const VOCABULARY = [
    { id: 1, level: 'A1', german: 'Hallo', english: 'hello', category: 'Greetings' },
    { id: 2, level: 'A1', german: 'Guten Morgen', english: 'good morning', category: 'Greetings' },
    { id: 3, level: 'A1', german: 'Guten Tag', english: 'good day', category: 'Greetings' },
    { id: 4, level: 'A1', german: 'Guten Abend', english: 'good evening', category: 'Greetings' },
    { id: 5, level: 'A1', german: 'Gute Nacht', english: 'good night', category: 'Greetings' },
    { id: 6, level: 'A1', german: 'willkommen', english: 'welcome', category: 'Greetings' },
    { id: 7, level: 'A1', german: 'Wie geht\'s?', english: 'how are you?', category: 'Greetings' },
    { id: 8, level: 'A1', german: 'Danke', english: 'thank you', category: 'Greetings' },
    { id: 9, level: 'A1', german: 'gern geschehen', english: 'You\'re welcome', category: 'Greetings' },
    { id: 10, level: 'A1', german: 'Bitte', english: 'please / you\'re welcome', category: 'Greetings' },
    { id: 11, level: 'A1', german: 'leider', english: 'unfortunately', category: 'Greetings' },
    { id: 12, level: 'A1', german: 'Auf wiedersehen', english: 'goodbye', category: 'Greetings' },
    { id: 13, level: 'A1', german: 'nicht schlecht', english: 'not bad', category: 'Greetings' },
    { id: 14, level: 'A1', german: 'so lala', english: 'so so', category: 'Greetings' },
    { id: 15, level: 'A1', german: 'freut mich', english: 'nice to meet you', category: 'Greetings' },
    { id: 16, level: 'A1', german: 'Was machen sie beruflich?', english: 'What do you do professionally?', category: 'Greetings' },
    { id: 17, level: 'A1', german: 'Ich arbeite als IT-Ingenieur', english: 'I work as an IT engineer', category: 'Greetings' },
    { id: 18, level: 'A1', german: 'noch einmal', english: 'one more time', category: 'Greetings' },
    { id: 19, level: 'A1', german: 'der Kollege', english: 'colleague', category: 'Work' },
    { id: 20, level: 'A1', german: 'der Mitarbeiter', english: 'employee', category: 'Work' },
    { id: 21, level: 'A1', german: 'der Arbeiter', english: 'worker', category: 'Work' },
    { id: 22, level: 'A1', german: 'der Chef', english: 'boss', category: 'Work' },
    { id: 23, level: 'A1', german: 'Ich heiße...', english: 'my name is...', category: 'Personal Info' },
    { id: 24, level: 'A1', german: 'Woher kommst du?', english: 'where are you from?', category: 'Personal Info' },
    { id: 25, level: 'A1', german: 'Ich komme aus...', english: 'I come from...', category: 'Personal Info' },
    { id: 26, level: 'A1', german: 'Ich bin ... Jahre alt', english: 'I am ... years old', category: 'Personal Info' },
    { id: 27, level: 'A1', german: 'Ich wohne in...', english: 'I live in...', category: 'Personal Info' },
    { id: 28, level: 'A1', german: 'Wie heißt du?', english: 'What is your name?', category: 'Personal Info' },
    { id: 29, level: 'A1', german: 'Wer bist du?', english: 'Who are you?', category: 'Personal Info' },
    { id: 30, level: 'A1', german: 'Wie geht es dir?', english: 'How are you?', category: 'Personal Info' },
    { id: 31, level: 'A1', german: 'Freut mich', english: 'Pleased to meet you', category: 'Personal Info' },
    { id: 32, level: 'A1', german: 'ledig', english: 'single', category: 'Personal Info' },
    { id: 33, level: 'A1', german: 'verheiratet', english: 'married', category: 'Personal Info' },
    { id: 34, level: 'A1', german: 'Ich bin Student(in)', english: 'I am a student', category: 'Personal Info' },
    { id: 35, level: 'A1', german: 'Beruf', english: 'profession / job', category: 'Personal Info' },
    { id: 36, level: 'A1', german: 'Hobbys', english: 'hobbies', category: 'Personal Info' },
    { id: 37, level: 'A1', german: 'die Telefonnummer', english: 'phone number', category: 'Personal Info' },
    { id: 38, level: 'A1', german: 'die Adresse', english: 'address', category: 'Personal Info' },
    { id: 39, level: 'A1', german: 'die Staatsangehörigkeit', english: 'nationality', category: 'Personal Info' },
    { id: 40, level: 'A1', german: 'Sprechen Sie Deutsch?', english: 'Do you speak German? (formal)', category: 'Personal Info' },
    { id: 41, level: 'A1', german: 'Ich spreche ein bisschen...', english: 'I speak a little...', category: 'Personal Info' },
    { id: 42, level: 'A1', german: 'meine Muttersprache', english: 'my native language', category: 'Personal Info' },
    { id: 43, level: 'A1', german: 'der Geburstag', english: 'birthday', category: 'Personal Info' },
    { id: 44, level: 'A1', german: 'der Arzt', english: 'doctor', category: 'Jobs' },
    { id: 45, level: 'A1', german: 'der Lehrer', english: 'teacher', category: 'Jobs' },
    { id: 46, level: 'A1', german: 'der Kellner', english: 'waiter', category: 'Jobs' },
    { id: 47, level: 'A1', german: 'der Polizist', english: 'police officer', category: 'Jobs' },
    { id: 48, level: 'A1', german: 'der Mechaniker', english: 'mechanic', category: 'Jobs' },
    { id: 49, level: 'A1', german: 'der Engenieur', english: 'Engineer', category: 'Jobs' },
    { id: 50, level: 'A1', german: 'der Student', english: 'student', category: 'Jobs' },
    { id: 51, level: 'A1', german: 'der Koch', english: 'cook', category: 'Jobs' },
    { id: 52, level: 'A1', german: 'die Mutter', english: 'mother', category: 'Family' },
    { id: 53, level: 'A1', german: 'der Vater', english: 'father', category: 'Family' },
    { id: 54, level: 'A1', german: 'die Eltern', english: 'parents', category: 'Family' },
    { id: 55, level: 'A1', german: 'der Bruder', english: 'brother', category: 'Family' },
    { id: 56, level: 'A1', german: 'die Schwester', english: 'sister', category: 'Family' },
    { id: 57, level: 'A1', german: 'das Geschwister', english: 'siblings', category: 'Family' },
    { id: 58, level: 'A1', german: 'die Frau', english: 'woman / wife', category: 'Family' },
    { id: 59, level: 'A1', german: 'der Mann', english: 'man / husband', category: 'Family' },
    { id: 60, level: 'A1', german: 'das Kind', english: 'child', category: 'Family' },
    { id: 61, level: 'A1', german: 'die Kinder', english: 'children', category: 'Family' },
    { id: 62, level: 'A1', german: 'die Familie', english: 'family', category: 'Family' },
    { id: 63, level: 'A1', german: 'der Freund / die Freundin', english: 'friend / boyfriend / girlfriend', category: 'Family' },
    { id: 64, level: 'A1', german: 'das Essen', english: 'food', category: 'Food & Drink' },
    { id: 65, level: 'A1', german: 'das Getränk', english: 'drink', category: 'Food & Drink' },
    { id: 66, level: 'A1', german: 'das Brot', english: 'bread', category: 'Food & Drink' },
    { id: 67, level: 'A1', german: 'das Brötchen', english: 'bread roll', category: 'Food & Drink' },
    { id: 68, level: 'A1', german: 'der Apfel', english: 'apple', category: 'Food & Drink' },
    { id: 69, level: 'A1', german: 'die Banane', english: 'banana', category: 'Food & Drink' },
    { id: 70, level: 'A1', german: 'das Wasser', english: 'water', category: 'Food & Drink' },
    { id: 71, level: 'A1', german: 'der Kaffee', english: 'coffee', category: 'Food & Drink' },
    { id: 72, level: 'A1', german: 'der Tee', english: 'tea', category: 'Food & Drink' },
    { id: 73, level: 'A1', german: 'das Bier', english: 'beer', category: 'Food & Drink' },
    { id: 74, level: 'A1', german: 'der Wein', english: 'wine', category: 'Food & Drink' },
    { id: 75, level: 'A1', german: 'die Milch', english: 'milk', category: 'Food & Drink' },
    { id: 76, level: 'A1', german: 'der Saft', english: 'juice', category: 'Food & Drink' },
    { id: 77, level: 'A1', german: 'das Frühstück', english: 'breakfast', category: 'Food & Drink' },
    { id: 78, level: 'A1', german: 'das Mittagessen', english: 'lunch', category: 'Food & Drink' },
    { id: 79, level: 'A1', german: 'das Abendessen', english: 'dinner', category: 'Food & Drink' },
    { id: 80, level: 'A1', german: 'die Suppe', english: 'soup', category: 'Food & Drink' },
    { id: 81, level: 'A1', german: 'der Salat', english: 'salad', category: 'Food & Drink' },
    { id: 82, level: 'A1', german: 'der Zucker', english: 'sugar', category: 'Food & Drink' },
    { id: 83, level: 'A1', german: 'das Salz', english: 'salt', category: 'Food & Drink' },
    { id: 84, level: 'A1', german: 'das Hähnchen', english: 'chicken', category: 'Food & Drink' },
    { id: 85, level: 'A1', german: 'der Fisch', english: 'fish', category: 'Food & Drink' },
    { id: 86, level: 'A1', german: 'das Ei', english: 'egg', category: 'Food & Drink' },
    { id: 87, level: 'A1', german: 'der Kuchen', english: 'cake', category: 'Food & Drink' },
    { id: 88, level: 'A1', german: 'der honig', english: 'honey', category: 'Food & Drink' },
    { id: 89, level: 'A1', german: 'die Marmelade', english: 'jam', category: 'Food & Drink' },
    { id: 90, level: 'A1', german: 'lecker', english: 'delicious', category: 'Food & Drink' },
    { id: 91, level: 'A1', german: 'der Käse', english: 'cheese', category: 'Food & Drink' },
    { id: 92, level: 'A1', german: 'Große', english: 'big', category: 'Measurement' },
    { id: 93, level: 'A1', german: 'kleine', english: 'small', category: 'Measurement' },
    { id: 94, level: 'A1', german: 'kurz', english: 'short', category: 'Measurement' },
    { id: 95, level: 'A1', german: 'lang', english: 'long', category: 'Measurement' },
    { id: 96, level: 'A1', german: 'das Obst', english: 'fruit', category: 'Fruits' },
    { id: 97, level: 'A1', german: 'der Apfel', english: 'apple', category: 'Fruits' },
    { id: 98, level: 'A1', german: 'die Banane', english: 'banana', category: 'Fruits' },
    { id: 99, level: 'A1', german: 'die Erdbeere', english: 'strawberry', category: 'Fruits' },
    { id: 100, level: 'A1', german: 'die Orangen', english: 'orange', category: 'Fruits' },
    { id: 101, level: 'A1', german: 'der Kasse', english: 'cashier', category: 'Supermarket' },
    { id: 102, level: 'A1', german: 'bar', english: 'cash', category: 'Supermarket' },
    { id: 103, level: 'A1', german: 'mit Karte', english: 'with card', category: 'Supermarket' },
    { id: 104, level: 'A1', german: 'der Kassenbon', english: 'receipt', category: 'Supermarket' },
    { id: 105, level: 'A1', german: 'zahlen', english: 'to pay', category: 'Supermarket' },
    { id: 106, level: 'A1', german: 'die Farbe', english: 'color', category: 'Colors' },
    { id: 107, level: 'A1', german: 'Blau', english: 'blue', category: 'Colors' },
    { id: 108, level: 'A1', german: 'Rot', english: 'red', category: 'Colors' },
    { id: 109, level: 'A1', german: 'Gelb', english: 'yellow', category: 'Colors' },
    { id: 110, level: 'A1', german: 'Grün', english: 'green', category: 'Colors' },
    { id: 111, level: 'A1', german: 'Weiß', english: 'white', category: 'Colors' },
    { id: 112, level: 'A1', german: 'Schwarz', english: 'black', category: 'Colors' },
    { id: 113, level: 'A1', german: 'Gelb', english: 'yellow', category: 'Colors' },
    { id: 114, level: 'A1', german: 'heute', english: 'today', category: 'Time' },
    { id: 115, level: 'A1', german: 'morgen', english: 'tomorrow', category: 'Time' },
    { id: 116, level: 'A1', german: 'gestern', english: 'yesterday', category: 'Time' },
    { id: 117, level: 'A1', german: 'jetzt', english: 'now', category: 'Time' },
    { id: 118, level: 'A1', german: 'bald', english: 'soon', category: 'Time' },
    { id: 119, level: 'A1', german: 'Uhr', english: 'o\'clock', category: 'Time' },
    { id: 120, level: 'A1', german: 'Stunde', english: 'hour', category: 'Time' },
    { id: 121, level: 'A1', german: 'Minute', english: 'minute', category: 'Time' },
    { id: 122, level: 'A1', german: 'Zeit', english: 'time', category: 'Time' },
    { id: 123, level: 'A1', german: 'immer', english: 'always', category: 'Time' },
    { id: 124, level: 'A1', german: 'oft', english: 'often', category: 'Time' },
    { id: 125, level: 'A1', german: 'manchmal', english: 'sometimes', category: 'Time' },
    { id: 126, level: 'A1', german: 'selten', english: 'rarely', category: 'Time' },
    { id: 127, level: 'A1', german: 'nie', english: 'never', category: 'Time' },
    { id: 128, level: 'A1', german: 'Viertel vor fünf', english: 'quarter to five', category: 'Time' },
    { id: 129, level: 'A1', german: 'Viertel nach fünf', english: 'quarter past five', category: 'Time' },
    { id: 130, level: 'A1', german: 'es ist halb acht', english: 'half past seven', category: 'Time' },
    { id: 131, level: 'A1', german: 'der Tag', english: 'day', category: 'Time' },
    { id: 132, level: 'A1', german: 'die Woche', english: 'week', category: 'Time' },
    { id: 133, level: 'A1', german: 'der Monat', english: 'month', category: 'Time' },
    { id: 134, level: 'A1', german: 'das Jahr', english: 'year', category: 'Time' },
    { id: 135, level: 'A1', german: 'das wochenende', english: 'weekend', category: 'Time' },
    { id: 136, level: 'A1', german: 'später', english: 'later', category: 'Time' },
    { id: 137, level: 'A1', german: 'in der nacht', english: 'at night', category: 'Time' },
    { id: 138, level: 'A1', german: 'am Deinstagnachmittag', english: 'on Wednesday afternoon', category: 'Time' },
    { id: 139, level: 'A1', german: 'am Mittwochabend', english: 'on Wednesday evening', category: 'Time' },
    { id: 140, level: 'A1', german: 'am Montag', english: 'on Monday', category: 'Time' },
    { id: 141, level: 'A1', german: 'heute Abend', english: 'tonight', category: 'Time' },
    { id: 142, level: 'A1', german: 'heute Morgen', english: 'this morning', category: 'Time' },
    { id: 143, level: 'A1', german: 'um 12:00 Uhr', english: 'at 12:00 o\'clock', category: 'Time' },
    { id: 144, level: 'A1', german: 'von 12:00 bis 13:15 Uhr', english: 'from 12:00 to 13:15', category: 'Time' },
    { id: 145, level: 'A1', german: 'nach dem Abendessen', english: 'after dinner', category: 'Time' },
    { id: 146, level: 'A1', german: 'nächste Woche', english: 'next week', category: 'Time' },
    { id: 147, level: 'A1', german: 'am kommenden sonntag', english: 'next Sunday', category: 'Time' },
    { id: 148, level: 'A1', german: 'Wie spät ist es?', english: 'What time is it?', category: 'Time' },
    { id: 149, level: 'A1', german: 'am letzten wochenende', english: 'last weekend', category: 'Time' },
    { id: 150, level: 'A1', german: 'Es ist zwei Uhr', english: 'It is two o\'clock', category: 'Time' },
    { id: 151, level: 'A1', german: 'Es ist zwei Uhr fuüfzhen', english: 'It is 02:15', category: 'Time' },
    { id: 152, level: 'A1', german: 'Wann gehst du zur Arbeit?', english: 'When do you go to work?', category: 'Time' },
    { id: 153, level: 'A1', german: 'Um wie viel Uhr?', english: 'At what time?', category: 'Time' },
    { id: 154, level: 'A1', german: 'Hast du um Samstag zeit?', english: 'Are you free on Saturday?', category: 'Time' },
    { id: 155, level: 'A1', german: 'Ja, ich bin frei', english: 'Yes, I am free', category: 'Time' },
    { id: 156, level: 'A1', german: 'Perfekt, bis dann!', english: 'Perfect, see you then!', category: 'Time' },
    { id: 157, level: 'A1', german: 'Montag', english: 'Monday', category: 'Days' },
    { id: 158, level: 'A1', german: 'Dienstag', english: 'Tuesday', category: 'Days' },
    { id: 159, level: 'A1', german: 'Mittwoch', english: 'Wednesday', category: 'Days' },
    { id: 160, level: 'A1', german: 'Donnerstag', english: 'Thursday', category: 'Days' },
    { id: 161, level: 'A1', german: 'Freitag', english: 'Friday', level: 'A1', category: 'Days' },
    { id: 162, level: 'A1', german: 'Samstag', english: 'Saturday', category: 'Days' },
    { id: 163, level: 'A1', german: 'Sonntag', english: 'Sunday', category: 'Days' },
    { id: 164, level: 'A1', german: 'Januar', english: 'January', category: 'Months' },
    { id: 165, level: 'A1', german: 'Februar', english: 'February', category: 'Months' },
    { id: 166, level: 'A1', german: 'März', english: 'March', category: 'Months' },
    { id: 167, level: 'A1', german: 'April', english: 'April', category: 'Months' },
    { id: 168, level: 'A1', german: 'Mai', english: 'May', category: 'Months' },
    { id: 169, level: 'A1', german: 'Juni', english: 'June', category: 'Months' },
    { id: 170, level: 'A1', german: 'Juli', english: 'July', category: 'Months' },
    { id: 171, level: 'A1', german: 'August', english: 'August', category: 'Months' },
    { id: 172, level: 'A1', german: 'September', english: 'September', category: 'Months' },
    { id: 173, level: 'A1', german: 'Oktober', english: 'October', category: 'Months' },
    { id: 174, level: 'A1', german: 'November', english: 'November', category: 'Months' },
    { id: 175, level: 'A1', german: 'Dezember', english: 'December', category: 'Months' },


    { id: 176, level: 'A1', german: 'eins', english: 'one', category: 'Numbers' },
    { id: 177, level: 'A1', german: 'zwei', english: 'two', category: 'Numbers' },
    { id: 178, level: 'A1', german: 'drei', english: 'three', category: 'Numbers' },
    { id: 179, level: 'A1', german: 'vier', english: 'four', category: 'Numbers' },
    { id: 180, level: 'A1', german: 'fünf', english: 'five', category: 'Numbers' },
    { id: 181, level: 'A1', german: 'sechs', english: 'six', category: 'Numbers' },
    { id: 182, level: 'A1', german: 'sieben', english: 'seven', category: 'Numbers' },
    { id: 183, level: 'A1', german: 'acht', english: 'eight', category: 'Numbers' },
    { id: 184, level: 'A1', german: 'neun', english: 'nine', category: 'Numbers' },
    { id: 185, level: 'A1', german: 'zehn', english: 'ten', category: 'Numbers' },
    { id: 186, level: 'A1', german: 'elf', english: 'eleven', category: 'Numbers' },
    { id: 187, level: 'A1', german: 'zwölf', english: 'twelve', category: 'Numbers' },
    { id: 188, level: 'A1', german: 'zwanzig', english: 'twenty', category: 'Numbers' },
    { id: 189, level: 'A1', german: 'dreißig', english: 'thirty', category: 'Numbers' },
    { id: 190, level: 'A1', german: 'vierzig', english: 'forty', category: 'Numbers' },
    { id: 191, level: 'A1', german: 'fünfzig', english: 'fifty', category: 'Numbers' },
    { id: 192, level: 'A1', german: 'hundert', english: 'one hundred', category: 'Numbers' },
    { id: 193, level: 'A1', german: 'erste', english: 'first', category: 'Ordinals' },
    { id: 194, level: 'A1', german: 'zweite', english: 'second', category: 'Ordinals' },
    { id: 195, level: 'A1', german: 'dritte', english: 'third', category: 'Ordinals' },
    { id: 196, level: 'A1', german: 'vierte', english: 'fourth', category: 'Ordinals' },
    { id: 197, level: 'A1', german: 'fünfte', english: 'fifth', category: 'Ordinals' },
    { id: 198, level: 'A1', german: 'der Bahnhof', english: 'train station', category: 'Transportation' },
    { id: 199, level: 'A1', german: 'der Flughafen', english: 'airport', category: 'Transportation' },
    { id: 200, level: 'A1', german: 'der Bus', english: 'bus', category: 'Transportation' },
    { id: 201, level: 'A1', german: 'die U-Bahn', english: 'underground', category: 'Transportation' },
    { id: 202, level: 'A1', german: 'das Auto', english: 'car', category: 'Transportation' },
    { id: 203, level: 'A1', german: 'das Fahrrad', english: 'bicycle', category: 'Transportation' },
    { id: 204, level: 'A1', german: 'der Zug', english: 'train', category: 'Transportation' },
    { id: 205, level: 'A1', german: 'die Straßenbahn', english: 'tram', category: 'Transportation' },
    { id: 206, level: 'A1', german: 'das Flugzeug', english: 'airplane', category: 'Transportation' },
    { id: 207, level: 'A1', german: 'das Taxi', english: 'taxi', category: 'Transportation' },
    { id: 208, level: 'A1', german: 'das Schiff', english: 'ship / boat', category: 'Transportation' },
    { id: 209, level: 'A1', german: 'zu Fuß gehen', english: 'to go on foot / to walk', category: 'Transportation' },
    { id: 210, level: 'A1', german: 'die Fahrkarte', english: 'ticket', category: 'Transportation' },
    { id: 211, level: 'A1', german: 'die Haltestelle', english: 'stop / station (bus or tram)', category: 'Transportation' },
    { id: 212, level: 'A1', german: 'der Bahnsteig', english: 'platform', category: 'Transportation' },
    { id: 213, level: 'A1', german: 'die Fahrgäste', english: 'passengers', category: 'Transportation' },
    { id: 214, level: 'A1', german: 'Schalter', english: 'check-in counter', category: 'Transportation' },
    { id: 215, level: 'A1', german: 'Auto mieten', english: 'car rental', category: 'Transportation' },
    { id: 216, level: 'A1', german: 'einsteigen', english: 'to get on / board', category: 'Transportation' },
    { id: 217, level: 'A1', german: 'aussteigen', english: 'to get off / exit', category: 'Transportation' },
    { id: 218, level: 'A1', german: 'umsteigen', english: 'to change trains', category: 'Transportation' },
    { id: 219, level: 'A1', german: 'fahren', english: 'to drive / to ride', level: 'A1', category: 'Transportation' },
    { id: 220, level: 'A1', german: 'abfahren', english: 'to leave / depart', category: 'Transportation' },
    { id: 221, level: 'A1', german: 'fliegen', english: 'to fly', category: 'Transportation' },
    { id: 222, level: 'A1', german: 'Wir nehmen den Bus.', english: 'We take the bus.', category: 'Transportation' },
    { id: 223, level: 'A1', german: 'rechts', english: 'right', category: 'Directions' },
    { id: 224, level: 'A1', german: 'links', english: 'left', category: 'Directions' },
    { id: 225, level: 'A1', german: 'geradeaus', english: 'straight ahead', category: 'Directions' },
    { id: 226, level: 'A1', german: 'da drüben', english: 'over there', category: 'Directions' },
    { id: 227, level: 'A1', german: 'hier', english: 'here', category: 'Directions' },
    { id: 228, level: 'A1', german: 'da / dort', english: 'there', category: 'Directions' },
    { id: 229, level: 'A1', german: 'oben', english: 'up / upstairs', category: 'Directions' },
    { id: 230, level: 'A1', german: 'unten', english: 'down / downstairs', category: 'Directions' },
    { id: 231, level: 'A1', german: 'vorne', english: 'at the front', category: 'Directions' },
    { id: 232, level: 'A1', german: 'hinten', english: 'at the back', category: 'Directions' },
    { id: 233, level: 'A1', german: 'um die Ecke', english: 'around the corner', category: 'Directions' },
    { id: 234, level: 'A1', german: 'an der Ampel', english: 'at the traffic light', category: 'Directions' },
    { id: 235, level: 'A1', german: 'die erste Straße', english: 'the first street', category: 'Directions' },
    { id: 236, level: 'A1', german: 'abbiegen', english: 'to turn', category: 'Directions' },
    { id: 237, level: 'A1', german: 'nach Hause', english: 'towards home', category: 'Directions' },
    { id: 238, level: 'A1', german: 'zurück', english: 'back / return', category: 'Directions' },
    { id: 239, level: 'A1', german: 'weit', english: 'far', category: 'Directions' },
    { id: 240, level: 'A1', german: 'nah', english: 'near', category: 'Directions' },
    { id: 241, level: 'A1', german: 'draußen', english: 'outside', level: 'A1', category: 'Directions' },
    { id: 242, level: 'A1', german: 'innen', english: 'inside', level: 'A1', category: 'Directions' },
    { id: 243, level: 'A1', german: 'auf dem Weg', english: 'on the way', category: 'Directions' },
    { id: 244, level: 'A1', german: 'auf der Straße', english: 'on the street', category: 'Directions' },
    { id: 245, level: 'A1', german: 'die Straße', english: 'street', category: 'Places' },
    { id: 246, level: 'A1', german: 'das Hotel', english: 'hotel', category: 'Places' },
    { id: 247, level: 'A1', german: 'die Stadt', english: 'city', category: 'Places' },
    { id: 248, level: 'A1', german: 'das Dorf', english: 'village', category: 'Places' },
    { id: 249, level: 'A1', german: 'die Haltestelle', english: 'stop', category: 'Places' },
    { id: 250, level: 'A1', german: 'die Schule', english: 'school', category: 'Education' },
    { id: 251, level: 'A1', german: 'die Universität', english: 'university', category: 'Education' },
    { id: 252, level: 'A1', german: 'das Büro', english: 'office', category: 'Work' },
    { id: 253, level: 'A1', german: 'das Museum', english: 'museum', category: 'Places' },
    { id: 254, level: 'A1', german: 'der Park', english: 'park', category: 'Places' },
    { id: 255, level: 'A1', german: 'die Bank', english: 'bank', category: 'Places' },
    { id: 256, level: 'A1', german: 'die Post', english: 'post office', category: 'Places' },
    { id: 257, level: 'A1', german: 'das Kino', english: 'cinema', category: 'Places' },
    { id: 258, level: 'A1', german: 'das Café', english: 'café', category: 'Places' },
    { id: 259, level: 'A1', german: 'das Restaurant', english: 'restaurant', category: 'Places' },
    { id: 260, level: 'A1', german: 'die Bibliothek', english: 'library', category: 'Places' },
    { id: 261, level: 'A1', german: 'der Supermarkt', english: 'supermarket', category: 'Places' },
    { id: 262, level: 'A1', german: 'das Geschäft', english: 'shop', category: 'Places' },
    { id: 263, level: 'A1', german: 'dort', english: 'there', category: 'Places' },
    { id: 264, level: 'A1', german: 'weit', english: 'far', category: 'Places' },
    { id: 265, level: 'A1', german: 'nah', english: 'near', category: 'Places' },
    { id: 266, level: 'A1', german: 'hier', english: 'here', category: 'Places' },
    { id: 267, level: 'A1', german: 'das Theater', english: 'theater', category: 'Places' },
    { id: 268, level: 'A1', german: 'die Apotheke', english: 'pharmacy', category: 'Places' },
    { id: 269, level: 'A1', german: 'der Garten', english: 'garden', category: 'Places' },
    { id: 270, level: 'A1', german: 'ins Restaurant', english: 'to the restaurant', category: 'Going Inside' },
    { id: 271, level: 'A1', german: 'ins Hotel', english: 'to the hotel', category: 'Going Inside' },
    { id: 272, level: 'A1', german: 'ins Dorf', english: 'to the village', category: 'Going Inside' },
    { id: 273, level: 'A1', german: 'ins Büro', english: 'to the office', category: 'Going Inside' },
    { id: 274, level: 'A1', german: 'ins Konzert', english: 'to the concert', category: 'Going Inside' },
    { id: 275, level: 'A1', german: 'ins Museum', english: 'to the museum', category: 'Going Inside' },
    { id: 276, level: 'A1', german: 'ins Geschäft', english: 'to the shop', category: 'Going Inside' },
    { id: 277, level: 'A1', german: 'in die Straße', english: 'to the street', category: 'Going Inside' },
    { id: 278, level: 'A1', german: 'in die Universität', english: 'to the university', category: 'Going Inside' },
    { id: 279, level: 'A1', german: 'in die Bibliothek', english: 'to the library', category: 'Going Inside' },
    { id: 280, level: 'A1', german: 'in den Park', english: 'to the park', category: 'Going Inside' },
    { id: 281, level: 'A1', german: 'in den Wald', english: 'to the forest', category: 'Going Inside' },
    { id: 282, level: 'A1', german: 'zum Supermarkt', english: 'to the supermarket', category: 'Going Inside' },
    { id: 283, level: 'A1', german: 'zur Haltestelle', english: 'to the stop', category: 'Going Inside' },
    { id: 284, level: 'A1', german: 'zur Bank', english: 'to the bank', category: 'Going Inside' },
    { id: 285, level: 'A1', german: 'zur Post', english: 'to the post office', category: 'Going Inside' },
    { id: 286, level: 'A1', german: 'zur Arbeit', english: 'to work', category: 'Going Inside' },
    { id: 287, level: 'A1', german: 'zum Kino', english: 'to the cinema', category: 'Going Inside' },
    { id: 288, level: 'A1', german: 'zum Theater', english: 'to the theater', category: 'Going Inside' },
    { id: 289, level: 'A1', german: 'zum Cafe', english: 'to the café', category: 'Going Inside' },
    { id: 290, level: 'A1', german: 'nach Berlin', english: 'to Berlin', category: 'Going Inside' },
    { id: 291, level: 'A1', german: 'nach Hause', english: 'to home', category: 'Going Inside' },
    { id: 292, level: 'A1', german: 'in die USA', english: 'to the USA', category: 'Going Inside' },
    { id: 293, level: 'A1', german: 'nach Deutschland', english: 'to Germany', category: 'Going Inside' },
    { id: 294, level: 'A1', german: 'in den Iran', english: 'to Iran', category: 'Going Inside' },
    { id: 295, level: 'A1', german: 'das Haus', english: 'house', category: 'Home' },
    { id: 296, level: 'A1', german: 'die Wohnung', english: 'flat', category: 'Home' },
    { id: 297, level: 'A1', german: 'das Zimmer', english: 'room', category: 'Home' },
    { id: 298, level: 'A1', german: 'das Wohnzimmer', english: 'living room', category: 'Home' },
    { id: 299, level: 'A1', german: 'die Küche', english: 'kitchen', category: 'Home' },
    { id: 300, level: 'A1', german: 'das Badezimmer', english: 'bathroom', category: 'Home' },
    { id: 301, level: 'A1', german: 'das Bett', english: 'bed', category: 'Home' },
    { id: 302, level: 'A1', german: 'der Tisch', english: 'table', category: 'Home' },
    { id: 303, level: 'A1', german: 'der Stuhl', english: 'chair', category: 'Home' },
    { id: 304, level: 'A1', german: 'die Lampe', english: 'lamp', category: 'Home' },
    { id: 305, level: 'A1', german: 'der Fernseher', english: 'television', category: 'Home' },
    { id: 306, level: 'A1', german: 'das Fenster', english: 'window', category: 'Home' },
    { id: 307, level: 'A1', german: 'die Tür', english: 'door', category: 'Home' },
    { id: 308, level: 'A1', german: 'der Schrank', english: 'wardrobe', category: 'Home' },
    { id: 309, level: 'A1', german: 'die Wand', english: 'wall', category: 'Home' },
    { id: 310, level: 'A1', german: 'das Sofa', english: 'sofa', category: 'Home' },
    { id: 311, level: 'A1', german: 'der Vorhang', english: 'curtain', category: 'Home' },
    { id: 312, level: 'A1', german: 'der Kühlschrank', english: 'fridge', level: 'A1', category: 'Home' },
    { id: 313, level: 'A1', german: 'die Waschmachine', english: 'washing machine', category: 'Home' },
    { id: 314, level: 'A1', german: 'die Hose', english: 'pants', category: 'Clothing' },
    { id: 315, level: 'A1', german: 'die Jacke', english: 'jacket', category: 'Clothing' },
    { id: 316, level: 'A1', german: 'die Kleidung', level: 'A1', english: 'clothing', category: 'Clothing' },
    { id: 317, level: 'A1', german: 'die Schuhe', english: 'shoes', category: 'Clothing' },
    { id: 318, level: 'A1', german: 'das Hemd', english: 'shirt', category: 'Clothing' },
    { id: 319, level: 'A1', german: 'der Hut', english: 'hat', category: 'Clothing' },
    { id: 320, level: 'A1', german: 'die Hochzeit', english: 'wedding', category: 'Events' },
    { id: 321, level: 'A1', german: 'Fest', english: 'party', category: 'Events' },
    { id: 322, level: 'A1', german: 'aufstehen', english: 'to get up', category: 'Verbs' },
    { id: 323, level: 'A1', german: 'hoffen', english: 'to hope', category: 'Verbs' },
    { id: 324, level: 'A1', german: 'geben', english: 'to give', category: 'Verbs' },
    { id: 325, level: 'A1', german: 'frühstücken', english: 'to eat breakfast', category: 'Verbs' },
    { id: 326, level: 'A1', german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { id: 327, level: 'A1', german: 'lernen', english: 'to study / learn', category: 'Verbs' },
    { id: 328, level: 'A1', german: 'essen', english: 'to eat', category: 'Verbs' },
    { id: 329, level: 'A1', german: 'trinken', english: 'to drink', category: 'Verbs' },
    { id: 330, level: 'A1', german: 'fernsehen', english: 'to watch TV', category: 'Verbs' },
    { id: 331, level: 'A1', german: 'schlafen', english: 'to sleep', category: 'Verbs' },
    { id: 332, level: 'A1', german: 'treffen', english: 'to meet', category: 'Verbs' },
    { id: 333, level: 'A1', german: 'lesen', english: 'to read', category: 'Verbs' },
    { id: 334, level: 'A1', german: 'schreiben', english: 'to write', category: 'Verbs' },
    { id: 335, level: 'A1', german: 'sprechen', english: 'to speak', category: 'Verbs' },
    { id: 336, level: 'A1', german: 'gehen', english: 'to go', category: 'Verbs' },
    { id: 337, level: 'A1', german: 'kommen', english: 'to come', category: 'Verbs' },
    { id: 338, level: 'A1', german: 'fahren', english: 'to drive / travel', category: 'Verbs' },
    { id: 339, level: 'A1', german: 'rennen / laufen', english: 'to run', category: 'Verbs' },
    { id: 340, level: 'A1', german: 'spielen', english: 'to play', category: 'Verbs' },
    { id: 341, level: 'A1', german: 'kochen', english: 'to cook', category: 'Verbs' },
    { id: 342, level: 'A1', german: 'bleiben', english: 'to stay, remain', category: 'Verbs' },
    { id: 343, level: 'A1', german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { id: 344, level: 'A1', german: 'leben', english: 'to live', category: 'Verbs' },
    { id: 345, level: 'A1', german: 'tun', english: 'to do', category: 'Verbs' },
    { id: 346, level: 'A1', german: 'rauchen', english: 'to smoke', category: 'Verbs' },
    { id: 347, level: 'A1', german: 'fragen', english: 'to ask', category: 'Verbs' },
    { id: 348, level: 'A1', german: 'tragen', english: 'to wear', category: 'Verbs' },
    { id: 349, level: 'A1', german: 'passieren', english: 'to happen', category: 'Verbs' },
    { id: 350, level: 'A1', german: 'singen', english: 'to sing', category: 'Verbs' },
    { id: 351, level: 'A1', german: 'einschlafen', english: 'to fall sleep', category: 'Verbs' },
    { id: 352, level: 'A1', german: 'vorstellen', english: 'to present', category: 'Verbs' },
    { id: 353, level: 'A1', german: 'benutzen', english: 'to use', category: 'Verbs' },
    { id: 354, level: 'A1', german: 'öffnen', english: 'to open', category: 'Verbs' },
    { id: 355, level: 'A1', german: 'schließen', english: 'to close', category: 'Verbs' },
    { id: 356, level: 'A1', german: 'buchstabieren', english: 'to spell', category: 'Verbs' },
    { id: 357, level: 'A1', german: 'tanzen', english: 'to dance', category: 'Verbs' },
    { id: 358, level: 'A1', german: 'zurück/schreiben', english: 'to write back', category: 'Verbs' },
    { id: 359, level: 'A1', german: 'Kellner', english: 'waiter', category: 'Restuarant' },
    { id: 360, level: 'A1', german: 'Kellnerin', english: 'waitress', category: 'Restuarant' },
    { id: 361, level: 'A1', german: 'Gast', english: 'guest', category: 'Restuarant' },
    { id: 362, level: 'A1', german: 'das Messer', english: 'knife', category: 'Restuarant' },
    { id: 363, level: 'A1', german: 'die Gabel', english: 'fork', category: 'Restuarant' },
    { id: 364, level: 'A1', german: 'der Löffel', english: 'spoon', category: 'Restuarant' },
    { id: 365, level: 'A1', german: 'der Teller', english: 'plate', category: 'Restuarant' },
    { id: 366, level: 'A1', german: 'das Glas', english: 'glass', category: 'Restuarant' },
    { id: 367, level: 'A1', german: 'die Tasse', english: 'cup', category: 'Restuarant' },
    { id: 368, level: 'A1', german: 'die Serviette', english: 'napkin', category: 'Restuarant' },
    { id: 369, level: 'A1', german: 'die Flasche', english: 'bottle', category: 'Restuarant' },
    { id: 370, level: 'A1', german: 'Gemüsesuppe', english: 'vegetable soup', category: 'Restuarant' },
    { id: 371, level: 'A1', german: 'die Speisekarte', english: 'menu', category: 'Restuarant' },
    { id: 372, level: 'A1', german: 'die Rechnung', english: 'bill / check', category: 'Restuarant' },
    { id: 373, level: 'A1', german: 'das Salz', english: 'salt', category: 'Restuarant' },
    { id: 374, level: 'A1', german: 'Schokoladenkuchen', english: 'chocolate cake', category: 'Restuarant' },
    { id: 375, level: 'A1', german: 'der Pfeffer', english: 'pepper', category: 'Restuarant' },
    { id: 376, level: 'A1', german: 'der Zucker', english: 'sugar', category: 'Restuarant' },
    { id: 377, level: 'A1', german: 'bestellen', english: 'to order', category: 'Restuarant' },
    { id: 378, level: 'A1', german: 'bezahlen', english: 'to pay', category: 'Restuarant' },
    { id: 379, level: 'A1', german: 'frühstücken', english: 'to eat breakfast', category: 'Restuarant' },
    { id: 380, level: 'A1', german: 'Kann ich bitte die Speisekarte haben?', english: 'Can I have the menu?', category: 'Restuarant' },
    { id: 381, level: 'A1', german: 'Vorspeise', english: 'appetizer', category: 'Restuarant' },
    { id: 382, level: 'A1', german: 'Hauptgericht', english: 'main course', category: 'Restuarant' },
    { id: 383, level: 'A1', german: 'Nachtisch', english: 'dessert', category: 'Restuarant' },
    { id: 384, level: 'A1', german: 'Getraenk', english: 'drink', category: 'Restuarant' },
    { id: 385, level: 'A1', german: 'Ich möchte eine Suppe', english: 'I would like soup', category: 'Restuarant' },
    { id: 386, level: 'A1', german: 'Möchten Sie noch etwas?', english: 'Would you like anything else?', category: 'Restuarant' },
    { id: 387, level: 'A1', german: 'Was möchtest du trinken?', english: 'What would you like to drink?', category: 'Restuarant' },
    { id: 388, level: 'A1', german: 'Das schmeckt gut', english: 'That tastes good', category: 'Restuarant' },
    { id: 389, level: 'A1', german: 'Prost', english: 'cheers', category: 'Restuarant' },
    { id: 390, level: 'A1', german: 'Guten Appetit', english: 'good appetite', category: 'Restuarant' },
    { id: 391, level: 'A1', german: 'Wo', english: 'Where', category: 'W Frage' },
    { id: 392, level: 'A1', german: 'Woher', english: 'Where from', category: 'W Frage' },
    { id: 393, level: 'A1', german: 'Wohin', english: 'Where to', category: 'W Frage' },
    { id: 394, level: 'A1', german: 'Wann', english: 'When', category: 'W Frage' },
    { id: 395, level: 'A1', german: 'Warum', english: 'Why', category: 'W Frage' },
    { id: 396, level: 'A1', german: 'Wie', english: 'How', category: 'W Frage' },
    { id: 397, level: 'A1', german: 'Wie oft', english: 'How often', category: 'W Frage' },
    { id: 398, level: 'A1', german: 'Wie viel', english: 'How much', category: 'W Frage' },
    { id: 399, level: 'A1', german: 'Wie viele', english: 'How many', category: 'W Frage' },
    { id: 400, level: 'A1', german: 'Was', english: 'What', category: 'W Frage' },
    { id: 401, level: 'A1', german: 'Wer', english: 'Who', category: 'W Frage' },
    { id: 402, level: 'A1', german: 'Welche/r/s', english: 'Which', category: 'W Frage' },
    { id: 403, level: 'A1', german: 'der Hund', english: 'dog', category: 'Animals' },
    { id: 404, level: 'A1', german: 'die Katze', english: 'cat', category: 'Animals' },
    { id: 405, level: 'A1', german: 'das Pferd', english: 'horse', category: 'Animals' },
    { id: 406, level: 'A1', german: 'das Schwein', english: 'pig', category: 'Animals' },
    { id: 407, level: 'A1', german: 'die Kuh', english: 'cow', category: 'Animals' },
    { id: 408, level: 'A1', german: 'der Vogel', english: 'bird', category: 'Animals' },
    { id: 409, level: 'A1', german: 'der Fisch', english: 'fish', category: 'Animals' },
    { id: 410, level: 'A1', german: 'die Maus', english: 'mouse', category: 'Animals' },
    { id: 411, level: 'A1', german: 'das Kaninchen', english: 'rabbit', category: 'Animals' },
    { id: 412, level: 'A1', german: 'der Elefant', english: 'elephant', category: 'Animals' },
    { id: 413, level: 'A1', german: 'der Löwe', english: 'lion', category: 'Animals' },
    { id: 414, level: 'A1', german: 'die Schlange', english: 'snake', category: 'Animals' },
    { id: 415, level: 'A1', german: 'die Spinne', english: 'spider', level: 'A1', category: 'Animals' },
    { id: 416, level: 'A1', german: 'die Biene', english: 'bee', category: 'Animals' },
    { id: 417, level: 'A1', german: 'die Ente', english: 'duck', category: 'Animals' },
    { id: 418, level: 'A1', german: 'das Buch', english: 'book', category: 'Stationery' },
    { id: 419, level: 'A1', german: 'der Brief', english: 'letter', category: 'Stationery' },
    { id: 420, level: 'A1', german: 'die Postkarte', english: 'postcard', category: 'Stationery' },
    { id: 421, level: 'A1', german: 'der Stift', english: 'pen', category: 'Stationery' },
    { id: 422, level: 'A1', german: 'das Papier', english: 'paper', category: 'Stationery' },
    { id: 423, level: 'A1', german: 'ArmbandUhr', english: 'wristwatch', category: 'Accessory' },
    { id: 424, level: 'A1', german: 'die Kamera', english: 'camera', category: 'Accessory' },
    { id: 425, level: 'A1', german: 'der Computer', english: 'computer', category: 'Accessory' },
    { id: 426, level: 'A1', german: 'das Handy', english: 'phone', category: 'Accessory' },
    { id: 427, level: 'A1', german: 'die Tasche', english: 'bag', category: 'Accessory' },
    { id: 428, level: 'A1', german: 'der Rucksack', english: 'backpack', category: 'Accessory' },
    { id: 429, level: 'A1', german: 'das Gepäck', english: 'suitcase', category: 'Accessory' },
    { id: 430, level: 'A1', german: 'der Stoff', english: 'fabric', category: 'Materials' },
    { id: 431, level: 'A1', german: 'das Holz', english: 'wood', category: 'Materials' },
    { id: 432, level: 'A1', german: 'das Metal', english: 'metal', category: 'Materials' },
    { id: 433, level: 'A1', german: 'das Leder', english: 'leather', category: 'Materials' },
    { id: 434, level: 'A1', german: 'das Glas', english: 'glass', category: 'Materials' },
    { id: 435, level: 'A1', german: 'der Kunststoff', english: 'plastic', category: 'Materials' },
    { id: 436, level: 'A1', german: 'haben', english: 'to have', category: 'Accusative Verbs' },
    { id: 437, level: 'A1', german: 'brauchen', english: 'to need', category: 'Accusative Verbs' },
    { id: 438, level: 'A1', german: 'parken', english: 'to park', category: 'Accusative Verbs' },
    { id: 439, level: 'A1', german: 'essen', english: 'to eat', category: 'Accusative Verbs' },
    { id: 440, level: 'A1', german: 'trinken', english: 'to drink', category: 'Accusative Verbs' },
    { id: 441, level: 'A1', german: 'sehen', english: 'to see', category: 'Accusative Verbs' },
    { id: 442, level: 'A1', german: 'hören', english: 'to hear', category: 'Accusative Verbs' },
    { id: 443, level: 'A1', german: 'kaufen', english: 'to buy', category: 'Accusative Verbs' },
    { id: 444, level: 'A1', german: 'bestellen', english: 'to order', category: 'Accusative Verbs' },
    { id: 445, level: 'A1', german: 'suchen', english: 'to look for', category: 'Accusative Verbs' },
    { id: 446, level: 'A1', german: 'finden', english: 'to find', category: 'Accusative Verbs' },
    { id: 447, level: 'A1', german: 'kochen', english: 'to cook', category: 'Accusative Verbs' },
    { id: 448, level: 'A1', german: 'verstehen', english: 'to understand', category: 'Accusative Verbs' },
    { id: 449, level: 'A1', german: 'besuchen', english: 'to visit', category: 'Accusative Verbs' },
    { id: 450, level: 'A1', german: 'anrufen', english: 'to call (on phone)', category: 'Accusative Verbs' },
    { id: 451, level: 'A1', german: 'schreiben', english: 'to write', category: 'Accusative Verbs' },
    { id: 452, level: 'A1', german: 'kennen', english: 'to know', category: 'Accusative Verbs' },
    { id: 453, level: 'A1', german: 'helfen', english: 'to help', category: 'Dative Verbs' },
    { id: 454, level: 'A1', german: 'danken', english: 'to thank', category: 'Dative Verbs' },
    { id: 455, level: 'A1', german: 'gefallen', english: 'to please / to like', category: 'Dative Verbs' },
    { id: 456, level: 'A1', german: 'gehören', english: 'to belong to', category: 'Dative Verbs' },
    { id: 457, level: 'A1', german: 'gratulieren', english: 'to congratulate', category: 'Dative Verbs' },
    { id: 458, level: 'A1', german: 'passen', english: 'to fit', category: 'Dative Verbs' },
    { id: 459, level: 'A1', german: 'antworten', english: 'to answer', category: 'Dative Verbs' },
    { id: 460, level: 'A1', german: 'zuhören', english: 'to listen to', category: 'Dative Verbs' },
    { id: 461, level: 'A1', german: 'schmecken', english: 'to taste (good) to', category: 'Dative Verbs' },
    { id: 462, level: 'A1', german: 'glauben', english: 'to believe', category: 'Dative Verbs' },
    { id: 463, level: 'A1', german: 'vertrauen', english: 'to trust', category: 'Dative Verbs' },
    { id: 464, level: 'A1', german: 'verzeihen', english: 'to forgive', category: 'Dative Verbs' },
    { id: 465, level: 'A1', german: 'wehtun', english: 'to hurt', category: 'Dative Verbs' },
    { id: 466, level: 'A1', german: 'folgen', english: 'to follow', category: 'Dative Verbs' },
    { id: 467, level: 'A1', german: 'passieren', english: 'to happen to', category: 'Dative Verbs' },
    { id: 468, level: 'A1', german: 'mitkommen', english: 'to come with', category: 'Separable Verbs' },
    { id: 469, level: 'A1', german: 'einsteigen', english: 'to get in / board', category: 'Separable Verbs' },
    { id: 470, level: 'A1', german: 'aufmachen', english: 'to open', category: 'Separable Verbs' },
    { id: 471, level: 'A1', german: 'mitspielen', english: 'to play with', category: 'Separable Verbs' },
    { id: 472, level: 'A1', german: 'das Wetter', english: 'weather', category: 'Weather' },
    { id: 473, level: 'A1', german: 'die Sonne', english: 'sun', category: 'Weather' },
    { id: 474, level: 'A1', german: 'der Regen', english: 'rain', category: 'Weather' },
    { id: 475, level: 'A1', german: 'der Schnee', english: 'snow', category: 'Weather' },
    { id: 476, level: 'A1', german: 'der Wind', english: 'wind', category: 'Weather' },
    { id: 477, level: 'A1', german: 'warm', english: 'warm', category: 'Weather' },
    { id: 478, level: 'A1', german: 'kalt', english: 'cold', category: 'Weather' },
    { id: 479, level: 'A1', german: 'heiß', english: 'hot', category: 'Weather' },
    { id: 480, level: 'A1', german: 'kühl', english: 'cool', category: 'Weather' },
    { id: 481, level: 'A1', german: 'bewölkt', english: 'cloudy', category: 'Weather' },
    { id: 482, level: 'A1', german: 'neblig', english: 'foggy', category: 'Weather' },
    { id: 483, level: 'A1', german: 'der Urlaub', english: 'vacation', category: 'Vacation' },
    { id: 484, level: 'A1', german: 'auf', english: 'on', category: 'Prepositions' },
    { id: 485, level: 'A1', german: 'an', english: 'at', category: 'Prepositions' },
    { id: 486, level: 'A1', german: 'ab', english: 'from - Dativ', category: 'Prepositions' },
    { id: 487, level: 'A1', german: 'bei', english: 'at - Dativ', category: 'Prepositions' },
    { id: 488, level: 'A1', german: 'durch', english: 'through - Akku', category: 'Prepositions' },
    { id: 489, level: 'A1', german: 'im', english: 'in', category: 'Prepositions' },
    { id: 490, level: 'A1', german: 'in', english: 'in', category: 'Prepositions' },
    { id: 491, level: 'A1', german: 'mit', english: 'with - Dativ', category: 'Prepositions' },
    { id: 492, level: 'A1', german: 'nach', english: 'after - Dativ', category: 'Prepositions' },
    { id: 493, level: 'A1', german: 'unter', english: 'under', category: 'Prepositions' },
    { id: 494, level: 'A1', german: 'zu', english: 'to - Dativ', category: 'Prepositions' },
    { id: 495, level: 'A1', german: 'hinter', english: 'behind', category: 'Prepositions' },
    { id: 496, level: 'A1', german: 'vor', english: 'before', category: 'Prepositions' },
    { id: 497, level: 'A1', german: 'ohne', english: 'without - Akku', category: 'Prepositions' },
    { id: 498, level: 'A1', german: 'mit', english: 'with', category: 'Prepositions' },
    { id: 499, level: 'A1', german: 'außer', english: 'except - Dativ', category: 'Prepositions' },
    { id: 500, level: 'A1', german: 'um', english: 'around - Akku', category: 'Prepositions' },
    { id: 501, level: 'A1', german: 'gegen', english: 'against - Akku', category: 'Prepositions' },
    { id: 502, level: 'A1', german: 'gegenüber', english: 'in front of - Dativ', category: 'Prepositions' },
    { id: 503, level: 'A1', german: 'Nach', english: 'after', category: 'Prepositions' },
    { id: 504, level: 'A1', german: 'aus', english: 'from - Dativ', category: 'Prepositions' },
    { id: 505, level: 'A1', german: 'von', english: 'from - Dativ', category: 'Prepositions' },
    { id: 506, level: 'A1', german: 'seit', english: 'since (for) - Dativ', category: 'Prepositions' },
    { id: 507, level: 'A1', german: 'nebe', english: 'beside', level: 'A1', category: 'Prepositions' },
    { id: 508, level: 'A1', german: 'zwischen', english: 'between', category: 'Prepositions' },
    { id: 509, level: 'A1', german: 'für', english: 'for - Akku', category: 'Prepositions' },
    { id: 510, level: 'A1', german: 'bis', english: 'until - Akku', category: 'Prepositions' },
    { id: 511, level: 'A1', german: 'der Arzt / die Ärztin', english: 'doctor', category: 'Health' },
    { id: 512, level: 'A1', german: 'der Zahnarzt / die Zahnärztin', english: 'dentist', category: 'Health' },
    { id: 513, level: 'A1', german: 'das Krankenhaus', english: 'hospital', category: 'Health' },
    { id: 514, level: 'A1', german: 'die Apotheke', english: 'pharmacy', category: 'Health' },
    { id: 515, level: 'A1', german: 'das Rezept', english: 'prescription', category: 'Health' },
    { id: 516, level: 'A1', german: 'die Tablette', english: 'tablet', category: 'Health' },
    { id: 517, level: 'A1', german: 'der Schmerz', english: 'pain', category: 'Health' },
    { id: 518, level: 'A1', german: 'das Fieber', english: 'fever', category: 'Health' },
    { id: 519, level: 'A1', german: 'die Erkältung', english: 'cold (sick)', category: 'Health' },
    { id: 520, level: 'A1', german: 'der Husten', english: 'cough', category: 'Health' },
    { id: 521, level: 'A1', german: 'der Kopf', english: 'head', category: 'Body' },
    { id: 522, level: 'A1', german: 'die Hand', english: 'hand', category: 'Body' },
    { id: 523, level: 'A1', german: 'der Arm', english: 'arm', category: 'Body' },
    { id: 524, level: 'A1', german: 'das Bein', english: 'leg', category: 'Body' },
    { id: 525, level: 'A1', german: 'der Rücken', english: 'back', category: 'Body' },
    { id: 526, level: 'A1', german: 'die Nase', english: 'nose', category: 'Body' },
    { id: 527, level: 'A1', german: 'der Mund', english: 'mouth', category: 'Body' },
    { id: 528, level: 'A1', german: 'das Auge', english: 'eye', category: 'Body' },
    { id: 529, level: 'A1', german: 'der Fuß', english: 'foot', category: 'Body' },
    { id: 530, level: 'A1', german: 'das Herz', english: 'heart', category: 'Body' },
    { id: 531, level: 'A1', german: 'das Gesicht', english: 'face', category: 'Body' },
    { id: 532, level: 'A1', german: 'groß', english: 'big / tall', category: 'Adjectives' },
    { id: 533, level: 'A1', german: 'klein', english: 'small / short', category: 'Adjectives' },
    { id: 534, level: 'A1', german: 'schön', english: 'beautiful', category: 'Adjectives' },
    { id: 535, level: 'A1', german: 'hässlich', english: 'ugly', category: 'Adjectives' },
    { id: 536, level: 'A1', german: 'alt', english: 'old', category: 'Adjectives' },
    { id: 537, level: 'A1', german: 'jung', english: 'young', category: 'Adjectives' },
    { id: 538, level: 'A1', german: 'neu', english: 'new', category: 'Adjectives' },
    { id: 539, level: 'A1', german: 'gut', english: 'good', category: 'Adjectives' },
    { id: 540, level: 'A1', german: 'schlecht', english: 'bad', category: 'Adjectives' },
    { id: 541, level: 'A1', german: 'freundlich', english: 'friendly', category: 'Adjectives' },
    { id: 542, level: 'A1', german: 'teuer', english: 'expensive', category: 'Adjectives' },
    { id: 543, level: 'A1', german: 'billig, güenstig', english: 'cheap', category: 'Adjectives' },
    { id: 544, level: 'A1', german: 'einfach', english: 'easy', category: 'Adjectives' },
    { id: 545, level: 'A1', german: 'schwer', english: 'difficult', category: 'Adjectives' },
    { id: 546, level: 'A1', german: 'ruhig', english: 'quiet', category: 'Adjectives' },
    { id: 547, level: 'A1', german: 'laut', english: 'loud', category: 'Adjectives' },
    { id: 548, level: 'A1', german: 'sauber', english: 'clean', category: 'Adjectives' },
    { id: 549, level: 'A1', german: 'schmutzig', english: 'dirty', category: 'Adjectives' },
    { id: 550, level: 'A1', german: 'nett', english: 'nice', category: 'Adjectives' },
    { id: 551, level: 'A1', german: 'langweilig', english: 'boring', category: 'Adjectives' },
    { id: 552, level: 'A1', german: 'interessant', english: 'interesting', category: 'Adjectives' },
    { id: 553, level: 'A1', german: 'lecker', english: 'tasty', category: 'Adjectives' },
    { id: 554, level: 'A1', german: 'müde', english: 'tired', category: 'Adjectives' },
    { id: 555, level: 'A1', german: 'gesund', english: 'healthy', category: 'Adjectives' },
    { id: 556, level: 'A1', german: 'krank', english: 'sick', category: 'Adjectives' },
    { id: 557, level: 'A1', german: 'lustig', english: 'funny', category: 'Adjectives' },
    { id: 558, level: 'A1', german: 'müde', english: 'tired', category: 'Adjectives' },
    { id: 559, level: 'A1', german: 'praktisch', english: 'usefull and practical', category: 'Adjectives' },
    { id: 560, level: 'A1', german: 'modern', english: 'modern', category: 'Adjectives' },
    { id: 561, level: 'A1', german: 'schnell', english: 'fast', category: 'Adjectives' },
    { id: 562, level: 'A1', german: 'langsam', english: 'slow', category: 'Adjectives' },
    { id: 563, level: 'A1', german: 'Zeitung lesen', english: 'reading the newspaper', category: 'Hobbies' },
    { id: 564, level: 'A1', german: 'das Buch', english: 'book', category: 'Hobbies' },
    { id: 565, level: 'A1', german: 'der Film', english: 'movie', category: 'Hobbies' },
    { id: 566, level: 'A1', german: 'das Spiel', english: 'game', category: 'Hobbies' },
    { id: 567, level: 'A1', german: 'der Sport', english: 'sport', category: 'Hobbies' },
    { id: 568, level: 'A1', german: 'die Musik', english: 'music', category: 'Hobbies' },
    { id: 569, level: 'A1', german: 'die Fotografie', english: 'photography', category: 'Hobbies' },
    { id: 570, level: 'A1', german: 'das Fitnessstudio', english: 'gym', category: 'Hobbies' },
    { id: 571, level: 'A1', german: 'Fußball spielen', english: 'playing football', category: 'Hobbies' },
    { id: 572, level: 'A1', german: 'Gittare spielen', english: 'playing Guitar', category: 'Hobbies' },
    { id: 573, level: 'A1', german: 'das Klavier', english: 'piano', category: 'Hobbies' },
    { id: 574, level: 'A1', german: 'Schwimmbad gehen', english: 'swimming', category: 'Hobbies' },

    { id: 575, level: 'A1', german: 'im Herbst', english: 'in autumn', category: 'Seasons' },
    { id: 576, level: 'A1', german: 'im Sommer', english: 'in summer', category: 'Seasons' },
    { id: 577, level: 'A1', german: 'im Winter', english: 'in winter', category: 'Seasons' },
    { id: 578, level: 'A1', german: 'im Frühling', english: 'in spring', category: 'Seasons' },
    { id: 579, level: 'A1', german: 'im Januar', english: 'in January', category: 'Time' },
    { id: 580, level: 'A1', german: 'vor 5 Jahren', english: '5 years ago', category: 'Time' },
    { id: 581, level: 'A1', german: 'ans Meer', english: 'to the sea', category: 'Going Inside' },
    { id: 582, level: 'A1', german: 'der Urlaub', english: 'vacation / leave', category: 'Work' },
    { id: 583, level: 'A1', german: 'der See', english: 'lake', category: 'Going Inside' },
    { id: 584, level: 'A1', german: 'das Wetter', english: 'weather', category: 'Weather' },
    { id: 585, level: 'A1', german: 'der Regen', english: 'rain', category: 'Weather' },
    { id: 586, level: 'A1', german: 'der Schnee', english: 'snow', category: 'Weather' },
    { id: 587, level: 'A1', german: 'der Wind', english: 'wind', category: 'Weather' },
    { id: 588, level: 'A1', german: 'Es ist windig', english: 'it is windy', category: 'Weather' },
    { id: 589, level: 'A1', german: 'Es ist kalt', english: 'it is cold', category: 'Weather' },
    { id: 590, level: 'A1', german: 'Es ist heiß', english: 'it is hot', category: 'Weather' },
    { id: 591, level: 'A1', german: 'Es ist sonnig', english: 'it is sunny', category: 'Weather' },
    { id: 592, level: 'A1', german: 'Es ist bewölkt', english: 'it is cloudy', category: 'Weather' },
    { id: 593, level: 'A1', german: 'Es ist neblig', english: 'it is foggy', category: 'Weather' },
    { id: 594, level: 'A1', german: 'Es regnet', english: 'it is raining', category: 'Weather' },
    { id: 595, level: 'A1', german: 'früh', english: 'early', category: 'Time' },
    { id: 596, level: 'A1', german: 'stehen', english: 'to stand', category: 'Verbs' },
    { id: 597, level: 'A1', german: 'Ich fahre mit dem Bus.', english: 'I go with the bus.', category: 'Transportation' },
    { id: 598, level: 'A1', german: 'ich gehe zu fuß.', english: 'I go on foot.', category: 'Transportation' },
    { id: 599, level: 'A1', german: 'das ist weit von hier', english: 'That is far from here', category: 'Directions' },
    { id: 600, level: 'A1', german: 'das Geld', english: 'money', category: 'Supermarket' },
    { id: 601, level: 'A1', german: 'tut mir leid', english: 'I am sorry', category: 'Greetings' },
    { id: 602, level: 'A1', german: 'der Herd', english: 'stove', category: 'Home' },
    { id: 603, level: 'A1', german: 'der Mülleimer', english: 'trash can / bin', category: 'Home' },
    { id: 604, level: 'A1', german: 'vermissen', english: 'to miss', category: 'Verbs' },
    { id: 605, level: 'A1', german: 'die Nachbarn', english: 'neighbours', category: 'Home' },
    { id: 606, level: 'A1', german: 'zweimal pro woche', english: 'twice a week', category: 'Time' },
    { id: 607, level: 'A1', german: 'das Stadtzentrum', english: 'city center', category: 'Places' },
    { id: 608, level: 'A1', german: 'der Schlüssel', english: 'key', category: 'Accessory' },
    { id: 609, level: 'A1', german: 'verlieren', english: 'lose', category: 'Verbs' },
    { id: 610, level: 'A1', german: 'die Treppe', english: 'stairs', category: 'Home' },
    { id: 611, level: 'A1', german: 'die Aufzug', english: 'elevator', category: 'Home' },
    { id: 612, level: 'A1', german: 'Wie hoch ist die Miete?', english: 'How much is the rent?', category: 'Home' },
    { id: 613, level: 'A1', german: 'Wie viel kostet die Wohnung?', english: 'How much is the apartment?', category: 'Home' },
    { id: 614, level: 'A1', german: 'Wie groß ist die Wohnung?', english: 'How big is the apartment?', category: 'Home' },
    { id: 615, level: 'A1', german: 'Wie viele Zimmer hat die Wohnung?', english: 'How many rooms does the apartment have?', category: 'Home' },
    { id: 616, level: 'A1', german: 'Gibt es eine Küche?', english: 'Is there a kitchen?', category: 'Home' },
    { id: 617, level: 'A1', german: 'Ab wann ist die Wohnung frei?', english: 'When is the apartment free?', category: 'Home' },
    { id: 618, level: 'A1', german: 'die möblierte Wohnung', english: 'furnished apartment', category: 'Home' },
    { id: 619, level: 'A1', german: 'die Kaltmiete', english: 'The basic rent', category: 'Home' },
    { id: 620, level: 'A1', german: 'die Warmmiete', english: 'the rent including utilities', category: 'Home' },
    { id: 621, level: 'A1', german: 'Die Nebenkosten', english: 'the additional costs', category: 'Home' },
    { id: 622, level: 'A1', german: 'die Haustiere', english: 'pets', category: 'Home' },
    { id: 623, level: 'A1', german: 'die Kaution', english: 'deposit', category: 'Home' },
    { id: 624, level: 'A1', german: 'die Wohnung zur miete', english: 'apartment for rent', category: 'Home' },
    { id: 625, level: 'A1', german: 'Nähe vom Zentrum', english: 'near the center', category: 'Home' },
    { id: 626, level: 'A1', german: 'die Wohnung ist im zweiten Stock.', english: 'the apartment is on the second floor.', category: 'Home' },
    { id: 627, level: 'A1', german: 'umziehen', english: 'to move', category: 'Verbs' },
    { id: 628, level: 'A1', german: 'ruhigen Stadtteil', english: 'quiet neighborhood', category: 'Home' },
    { id: 629, level: 'A1', german: 'der Koffer', english: 'suitcase', category: 'Vacation' },
    { id: 630, level: 'A1', german: 'verlassen', english: 'to leave', category: 'Verbs' },
    { id: 631, level: 'A1', german: 'jemanden', english: 'someone', category: 'People' },
    { id: 632, level: 'A1', german: 'Vielen Dank für Ihre Hilfe', english: 'Thank you for your help', category: 'Greetings' },
    { id: 633, level: 'A1', german: 'pünktlich', english: 'on time', category: 'Time' },
    { id: 634, level: 'A1', german: 'absagen', english: 'to cancel', category: 'Verbs' },
    { id: 635, level: 'A1', german: 'verschieben', english: 'to move / postpone', category: 'Verbs' },
    { id: 636, level: 'A1', german: 'ausgehen', english: 'to go', category: 'Verbs' },
    { id: 637, level: 'A1', german: 'zurückkehren', english: 'to return', category: 'Verbs' },
    { id: 638, level: 'A1', german: 'unbedingt', english: 'for sure, without a doubt', category: 'Adverbs' },
    { id: 639, level: 'A1', german: 'vielleicht', english: 'maybe', category: 'Adverbs' },
    { id: 640, level: 'A1', german: 'auf keinen fall', english: 'absolutely not', category: 'Adverbs' },
    { id: 641, level: 'A1', german: 'Pause', english: 'pause', category: 'Work' },
    { id: 642, level: 'A1', german: 'Geschenk', english: 'gift', category: 'Events' },
    { id: 643, level: 'A1', german: 'der Geburtstag', english: 'birthday', category: 'Events' },
    { id: 644, level: 'A1', german: 'die Firma', english: 'company, firm', category: 'Work' },
    { id: 645, level: 'A1', german: 'zukunft', english: 'future', category: 'Time' },
    { id: 646, level: 'A1', german: 'die Welt', english: 'world', category: 'Places' },
    { id: 647, level: 'A1', german: 'allein', english: 'alone', category: 'Adverbs' },
    { id: 648, level: 'A1', german: 'Reise', english: 'trip', category: 'Vacation' },
    { id: 649, level: 'A1', german: 'mehr', english: 'more', category: 'Adverbs' },
    { id: 650, level: 'A1', german: 'bauen', english: 'to build', category: 'Verbs' },
    { id: 651, level: 'A1', german: 'die Nachrichten', english: 'news', category: 'Society' },
    { id: 652, level: 'A1', german: 'dauern', english: 'to last, to take time', category: 'Verbs' },
    { id: 653, level: 'A1', german: 'Anfänger', english: 'beginner', category: 'Adjectives' },
    { id: 654, level: 'A1', german: 'Profi', english: 'professional', category: 'Adjectives' },
    { id: 655, level: 'A1', german: 'leise', english: 'quiet', category: 'Adjectives' },
    { id: 656, level: 'A1', german: 'Nehmen Sie Platz!', english: 'Please take a seat!', category: 'Greetings' },
    { id: 657, level: 'A1', german: 'der Zahn', english: 'tooth', category: 'Body' },
    { id: 658, level: 'A1', german: 'Kopfschmerzen', english: 'headache', category: 'Health' },
    { id: 659, level: 'A1', german: 'Zahnschmerzen', english: 'toothache', category: 'Health' },
    { id: 660, level: 'A1', german: 'Mein Rücken tut weh', english: 'my back hurts', category: 'Health' },
    { id: 661, level: 'A1', german: 'die Tablette', english: 'tablet', category: 'Health' },
    { id: 662, level: 'A1', german: 'der Schmerz', english: 'pain', category: 'Health' },
    { id: 663, level: 'A1', german: 'der Husten', english: 'cough', category: 'Health' },
    { id: 664, level: 'A1', german: 'die Kapsel', english: 'capsule', category: 'Health' },
    { id: 665, level: 'A1', german: 'der Sirup', english: 'syrup', category: 'Health' },
    { id: 666, level: 'A1', german: 'Wie oft soll ich die Tabletten nehmen?', english: 'How often should I take the tablets?', category: 'Health' },
    { id: 667, level: 'A1', german: 'Fieber', english: 'fever', category: 'Health' },
    { id: 668, level: 'A1', german: 'das Medikament', english: 'medicine', category: 'Health' },
    { id: 669, level: 'A1', german: 'die Menschen', english: 'people', category: 'People' },
    { id: 670, level: 'A1', german: 'ernst', english: 'serious', category: 'Adjectives' },
    { id: 671, level: 'A1', german: 'jeder', english: 'everyone', category: 'People' },
    { id: 672, level: 'A1', german: 'Angebot', english: 'offer', category: 'Work' },
    { id: 673, level: 'A1', german: 'abflug', english: 'departure', category: 'Transportation' },
    { id: 674, level: 'A1', german: 'ab sofort', english: 'from now on', category: 'Time' },
    { id: 675, level: 'A1', german: 'erzählen', english: 'to tell', category: 'Verbs' },
    { id: 676, level: 'A1', german: 'entscheiden', level: 'A1', english: 'to decide', level: 'A1', category: 'Verbs' },
    { id: 677, level: 'A1', german: 'verkaufen', english: 'to sell', category: 'Verbs' },
    { id: 678, level: 'A1', german: 'lachen', english: 'to laugh', category: 'Verbs' },
    { id: 679, level: 'A1', german: 'holen', english: 'pick up', category: 'Verbs' },
    { id: 680, level: 'A1', german: 'waschen', english: 'to wash', category: 'Verbs' },
    { id: 681, level: 'A1', german: 'mischen', english: 'to mix', category: 'Verbs' },
    { id: 682, level: 'A1', german: 'wissen', english: 'to know', category: 'Verbs' },
    { id: 683, level: 'A1', german: 'mussen', english: 'should', category: 'Verbs' },
    { id: 684, level: 'A1', german: 'mogen', english: 'like', category: 'Verbs' },
    { id: 685, level: 'A1', german: 'werden', english: 'become', category: 'Verbs' },
    { id: 686, level: 'A1', german: 'aussehen', english: 'look like', category: 'Separable Verbs' },
    { id: 687, level: 'A1', german: 'früher', english: 'earlier', category: 'Time' },
    { id: 688, level: 'A1', german: 'dick', english: 'fat', category: 'Adjectives' },
    { id: 689, level: 'A1', german: 'schlank', english: 'slim', category: 'Adjectives' },
    { id: 690, level: 'A1', german: 'schick', english: 'handsome or attractive', category: 'Adjectives' },
    { id: 691, level: 'A1', german: 'schlampig', english: 'untidy, sloopy', category: 'Adjectives' },
    { id: 692, level: 'A1', german: 'hübsch', english: 'pretty', category: 'Adjectives' },
    { id: 693, level: 'A1', german: 'Marjan sieht hübsch aus', english: 'Marjan looks pretty', category: 'Adjectives' },
    { id: 694, level: 'A1', german: 'glücklich', english: 'happy', category: 'Adjectives' },
    { id: 695, level: 'A1', german: 'unglücklich', english: 'sad, unhappy', category: 'Adjectives' },
    { id: 696, level: 'A1', german: 'unfreundlich', english: 'unfriendly', category: 'Adjectives' },
    { id: 697, level: 'A1', german: 'unwichtig', english: 'less important', category: 'Adjectives' },
    { id: 698, level: 'A1', german: 'wichtig', english: 'important', category: 'Adjectives' },
    { id: 699, level: 'A1', german: 'uninteressant', english: 'not interesting', category: 'Adjectives' },
    { id: 700, level: 'A1', german: 'Unglaublich', english: 'unbelievable', category: 'Adjectives' },
    { id: 701, level: 'A1', german: 'hilfsbereit', english: 'helpful', category: 'Adjectives' },
    { id: 702, level: 'A1', german: 'sympathisch', english: 'sympathetic, friendly', category: 'Adjectives' },
    { id: 703, level: 'A1', german: 'besonderes', english: 'special', category: 'Adjectives' },
    { id: 704, level: 'A1', german: 'die Pflanze', english: 'plan', category: 'Home' },
    { id: 705, level: 'A1', german: 'schon', english: 'already', category: 'Adverbs' },
    { id: 706, level: 'A1', german: 'aussteigen', english: 'to get out / off', category: 'Separable Verbs' },
    { id: 707, level: 'A1', german: 'umsteigen', english: 'change train / bus', category: 'Separable Verbs' },
    { id: 708, level: 'A1', german: 'nervig', english: 'nervous', category: 'Adjectives' },
    { id: 709, level: 'A1', german: 'heißen', english: 'to call', category: 'Verbs' },
    { id: 710, level: 'A1', german: 'fertig', english: 'ready', category: 'Adjectives' },
    { id: 711, level: 'A1', german: 'malen', english: 'to paint', category: 'Verbs' },
    { id: 712, level: 'A1', german: 'dürfen', english: 'can', category: 'Verbs' },
    { id: 713, level: 'A1', german: 'fehlen', english: 'miss', category: 'Verbs' },
    { id: 714, level: 'A1', german: 'laden', english: 'to invite', category: 'Verbs' },
    { id: 715, level: 'A1', german: 'aufräumen', english: 'to clean', category: 'Verbs' },
    { id: 716, level: 'A1', german: 'sagen', english: 'to say', category: 'Verbs' },
    { id: 717, level: 'A1', german: 'vergessen', english: 'to forget', category: 'Verbs' },
    { id: 718, level: 'A1', german: 'studieren', english: 'to study', category: 'Verbs' },
    { id: 719, level: 'A1', german: 'reparieren', english: 'to repair', category: 'Verbs' },
    { id: 720, level: 'A1', german: 'abholen', english: 'to pick up', category: 'Verbs' },
    { id: 721, level: 'A1', german: 'warten', english: 'to wait', category: 'Verbs' },
    { id: 722, level: 'A1', german: 'liegen', english: 'be located, lie', category: 'Verbs' },
    { id: 723, level: 'A1', german: 'einkaufen', english: 'to shop, perchase', category: 'Verbs' },
    { id: 724, level: 'A1', german: 'außerdem', english: 'also', category: 'Prepositions' },
    { id: 725, level: 'A1', german: 'normalerweise', english: 'usually', category: 'Adverbs' },
    { id: 726, level: 'A1', german: 'ferien', english: 'holidays', level: 'A1', category: 'Work' },
    { id: 727, level: 'A1', german: 'das Wörterbuch', english: 'dictionary', category: 'Tool' },
    { id: 728, level: 'A1', german: 'erlaubt', english: 'allowed', category: 'Public Places' },
    { id: 729, level: 'A1', german: 'verboten', english: 'prohibited, forbidden', level: 'A1', category: 'Public Places' },
    { id: 730, level: 'A1', german: 'dürfen', english: 'to allow', category: 'Public Places' },
    { id: 731, level: 'A1', german: 'spazieren', english: 'walk', category: 'Verbs' },
    { id: 732, level: 'A1', german: 'Natur', english: 'nature', category: 'Public Places' },
    { id: 733, level: 'A1', german: 'Grillen und Feuer machen ist verboten', english: 'grilling and fire making is prohibited', category: 'Public Places' },
    { id: 734, level: 'A1', german: 'halten', english: 'keep, hold', category: 'Verbs' },
    { id: 735, level: 'A1', german: 'vorsichtig', english: 'careful', category: 'Adjectives' },
    { id: 736, level: 'A1', german: 'am ältesten', english: 'the oldest', category: 'Adjectives' },
    { id: 737, level: 'A1', german: 'am modernsten', english: 'the most modern', category: 'Adjectives' },
    { id: 738, level: 'A1', german: 'am teuersten', english: 'the most expensive', category: 'Adjectives' },
    { id: 739, level: 'A1', german: 'am billigsten', english: 'the cheapest', category: 'Adjectives' },
    { id: 740, level: 'A1', german: 'Ben ist so schick wie Marjan', english: 'Ben is so handsome as Marjan', category: 'Adjectives' },
    { id: 741, level: 'A1', german: 'kleiner', english: 'smaller', category: 'Adjectives' },
    { id: 742, level: 'A1', german: 'schöner', english: 'prettier', category: 'Adjectives' },
    { id: 743, level: 'A1', german: 'teurer', english: 'more expensive', category: 'Adjectives' },
    { id: 744, level: 'A1', german: 'dunkler', english: 'darker', category: 'Adjectives' },
    { id: 745, level: 'A1', german: 'leckerer', english: 'more tasty', category: 'Adjectives' },
    { id: 746, level: 'A1', german: 'länger', english: 'longer', category: 'Adjectives' },
    { id: 747, level: 'A1', german: 'größer', english: 'bigger', category: 'Adjectives' },
    { id: 748, level: 'A1', german: 'schneller', english: 'faster', category: 'Adjectives' },
    { id: 749, level: 'A1', german: 'heller', english: 'brighter', category: 'Adjectives' },
    { id: 750, level: 'A1', german: 'Ich bin größer als er.', english: 'I am bigger than him.', category: 'Adjectives' },
    { id: 751, level: 'A1', german: 'Iran ist das schönste Land.', english: 'Iran is the most beautiful country.', category: 'Adjectives' },
    { id: 752, level: 'A1', german: 'am liebsten', english: 'the most lovely', category: 'Adjectives' },
    { id: 753, level: 'A1', german: 'Der Kaffee ist besser als Tee', english: 'coffee is better than tea', category: 'Adjectives' },
    { id: 754, level: 'A1', german: 'Er hatte mehr Zeit als ich.', english: 'He had more time than I.', category: 'Adjectives' },
    { id: 755, level: 'A1', german: 'näher', english: 'closer', category: 'Adjectives' },
    { id: 756, level: 'A1', german: 'denn', english: 'because', category: 'Conjunctions' },
    { id: 757, level: 'A1', german: 'und', english: 'and', category: 'Conjunctions' },
    { id: 758, level: 'A1', german: 'oder', english: 'or', category: 'Conjunctions' },
    { id: 759, level: 'A1', german: 'aber', english: 'but', category: 'Conjunctions' },
    { id: 760, level: 'A1', german: 'durst', english: 'thirst', category: 'Adjectives' },
    { id: 761, level: 'A1', german: 'hunger', english: 'hunger', category: 'Adjectives' },
    { id: 762, level: 'A1', german: 'wertlos', english: 'worthless', category: 'Adjectives' },
    { id: 763, level: 'A1', german: 'arbeitslos', english: 'unemployed', category: 'Adjectives' },
    { id: 764, level: 'A1', german: 'schlaflos', english: 'sleepless', category: 'Adjectives' },
    { id: 765, level: 'A1', german: 'ohne', english: 'without', category: 'Conjunctions' },
    { id: 766, level: 'A1', german: 'mit', english: 'with', category: 'Conjunctions' },
    { id: 767, level: 'A1', german: 'Wie ist das Wetter?', english: 'How is the weather?', category: 'Weather' },
    { id: 768, level: 'A1', german: 'Es ist bewölkt.', english: 'It is cloudy.', category: 'Weather' },
    { id: 769, level: 'A1', german: 'Es regnet', english: 'It is raining', category: 'Weather' },
    { id: 770, level: 'A1', german: 'schon', english: 'already', category: 'Conjunctions' },
    { id: 771, level: 'A1', german: 'dann', english: 'then', category: 'Conjunctions' },
    { id: 772, level: 'A1', german: 'anders', english: 'different', category: 'Adjectives' },
    { id: 773, level: 'A1', german: 'noch', english: 'still', category: 'Conjunctions' },
    { id: 774, level: 'A1', german: 'mitnehmen', english: 'take along', category: 'Separable Verbs' },
    { id: 775, level: 'A1', german: 'manche', english: 'some', category: 'Conjunctions' },
    { id: 776, level: 'A1', german: 'überall', english: 'everywhere', category: 'Conjunctions' },
    { id: 777, level: 'A1', german: 'das Ostern', english: 'Easter', category: 'Events' },
    { id: 778, level: 'A1', german: 'das Weihnachten', english: 'Christmas', category: 'Events' },
    { id: 779, level: 'A1', german: 'das Silvester', english: 'New Year', category: 'Events' },
    { id: 780, level: 'A1', german: 'das Oktoberfest', english: 'beer festival', category: 'Events' },
    { id: 781, level: 'A1', german: 'das Feuerwerk', english: 'fireworks', category: 'Events' },
    { id: 782, level: 'A1', german: 'feiern', english: 'celebrate', category: 'Verbs' },
    { id: 783, level: 'A1', german: 'freuen', english: 'be happy', category: 'Verbs' },
    { id: 784, level: 'A1', german: 'einladung', english: 'invitation', category: 'Events' },
    { id: 785, level: 'A1', german: 'Anfong Mai', english: 'beginning of May', category: 'Time' },
    { id: 786, level: 'A1', german: 'lage', english: 'location', category: 'Home' },
    { id: 787, level: 'A1', german: 'die Wanderung', english: 'hike', category: 'Hobbies' },
    { id: 788, level: 'A1', german: 'empfehlen', english: 'recommend', category: 'Verbs' },
    { id: 789, level: 'A1', german: 'Erwachsene', english: 'adult', category: 'People' },
    { id: 790, level: 'A1', german: 'weil', english: 'because', category: 'Conjunctions' },
    { id: 791, level: 'A1', german: 'übermorgen', english: 'the day after tomorrow', category: 'Time' },
    { id: 792, level: 'A1', german: 'sollten', english: 'should', category: 'Verbs' },
    { id: 793, level: 'A1', german: 'shoppen', english: 'shop', category: 'Verbs' },
    { id: 794, level: 'A1', german: 'buchen', english: 'reserve, book', category: 'Verbs' },
    { id: 795, level: 'A1', german: 'das ganze Wochenende', english: 'the whole weekend', category: 'Time' },
    { id: 796, level: 'A1', german: 'zeigen', english: 'to show', category: 'Verbs' },
    { id: 797, level: 'A1', german: 'herzlichen Glückwunsch zu..', english: 'Congratulations on ..', category: 'Greetings' },
    { id: 798, level: 'A1', german: 'ausleihen', english: 'to borrow', category: 'Verbs' },
    { id: 799, level: 'A1', german: 'teilnehmen', english: 'Participate, attend', category: 'Verbs' },
    { id: 800, level: 'A1', german: 'im voraus', english: 'in advance', category: 'Conjunctions' },
    { id: 801, level: 'A1', german: 'das Gehalt', english: 'salary', category: 'Work' },
    { id: 802, level: 'A1', german: 'der Grund', english: 'the reason', category: 'General' },
    { id: 803, level: 'A1', german: 'diesen', english: 'this', category: 'Conjunctions' },
    { id: 804, level: 'A1', german: 'zumachen', english: 'to close', category: 'Verbs' },
    { id: 805, level: 'A1', german: 'anmachen', english: 'to turn on (light/tech)', category: 'Verbs' },
    { id: 806, level: 'A1', german: 'ausmachen', english: 'to turn off', category: 'Verbs' },
    // ------------------------------------------------------------------------------------------------------------------
    // ------------------------------------------------------------------------------------------------------------------
    { id: 807, level: 'A2', german: 'die Angst', english: 'fear', category: 'Feeling' },
    { id: 808, level: 'A2', german: 'das Olivenöl', english: 'Olive oil', category: 'Food & Drink' },
    { id: 809, level: 'A2', german: 'der Anfang', english: 'start', category: 'General' },
    { id: 810, level: 'A2', german: 'die Reihenfolge', english: 'order, series', category: 'General' },
    { id: 811, level: 'A2', german: 'das Ereignis', english: 'the event', category: 'Events' },
    { id: 812, level: 'A2', german: 'das Rätsel', english: 'riddle, puzzle', category: 'Hobbies' },
    { id: 813, level: 'A2', german: 'der Flohmarkt', english: 'the flea market', category: 'Supermarket' },
    { id: 814, level: 'A2', german: 'das Skateboard', english: 'skateboard', category: 'Hobbies' },
    { id: 815, level: 'A2', german: 'der Comic', english: 'comic story, fun story', category: 'Hobbies' },
    { id: 816, level: 'A2', german: 'die Puppe', english: 'the doll', category: 'Hobbies' },
    { id: 817, level: 'A2', german: 'die Süßigkeit', english: 'sweet, candy', category: 'Food & Drink' },
    { id: 818, level: 'A2', german: 'der Witz', english: 'jock', category: 'Hobbies' },
    { id: 819, level: 'A2', german: 'der Neffe', english: 'the nephew', category: 'Family' },
    { id: 820, level: 'A2', german: 'die Nichte', english: 'niece', category: 'Family' },
    { id: 821, level: 'A2', german: 'der Cousin', english: 'cousin (M)', category: 'Family' },
    { id: 822, level: 'A2', german: 'die Cousine', english: 'cousin (F)', category: 'Family' },
    { id: 823, level: 'A2', german: 'der Schwiegervater', english: 'father-in-law', category: 'Family' },
    { id: 824, level: 'A2', german: 'die Schwiegermutter', english: 'mother-in-law', category: 'Family' },
    { id: 825, level: 'A2', german: 'der Schwiegersohn', english: 'son-in-law', category: 'Family' },
    { id: 826, level: 'A2', german: 'die Schwiegertochter', english: 'daughter-in-law', category: 'Family' },
    { id: 827, level: 'A2', german: 'die Kindheitserinnerungen', english: 'childhood memories ', category: 'General' },
    { id: 828, level: 'A2', german: 'das Studium', english: 'academic study', category: 'Education' },
    { id: 829, level: 'A2', german: 'der Schluss', english: 'the end', category: 'General' },
    { id: 830, level: 'A2', german: 'der Abstimmung', english: 'vote', category: 'Society' },
    { id: 831, level: 'A2', german: 'die Kommode', english: 'drawers', category: 'Home' },
    { id: 832, level: 'A2', german: 'der Umzug', english: 'the move', category: 'Transportation' },
    { id: 833, level: 'A2', german: 'die Einrichtung', english: 'the facility', category: 'General' },
    { id: 834, level: 'A2', german: 'das Regal', english: 'shelf', category: 'Home' },
    { id: 835, level: 'A2', german: 'das Deckenlicht', english: 'the ceiling light', category: 'Home' },
    { id: 836, level: 'A2', german: 'die Landschaft', english: 'the landscape, view', category: 'Vacation' },
    { id: 837, level: 'A2', german: 'das Souvenir', english: 'the souvenir', category: 'Vacation' },
    { id: 838, level: 'A2', german: 'das Möbelstück', english: 'the piece of furniture', category: 'Home' },
    { id: 839, level: 'A2', german: 'die Ruhe', english: 'peace', category: 'General' },
    { id: 840, level: 'A2', german: 'die Erholung', english: 'resting', category: 'General' },
    { id: 841, level: 'A2', german: 'die Vorliebe', english: 'preference, favorite', category: 'General' },
    { id: 842, level: 'A2', german: 'die Entspannung', english: 'relaxation', category: 'General' },
    { id: 843, level: 'A2', german: 'der Bauernhof', english: 'farm', category: 'Places' },
    { id: 844, level: 'A2', german: 'die Luft', english: 'air', category: 'General' },
    { id: 845, level: 'A2', german: 'die Erfahrung', english: 'experience', category: 'Work' },
    { id: 846, level: 'A2', german: 'die Motivation', english: 'motivation', category: 'General' },
    { id: 847, level: 'A2', german: 'der Anfänger', english: 'beginner', category: 'General' },
    { id: 848, level: 'A2', german: 'der Fortgeschrittener', english: 'the advanced ', category: 'General' },
    { id: 849, level: 'A2', german: 'die Tour', english: 'tour', category: 'Vacation' },
    { id: 850, level: 'A2', german: 'die Natur', english: 'nature', category: 'Public Places' },
    { id: 851, level: 'A2', german: 'der Strand', english: 'beach', category: 'Public Places' },
    { id: 852, level: 'A2', german: 'das Ufer', english: 'shore', category: 'Public Places' },
    { id: 853, level: 'A2', german: 'der Hügel', english: 'hill', category: 'Public Places' },
    { id: 854, level: 'A2', german: 'das Dorf', english: 'village', category: 'Places' },
    { id: 855, level: 'A2', german: 'der Frosch', english: 'frog', category: 'Animals' },
    { id: 856, level: 'A2', german: 'der Stadtbummel', english: 'city stroll', category: 'Vacation' },
    { id: 857, level: 'A2', german: 'das Angebot', english: 'offer', category: 'Supermarket' },
    { id: 858, level: 'A2', german: 'die Tafel', english: 'board', category: 'Home' },
    { id: 859, level: 'A2', german: 'der Reiseveranstalter', english: 'tour operatore', category: 'Vacation' },
    { id: 860, level: 'A2', german: 'die Verpackung', english: 'packaging', category: 'General' },
    { id: 861, level: 'A2', german: 'der Einkaufszettel', english: 'shopping list', category: 'Supermarket' },
    { id: 862, level: 'A2', german: 'der Mitbewohner', english: 'roommate', category: 'Home' },
    { id: 863, level: 'A2', german: 'der Thunfisch', english: 'tuna', category: 'Food & Drink' },
    { id: 864, level: 'A2', german: 'die Salami', english: 'salami', category: 'Food & Drink' },
    { id: 865, level: 'A2', german: 'der Pfirsich', english: 'peach', category: 'Fruits' },
    { id: 866, level: 'A2', german: 'der Eistee', english: 'iced tee', category: 'Food & Drink' },
    { id: 867, level: 'A2', german: 'die Paprika', english: 'bell pepper', category: 'Food & Drink' },
    { id: 868, level: 'A2', german: 'der Knoblauch', english: 'garlic', category: 'Food & Drink' },
    { id: 869, level: 'A2', german: 'die Birne', english: 'pear', category: 'Fruits' },
    { id: 870, level: 'A2', german: 'die Bohne', english: 'bean', category: 'Food & Drink' },
    { id: 871, level: 'A2', german: 'das Mehl', english: 'flour', category: 'Food & Drink' },
    { id: 872, level: 'A2', german: 'die Marmelade', english: 'jam', category: 'Food & Drink' },
    { id: 873, level: 'A2', german: 'der Quark', english: 'quark (maste chekide)', category: 'Food & Drink' },
    { id: 874, level: 'A2', german: 'die Cola', english: 'cola', category: 'Food & Drink' },
    { id: 875, level: 'A2', german: 'das Bonbon', english: 'candy', category: 'Food & Drink' },
    { id: 876, level: 'A2', german: 'die Tüte', english: 'bag', category: 'Supermarket' },
    { id: 877, level: 'A2', german: 'die Dose', english: 'can', category: 'Food & Drink' },
    { id: 878, level: 'A2', german: 'die Packung', english: 'package', category: 'General' },
    { id: 879, level: 'A2', german: 'die Magermilch', english: 'fatless milk (skim milk)', category: 'Food & Drink' },
    { id: 880, level: 'A2', german: 'die Fettarmmilch', english: 'low-fat milk', category: 'Food & Drink' },
    { id: 881, level: 'A2', german: 'die Vollmilch', english: 'high-fat milk', category: 'Food & Drink' },
    { id: 882, level: 'A2', german: 'die Vermutung', english: 'assumption', category: 'General' },
    { id: 883, level: 'A2', german: 'die Portion', english: 'portion, part', category: 'General' },
    { id: 884, level: 'A2', german: 'das Rührei', english: 'scrambled eggs', category: 'Food & Drink' },
    { id: 885, level: 'A2', german: 'der Tourismus', english: 'tourism', category: 'Vacation' },
    { id: 886, level: 'A2', german: 'die Besichtigung', english: 'sightseeing', category: 'Vacation' },
    { id: 887, level: 'A2', german: 'die Führung', english: 'the guided tour', category: 'Vacation' },
    { id: 888, level: 'A2', german: 'der Reiseführer', english: 'tour guide', category: 'Vacation' },
    { id: 889, level: 'A2', german: 'die Sehenswürdigkeit', english: 'landmark', category: 'Vacation' },
    { id: 890, level: 'A2', german: 'der Rundgang', english: 'tour', category: 'Vacation' },
    { id: 891, level: 'A2', german: 'der Prospekt', english: 'brochure', category: 'Vacation' },
    { id: 892, level: 'A2', german: 'die Unterkunft', english: 'accommodation', category: 'Vacation' },
    { id: 893, level: 'A2', german: 'das Trinkgeld', english: 'tip', category: 'Vacation' },
    { id: 894, level: 'A2', german: 'das Geld wechseln', english: ' exchanging money', category: 'Vacation' },
    { id: 895, level: 'A2', german: 'die Schifffahrt', english: 'the boat trip', category: 'Vacation' },
    { id: 896, level: 'A2', german: 'das Einverständnis', english: 'agreement', category: 'General' },
    { id: 897, level: 'A2', german: 'die Ferien', english: 'holiday', category: 'Vacation' },
    { id: 898, level: 'A2', german: 'der Begriff', english: 'term', category: 'General' },
    { id: 899, level: 'A2', german: 'das Mittelalter', english: 'middle ages', category: 'People' },
    { id: 900, level: 'A2', german: 'der Eintritt', english: 'the entrance fee', category: 'Vacation' },
    { id: 901, level: 'A2', german: 'die Ermäßigung', english: 'discount', category: 'Supermarket' },
    { id: 902, level: 'A2', german: 'der Künstler', english: 'artist', category: 'Events' },
    { id: 903, level: 'A2', german: 'die Bühne', english: 'stage, scene', category: 'Events' },
    { id: 904, level: 'A2', german: 'der Vortrag', english: 'lecture, speech', category: 'Events' },
    { id: 905, level: 'A2', german: 'die Diskussionsrunde', english: 'discussion meeting', category: 'Events' },
    { id: 906, level: 'A2', german: 'das Fest', english: 'festival', category: 'Events' },
    { id: 907, level: 'A2', german: 'das Kostüm', english: 'costume', category: 'Events' },
    { id: 908, level: 'A2', german: 'das Theaterstück', english: 'drama, play, scenario of the film or theatre', category: 'Events' },
    { id: 909, level: 'A2', german: 'das Festival', english: 'festival', category: 'Events' },
    { id: 910, level: 'A2', german: 'der König', english: 'king', category: 'People' },
    { id: 911, level: 'A2', german: 'der Zeitraum', english: 'period, part of the time', category: 'Time' },
    { id: 912, level: 'A2', german: 'die Verbindung', english: 'connection, relation', category: 'People' },
    { id: 913, level: 'A2', german: 'die Zukunft', english: 'future', category: 'Time' },
    { id: 914, level: 'A2', german: 'die Fitness', english: 'fitness', category: 'Sport' },
    { id: 915, level: 'A2', german: 'die Ernährung', english: 'nutrition', category: 'Sport' },
    { id: 916, level: 'A2', german: 'der Basketball', english: 'Basketball', category: 'Sport' },
    { id: 917, level: 'A2', german: 'der Handball', english: 'Handball', category: 'Sport' },
    { id: 918, level: 'A2', german: 'das Gewichtheben', english: 'weightlifting', category: 'Sport' },
    { id: 919, level: 'A2', german: 'das Judo', english: 'judo', category: 'Sport' },
    { id: 920, level: 'A2', german: 'der Yoga', english: 'yoga', category: 'Sport' },
    { id: 921, level: 'A2', german: 'der Golf', english: 'golf', category: 'Sport' },
    { id: 922, level: 'A2', german: 'die Gymnastik', english: 'gymnastics', category: 'Sport' },
    { id: 923, level: 'A2', german: 'das Tischtennis', english: 'ping pong', category: 'Sport' },
    { id: 924, level: 'A2', german: 'das Eishockey', english: 'ice hockey', category: 'Sport' },
    { id: 925, level: 'A2', german: 'die Sportart', english: 'sport', category: 'Sport' },
    { id: 926, level: 'A2', german: 'der Wettkampf', english: 'competition', category: 'Sport' },
    { id: 927, level: 'A2', german: 'die Briefmarke', english: 'stamp', category: 'Work' },
    { id: 928, level: 'A2', german: 'draußen übernachten', english: 'Sleeping outdoors', category: 'Hobbies' },
    { id: 929, level: 'A2', german: 'Witze erzählen', english: 'telling jokes', category: 'Hobbies' },
    { id: 930, level: 'A2', german: 'die Puppe', english: 'doll', category: 'Hobbies' },
    { id: 931, level: 'A2', german: 'der Flohmarkt', english: 'flea market', category: 'Supermarket' },
    { id: 932, level: 'A2', german: 'strenge', english: 'strict', category: 'General' },
    { id: 933, level: 'A2', german: 'verdanken', english: 'to owe', category: 'General' },
    { id: 934, level: 'A2', german: 'zuerst', english: 'at first', category: 'General' },
    { id: 935, level: 'A2', german: 'dann', english: 'then', category: 'General' },
    { id: 936, level: 'A2', german: 'danach', english: 'after that', category: 'General' },
    { id: 937, level: 'A2', german: 'yum Schluss', english: 'in conclusion', category: 'General' },
    { id: 938, level: 'A2', german: 'die Gemeinsamkeit', english: 'similarity', category: 'General' },
    { id: 939, level: 'A2', german: 'der Unterschied', english: 'difference', category: 'General' },
    { id: 940, level: 'A2', german: 'der Magen', english: 'stomach', category: 'Health' },
    { id: 941, level: 'A2', german: 'der Notfall', english: 'emergency', category: 'General' },
    { id: 942, level: 'A2', german: 'der Herzinfarkt', english: 'the heart attack', category: 'Health' },
    { id: 943, level: 'A2', german: 'die Krankheit', english: 'illness', category: 'Health' },
    { id: 944, level: 'A2', german: 'der Unfall', english: 'accident', category: 'Health' },
    { id: 945, level: 'A2', german: 'die Hoffnung', english: 'hope', category: 'General' },
    { id: 946, level: 'A2', german: 'der Krankendwagen', english: 'ambulance', category: 'Health' },
    { id: 947, level: 'A2', german: 'die Verletzung', english: 'injury', category: 'Health' },
    { id: 948, level: 'A2', german: 'das Blut', english: 'blood', category: 'Health' },
    { id: 949, level: 'A2', german: 'der Notarzt', english: 'emergency doctor', category: 'Health' },
    { id: 950, level: 'A2', german: 'das Krankenhause', english: 'hospital', category: 'Health' },
    { id: 951, level: 'A2', german: 'die Notaufnahme', english: 'the emergency room', category: 'Health' },
    { id: 952, level: 'A2', german: 'die Operation', english: 'surgery', category: 'Health' },
    { id: 953, level: 'A2', german: 'der Verband', english: 'bandage', category: 'Health' },
    { id: 954, level: 'A2', german: 'die Sorge', english: 'worry', category: 'Health' },
    { id: 955, level: 'A2', german: 'der Hausarzt', english: 'the family doctor', category: 'Health' },
    { id: 956, level: 'A2', german: 'die Wahrheit', english: 'truth', category: 'General' },
    { id: 957, level: 'A2', german: 'das Mitleid', english: 'pity, sympathy', category: 'General' },
    { id: 958, level: 'A2', german: 'die Wichtigkeit', english: 'importance', category: 'General' },
    { id: 959, level: 'A2', german: 'der Bericht', english: 'report', category: 'General' },
    { id: 960, level: 'A2', german: 'der/die Angestellte', english: 'office worker', category: 'Jobs' },
    { id: 961, level: 'A2', german: 'die Halle', english: 'hall', category: 'Places' },


    // { id: 962, level: 'A2', german: '', english: '', category: '' },
    // { id: 963, level: 'A2', german: '', english: '', category: '' },
    // { id: 964, level: 'A2', german: '', english: '', category: '' },
    // { id: 965, level: 'A2', german: '', english: '', category: '' },
    // { id: 966, level: 'A2', german: '', english: '', category: '' },
    // { id: 967, level: 'A2', german: '', english: '', category: '' },
    // { id: 968, level: 'A2', german: '', english: '', category: '' },
    // { id: 969, level: 'A2', german: '', english: '', category: '' },
    // { id: 970, level: 'A2', german: '', english: '', category: '' },
    // { id: 971, level: 'A2', german: '', english: '', category: '' },
    // { id: 972, level: 'A2', german: '', english: '', category: '' },
    // { id: 973, level: 'A2', german: '', english: '', category: '' },
    // { id: 974, level: 'A2', german: '', english: '', category: '' },
    // { id: 975, level: 'A2', german: '', english: '', category: '' },
    // { id: 976, level: 'A2', german: '', english: '', category: '' },
    // { id: 977, level: 'A2', german: '', english: '', category: '' },
    // { id: 978, level: 'A2', german: '', english: '', category: '' },
    // { id: 979, level: 'A2', german: '', english: '', category: '' },
    // { id: 980, level: 'A2', german: '', english: '', category: '' },
    // { id: 981, level: 'A2', german: '', english: '', category: '' },
    // { id: 982, level: 'A2', german: '', english: '', category: '' },
    // { id: 983, level: 'A2', german: '', english: '', category: '' },
    // { id: 984, level: 'A2', german: '', english: '', category: '' },
    // { id: 985, level: 'A2', german: '', english: '', category: '' },
    // { id: 986, level: 'A2', german: '', english: '', category: '' },
]

export default VOCABULARY
