const VOCABULARY = [
    // Greetings
    { german: 'Hallo', english: 'hello', category: 'Greetings' },
    { german: 'Guten Morgen', english: 'good morning', category: 'Greetings' },
    { german: 'Guten Tag', english: 'good day', category: 'Greetings' },
    { german: 'Guten Abend', english: 'good evening', category: 'Greetings' },
    { german: 'Gute Nacht', english: 'good night', category: 'Greetings' },
    { german: 'willkommen', english: 'welcome', category: 'Greetings' },
    { german: 'Wie geht\'s?', english: 'how are you?', category: 'Greetings' },
    { german: 'Danke', english: 'thank you', category: 'Greetings' },
    { german: 'gern geschehen', english: 'You\'re welcome', category: 'Greetings' },
    { german: 'Bitte', english: 'please / you\'re welcome', category: 'Greetings' },
    { german: 'leider', english: 'unfortunately', category: 'Greetings' },
    { german: 'Auf wiedersehen', english: 'goodbye', category: 'Greetings' },
    // { german: 'Auf widerhoren', english: 'goodbye', category: 'Greetings' },
    { german: 'nicht schlecht', english: 'not bad', category: 'Greetings' },
    { german: 'so lala', english: 'so so', category: 'Greetings' },
    { german: 'freut mich', english: 'nice to meet you', category: 'Greetings' },
    { german: 'Was machen sie beruflich?', english: 'What do you do professionally?', category: 'Greetings' },
    { german: 'Ich arbeite als IT-Ingenieur', english: 'I work as an IT engineer', category: 'Greetings' },
    { german: 'noch einmal', english: 'one more time', category: 'Greetings' },

    // Work
    { german: 'der Kollege', english: 'colleague', category: 'Work' },
    { german: 'der Mitarbeiter', english: 'employee', category: 'Work' },
    { german: 'der Arbeiter', english: 'worker', category: 'Work' },
    { german: 'der Chef', english: 'boss', category: 'Work' },


    // Personal Information
    { german: 'Ich heiße...', english: 'my name is...', category: 'Personal Info' },
    { german: 'Woher kommst du?', english: 'where are you from?', category: 'Personal Info' },
    { german: 'Ich komme aus...', english: 'I come from...', category: 'Personal Info' },
    { german: 'Ich bin ... Jahre alt', english: 'I am ... years old', category: 'Personal Info' },
    { german: 'Ich wohne in...', english: 'I live in...', category: 'Personal Info' },
    { german: 'Wie heißt du?', english: 'What is your name?', category: 'Personal Info' },
    { german: 'Wer bist du?', english: 'Who are you?', category: 'Personal Info' },
    { german: 'Wie geht es dir?', english: 'How are you?', category: 'Personal Info' },
    { german: 'Freut mich', english: 'Pleased to meet you', category: 'Personal Info' },
    { german: 'ledig', english: 'single', category: 'Personal Info' },
    { german: 'verheiratet', english: 'married', category: 'Personal Info' },
    { german: 'Ich bin Student(in)', english: 'I am a student', category: 'Personal Info' },
    { german: 'Beruf', english: 'profession / job', category: 'Personal Info' },
    { german: 'Hobbys', english: 'hobbies', category: 'Personal Info' },
    { german: 'die Telefonnummer', english: 'phone number', category: 'Personal Info' },
    { german: 'die Adresse', english: 'address', category: 'Personal Info' },
    { german: 'die Staatsangehörigkeit', english: 'nationality', category: 'Personal Info' },
    { german: 'Sprechen Sie Deutsch?', english: 'Do you speak German? (formal)', category: 'Personal Info' },
    { german: 'Ich spreche ein bisschen...', english: 'I speak a little...', category: 'Personal Info' },
    { german: 'meine Muttersprache', english: 'my native language', category: 'Personal Info' },
    { german: 'der Geburstag', english: 'birthday', category: 'Personal Info' },

    // Jobs
    { german: 'der Arzt', english: 'doctor', category: 'Jobs' },
    { german: 'der Lehrer', english: 'teacher', category: 'Jobs' },
    { german: 'der Kellner', english: 'waiter', category: 'Jobs' },
    { german: 'der Polizist', english: 'police officer', category: 'Jobs' },
    { german: 'der Mechaniker', english: 'mechanic', category: 'Jobs' },
    { german: 'der Engenieur', english: 'Engineer', category: 'Jobs' },
    { german: 'der Student', english: 'student', category: 'Jobs' },
    { german: 'der Koch', english: 'cook', category: 'Jobs' },

    // Family
    { german: 'die Mutter', english: 'mother', category: 'Family' },
    { german: 'der Vater', english: 'father', category: 'Family' },
    { german: 'die Eltern', english: 'parents', category: 'Family' },
    { german: 'der Bruder', english: 'brother', category: 'Family' },
    { german: 'die Schwester', english: 'sister', category: 'Family' },
    { german: 'das Geschwister', english: 'siblings', category: 'Family' },
    { german: 'die Frau', english: 'woman / wife', category: 'Family' },
    { german: 'der Mann', english: 'man / husband', category: 'Family' },
    { german: 'das Kind', english: 'child', category: 'Family' },
    { german: 'die Kinder', english: 'children', category: 'Family' },
    { german: 'die Familie', english: 'family', category: 'Family' },
    { german: 'der Freund / die Freundin', english: 'friend / boyfriend / girlfriend', category: 'Family' },

    // Food & Drink
    { german: 'das Essen', english: 'food', category: 'Food & Drink' },
    { german: 'das Getränk', english: 'drink', category: 'Food & Drink' },
    { german: 'das Brot', english: 'bread', category: 'Food & Drink' },
    { german: 'das Brötchen', english: 'bread roll', category: 'Food & Drink' },
    { german: 'der Apfel', english: 'apple', category: 'Food & Drink' },
    { german: 'die Banane', english: 'banana', category: 'Food & Drink' },
    { german: 'das Wasser', english: 'water', category: 'Food & Drink' },
    { german: 'der Kaffee', english: 'coffee', category: 'Food & Drink' },
    { german: 'der Tee', english: 'tea', category: 'Food & Drink' },
    { german: 'das Bier', english: 'beer', category: 'Food & Drink' },
    { german: 'der Wein', english: 'wine', category: 'Food & Drink' },
    { german: 'die Milch', english: 'milk', category: 'Food & Drink' },
    { german: 'der Saft', english: 'juice', category: 'Food & Drink' },
    { german: 'das Frühstück', english: 'breakfast', category: 'Food & Drink' },
    { german: 'das Mittagessen', english: 'lunch', category: 'Food & Drink' },
    { german: 'das Abendessen', english: 'dinner', category: 'Food & Drink' },
    { german: 'die Suppe', english: 'soup', category: 'Food & Drink' },
    { german: 'der Salat', english: 'salad', category: 'Food & Drink' },
    { german: 'der Zucker', english: 'sugar', category: 'Food & Drink' },
    { german: 'das Salz', english: 'salt', category: 'Food & Drink' },
    { german: 'das Hähnchen', english: 'chicken', category: 'Food & Drink' },
    { german: 'der Fisch', english: 'fish', category: 'Food & Drink' },
    { german: 'das Ei', english: 'egg', category: 'Food & Drink' },
    { german: 'der Kuchen', english: 'cake', category: 'Food & Drink' },
    { german: 'der honig', english: 'honey', category: 'Food & Drink' },
    { german: 'die Marmelade', english: 'jam', category: 'Food & Drink' },
    { german: 'lecker', english: 'delicious', category: 'Food & Drink' },
    { german: 'der Käse', english: 'cheese', category: 'Food & Drink' },

    // Measurement
    { german: 'Große', english: 'big', category: 'Measurement' },
    { german: 'kleine', english: 'small', category: 'Measurement' },
    { german: 'kurz', english: 'short', category: 'Measurement' },
    { german: 'lang', english: 'long', category: 'Measurement' },


    // fruits
    { german: 'das Obst', english: 'fruit', category: 'Fruits' },
    { german: 'der Apfel', english: 'apple', category: 'Fruits' },
    { german: 'die Banane', english: 'banana', category: 'Fruits' },
    { german: 'die Erdbeere', english: 'strawberry', category: 'Fruits' },
    { german: 'die Orangen', english: 'orange', category: 'Fruits' },

    //Supermarket / shopping
    { german: 'der Kasse', english: 'cashier', category: 'Supermarket' },
    { german: 'bar', english: 'cash', category: 'Supermarket' },
    { german: 'mit Karte', english: 'with card', category: 'Supermarket' },
    { german: 'der Kassenbon', english: 'receipt', category: 'Supermarket' },
    { german: 'zahlen', english: 'to pay', category: 'Supermarket' },

    // Colors
    { german: 'die Farbe', english: 'color', category: 'Colors' },
    { german: 'Blau', english: 'blue', category: 'Colors' },
    { german: 'Rot', english: 'red', category: 'Colors' },
    { german: 'Gelb', english: 'yellow', category: 'Colors' },
    { german: 'Grün', english: 'green', category: 'Colors' },
    { german: 'Weiß', english: 'white', category: 'Colors' },
    { german: 'Schwarz', english: 'black', category: 'Colors' },
    { german: 'Gelb', english: 'yellow', category: 'Colors' },


    // Time
    { german: 'heute', english: 'today', category: 'Time' },
    { german: 'morgen', english: 'tomorrow', category: 'Time' },
    { german: 'gestern', english: 'yesterday', category: 'Time' },
    { german: 'jetzt', english: 'now', category: 'Time' },
    { german: 'bald', english: 'soon', category: 'Time' },
    { german: 'Uhr', english: 'o\'clock', category: 'Time' },
    { german: 'Stunde', english: 'hour', category: 'Time' },
    { german: 'Minute', english: 'minute', category: 'Time' },
    { german: 'Zeit', english: 'time', category: 'Time' },
    { german: 'immer', english: 'always', category: 'Time' },
    { german: 'oft', english: 'often', category: 'Time' },
    { german: 'manchmal', english: 'sometimes', category: 'Time' },
    { german: 'selten', english: 'rarely', category: 'Time' },
    { german: 'nie', english: 'never', category: 'Time' },
    { german: 'Viertel vor fünf', english: 'quarter to five', category: 'Time' },
    { german: 'Viertel nach fünf', english: 'quarter past five', category: 'Time' },
    { german: 'es ist halb acht', english: 'half past seven', category: 'Time' },
    { german: 'der Tag', english: 'day', category: 'Time' },
    { german: 'die Woche', english: 'week', category: 'Time' },
    { german: 'der Monat', english: 'month', category: 'Time' },
    { german: 'das Jahr', english: 'year', category: 'Time' },
    { german: 'das wochenende', english: 'weekend', category: 'Time' },
    { german: 'später', english: 'later', category: 'Time' },
    { german: 'in der nacht', english: 'at night', category: 'Time' },
    { german: 'am Deinstagnachmittag', english: 'on Wednesday afternoon', category: 'Time' },
    { german: 'am Mittwochabend', english: 'on Wednesday evening', category: 'Time' },
    { german: 'am Montag', english: 'on Monday', category: 'Time' },
    { german: 'heute Abend', english: 'tonight', category: 'Time' },
    { german: 'heute Morgen', english: 'this morning', category: 'Time' },
    { german: 'um 12:00 Uhr', english: 'at 12:00 o\'clock', category: 'Time' },
    { german: 'von 12:00 bis 13:15 Uhr', english: 'from 12:00 to 13:15', category: 'Time' },
    { german: 'nach dem Abendessen', english: 'after dinner', category: 'Time' },
    { german: 'nächste Woche', english: 'next week', category: 'Time' },
    { german: 'am kommenden sonntag', english: 'next Sunday', category: 'Time' },
    { german: 'Wie spät ist es?', english: 'What time is it?', category: 'Time' },
    { german: 'am letzten wochenende', english: 'last weekend', category: 'Time' },
    { german: 'Es ist zwei Uhr', english: 'It is two o\'clock', category: 'Time' },
    { german: 'Es ist zwei Uhr fuüfzhen', english: 'It is 02:15', category: 'Time' },
    { german: 'Wann gehst du denn zur Arbeit?', english: 'When do you go to work?', category: 'Time' },
    { german: 'Um wie viel Uhr?', english: 'At what time?', category: 'Time' },
    { german: 'Hast du um Samstag zeit?', english: 'Are you free on Saturday?', category: 'Time' },
    { german: 'Ja, ich bin frei', english: 'Yes, I am free', category: 'Time' },
    { german: 'Perfekt, bis dann!', english: 'Perfect, see you then!', category: 'Time' },

    // Days
    { german: 'Montag', english: 'Monday', category: 'Days' },
    { german: 'Dienstag', english: 'Tuesday', category: 'Days' },
    { german: 'Mittwoch', english: 'Wednesday', category: 'Days' },
    { german: 'Donnerstag', english: 'Thursday', category: 'Days' },
    { german: 'Freitag', english: 'Friday', category: 'Days' },
    { german: 'Samstag', english: 'Saturday', category: 'Days' },
    { german: 'Sonntag', english: 'Sunday', category: 'Days' },

    // Months
    { german: 'Januar', english: 'January', category: 'Months' },
    { german: 'Februar', english: 'February', category: 'Months' },
    { german: 'März', english: 'March', category: 'Months' },
    { german: 'April', english: 'April', category: 'Months' },
    { german: 'Mai', english: 'May', category: 'Months' },
    { german: 'Juni', english: 'June', category: 'Months' },
    { german: 'Juli', english: 'July', category: 'Months' },
    { german: 'August', english: 'August', category: 'Months' },
    { german: 'September', english: 'September', category: 'Months' },
    { german: 'Oktober', english: 'October', category: 'Months' },
    { german: 'November', english: 'November', category: 'Months' },
    { german: 'Dezember', english: 'December', category: 'Months' },

    // Numbers
    { german: 'eins', english: 'one', category: 'Numbers' },
    { german: 'zwei', english: 'two', category: 'Numbers' },
    { german: 'drei', english: 'three', category: 'Numbers' },
    { german: 'vier', english: 'four', category: 'Numbers' },
    { german: 'fünf', english: 'five', category: 'Numbers' },
    { german: 'sechs', english: 'six', category: 'Numbers' },
    { german: 'sieben', english: 'seven', category: 'Numbers' },
    { german: 'acht', english: 'eight', category: 'Numbers' },
    { german: 'neun', english: 'nine', category: 'Numbers' },
    { german: 'zehn', english: 'ten', category: 'Numbers' },
    { german: 'elf', english: 'eleven', category: 'Numbers' },
    { german: 'zwölf', english: 'twelve', category: 'Numbers' },
    { german: 'zwanzig', english: 'twenty', category: 'Numbers' },
    { german: 'dreißig', english: 'thirty', category: 'Numbers' },
    { german: 'vierzig', english: 'forty', category: 'Numbers' },
    { german: 'fünfzig', english: 'fifty', category: 'Numbers' },
    { german: 'hundert', english: 'one hundred', category: 'Numbers' },

    // Ordinal Numbers
    { german: 'erste', english: 'first', category: 'Ordinals' },
    { german: 'zweite', english: 'second', category: 'Ordinals' },
    { german: 'dritte', english: 'third', category: 'Ordinals' },
    { german: 'vierte', english: 'fourth', category: 'Ordinals' },
    { german: 'fünfte', english: 'fifth', category: 'Ordinals' },

    // Transportation
    { german: 'der Bahnhof', english: 'train station', category: 'Transportation' },
    { german: 'der Flughafen', english: 'airport', category: 'Transportation' },
    { german: 'der Bus', english: 'bus', category: 'Transportation' },
    { german: 'die U-Bahn', english: 'underground', category: 'Transportation' },
    { german: 'das Auto', english: 'car', category: 'Transportation' },
    { german: 'das Fahrrad', english: 'bicycle', category: 'Transportation' },
    { german: 'der Zug', english: 'train', category: 'Transportation' },
    { german: 'die Straßenbahn', english: 'tram', category: 'Transportation' },
    { german: 'das Flugzeug', english: 'airplane', category: 'Transportation' },
    { german: 'das Taxi', english: 'taxi', category: 'Transportation' },
    { german: 'das Schiff', english: 'ship / boat', category: 'Transportation' },
    { german: 'zu Fuß gehen', english: 'to go on foot / to walk', category: 'Transportation' },
    { german: 'die Fahrkarte', english: 'ticket', category: 'Transportation' },
    { german: 'die Haltestelle', english: 'stop / station (bus or tram)', category: 'Transportation' },
    { german: 'der Bahnsteig', english: 'platform', category: 'Transportation' },
    { german: 'die Fahrgäste', english: 'passengers', category: 'Transportation' },
    { german: 'Schalter', english: 'check-in counter', category: 'Transportation' },
    { german: 'Auto mieten', english: 'car rental', category: 'Transportation' },
    { german: 'einsteigen', english: 'to get on / board', category: 'Transportation' },
    { german: 'aussteigen', english: 'to get off / exit', category: 'Transportation' },
    { german: 'umsteigen', english: 'to change trains', category: 'Transportation' },
    { german: 'fahren', english: 'to drive / to ride', category: 'Transportation' },
    { german: 'abfahren', english: 'to leave / depart', category: 'Transportation' },
    { german: 'fliegen', english: 'to fly', category: 'Transportation' },
    { german: 'Wir nehmen den Bus.', english: 'We take the bus.', category: 'Transportation' },

    // Directions
    { german: 'rechts', english: 'right', category: 'Directions' },
    { german: 'links', english: 'left', category: 'Directions' },
    { german: 'geradeaus', english: 'straight ahead', category: 'Directions' },
    { german: 'da drüben', english: 'over there', category: 'Directions' },
    { german: 'hier', english: 'here', category: 'Directions' },
    { german: 'da / dort', english: 'there', category: 'Directions' },
    { german: 'oben', english: 'up / upstairs', category: 'Directions' },
    { german: 'unten', english: 'down / downstairs', category: 'Directions' },
    { german: 'vorne', english: 'at the front', category: 'Directions' },
    { german: 'hinten', english: 'at the back', category: 'Directions' },
    { german: 'um die Ecke', english: 'around the corner', category: 'Directions' },
    { german: 'an der Ampel', english: 'at the traffic light', category: 'Directions' },
    { german: 'die erste Straße', english: 'the first street', category: 'Directions' },
    { german: 'abbiegen', english: 'to turn', category: 'Directions' },
    { german: 'nach Hause', english: 'towards home', category: 'Directions' },
    { german: 'zurück', english: 'back / return', category: 'Directions' },
    { german: 'weit', english: 'far', category: 'Directions' },
    { german: 'nah', english: 'near', category: 'Directions' },
    { german: 'draußen', english: 'outside', category: 'Directions' },
    { german: 'innen', english: 'inside', category: 'Directions' },
    { german: 'auf dem Weg', english: 'on the way', category: 'Directions' },
    { german: 'auf der Straße', english: 'on the street', category: 'Directions' },

    // Places
    { german: 'die Straße', english: 'street', category: 'Places' },
    { german: 'das Hotel', english: 'hotel', category: 'Places' },
    { german: 'die Stadt', english: 'city', category: 'Places' },
    { german: 'das Dorf', english: 'village', category: 'Places' },
    { german: 'die Haltestelle', english: 'stop', category: 'Places' },
    { german: 'die Schule', english: 'school', category: 'Education' },
    { german: 'die Universität', english: 'university', category: 'Education' },
    { german: 'das Büro', english: 'office', category: 'Work' },
    { german: 'das Museum', english: 'museum', category: 'Places' },
    { german: 'der Park', english: 'park', category: 'Places' },
    { german: 'die Bank', english: 'bank', category: 'Places' },
    { german: 'die Post', english: 'post office', category: 'Places' },
    { german: 'das Kino', english: 'cinema', category: 'Places' },
    { german: 'das Café', english: 'café', category: 'Places' },
    { german: 'das Restaurant', english: 'restaurant', category: 'Places' },
    { german: 'die Bibliothek', english: 'library', category: 'Places' },
    { german: 'der Supermarkt', english: 'supermarket', category: 'Places' },
    { german: 'das Geschäft', english: 'shop', category: 'Places' },
    { german: 'dort', english: 'there', category: 'Places' },
    { german: 'weit', english: 'far', category: 'Places' },
    { german: 'nah', english: 'near', category: 'Places' },
    { german: 'hier', english: 'here', category: 'Places' },
    { german: 'das Theater', english: 'theater', category: 'Places' },
    { german: 'die Apotheke', english: 'pharmacy', category: 'Places' },
    { german: 'der Garten', english: 'garden', category: 'Places' },

    // Going Inside
    { german: 'ins Restaurant', english: 'to the restaurant', category: 'Going Inside' },
    { german: 'ins Hotel', english: 'to the hotel', category: 'Going Inside' },
    { german: 'ins Dorf', english: 'to the village', category: 'Going Inside' },
    { german: 'ins Büro', english: 'to the office', category: 'Going Inside' },
    { german: 'ins Konzert', english: 'to the concert', category: 'Going Inside' },
    { german: 'ins Museum', english: 'to the museum', category: 'Going Inside' },
    { german: 'ins Geschäft', english: 'to the shop', category: 'Going Inside' },
    { german: 'in die Straße', english: 'to the street', category: 'Going Inside' },
    { german: 'in die Universität', english: 'to the university', category: 'Going Inside' },
    { german: 'in die Bibliothek', english: 'to the library', category: 'Going Inside' },
    { german: 'in den Park', english: 'to the park', category: 'Going Inside' },
    { german: 'in den Wald', english: 'to the forest', category: 'Going Inside' },
    { german: 'zum Supermarkt', english: 'to the supermarket', category: 'Going Inside' },
    { german: 'zur Haltestelle', english: 'to the stop', category: 'Going Inside' },
    { german: 'zur Bank', english: 'to the bank', category: 'Going Inside' },
    { german: 'zur Post', english: 'to the post office', category: 'Going Inside' },
    { german: 'zur Arbeit', english: 'to work', category: 'Going Inside' },
    { german: 'zum Kino', english: 'to the cinema', category: 'Going Inside' },
    { german: 'zum Theater', english: 'to the theater', category: 'Going Inside' },
    { german: 'zum Cafe', english: 'to the café', category: 'Going Inside' },
    { german: 'nach Berlin', english: 'to Berlin', category: 'Going Inside' },
    { german: 'nach Hause', english: 'to home', category: 'Going Inside' },
    { german: 'in die USA', english: 'to the USA', category: 'Going Inside' },
    { german: 'nach Deutschland', english: 'to Germany', category: 'Going Inside' },
    { german: 'in den Iran', english: 'to Iran', category: 'Going Inside' },

    // House & Home
    { german: 'das Haus', english: 'house', category: 'Home' },
    { german: 'die Wohnung', english: 'flat', category: 'Home' },
    { german: 'das Zimmer', english: 'room', category: 'Home' },
    { german: 'das Wohnzimmer', english: 'living room', category: 'Home' },
    { german: 'die Küche', english: 'kitchen', category: 'Home' },
    { german: 'das Badezimmer', english: 'bathroom', category: 'Home' },
    { german: 'das Bett', english: 'bed', category: 'Home' },
    { german: 'der Tisch', english: 'table', category: 'Home' },
    { german: 'der Stuhl', english: 'chair', category: 'Home' },
    { german: 'die Lampe', english: 'lamp', category: 'Home' },
    { german: 'der Fernseher', english: 'television', category: 'Home' },
    { german: 'das Fenster', english: 'window', category: 'Home' },
    { german: 'die Tür', english: 'door', category: 'Home' },
    { german: 'der Schrank', english: 'wardrobe', category: 'Home' },
    { german: 'die Wand', english: 'wall', category: 'Home' },
    { german: 'das Sofa', english: 'sofa', category: 'Home' },
    { german: 'der Vorhang', english: 'curtain', category: 'Home' },
    { german: 'der Kühlschrank', english: 'fridge', category: 'Home' },
    { german: 'die Waschmachine', english: 'washing machine', category: 'Home' },

    // Clothing
    { german: 'die Hose', english: 'pants', category: 'Clothing' },
    { german: 'die Jacke', english: 'jacket', category: 'Clothing' },
    { german: 'die Kleidung', english: 'clothing', category: 'Clothing' },
    { german: 'die Schuhe', english: 'shoes', category: 'Clothing' },
    { german: 'das Hemd', english: 'shirt', category: 'Clothing' },
    { german: 'der Hut', english: 'hat', category: 'Clothing' },

    // Events
    { german: 'die Hochzeit', english: 'wedding', category: 'Events' },
    { german: 'Fest', english: 'party', category: 'Events' },

    // Verbs
    { german: 'aufstehen', english: 'to get up', category: 'Verbs' },
    { german: 'hoffen', english: 'to hope', category: 'Verbs' },
    { german: 'geben', english: 'to give', category: 'Verbs' },
    { german: 'frühstücken', english: 'to eat breakfast', category: 'Verbs' },
    { german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { german: 'lernen', english: 'to study / learn', category: 'Verbs' },
    { german: 'essen', english: 'to eat', category: 'Verbs' },
    { german: 'trinken', english: 'to drink', category: 'Verbs' },
    { german: 'fernsehen', english: 'to watch TV', category: 'Verbs' },
    { german: 'schlafen', english: 'to sleep', category: 'Verbs' },
    { german: 'treffen', english: 'to meet', category: 'Verbs' },
    { german: 'lesen', english: 'to read', category: 'Verbs' },
    { german: 'schreiben', english: 'to write', category: 'Verbs' },
    { german: 'sprechen', english: 'to speak', category: 'Verbs' },
    { german: 'gehen', english: 'to go', category: 'Verbs' },
    { german: 'kommen', english: 'to come', category: 'Verbs' },
    { german: 'fahren', english: 'to drive / travel', category: 'Verbs' },
    { german: 'rennen', english: 'to run', category: 'Verbs' },
    { german: 'spielen', english: 'to play', category: 'Verbs' },
    { german: 'kochen', english: 'to cook', category: 'Verbs' },
    { german: 'bleiben', english: 'to stay', category: 'Verbs' },
    { german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { german: 'leben', english: 'to live', category: 'Verbs' },
    { german: 'tun', english: 'to do', category: 'Verbs' },
    { german: 'rauchen', english: 'to smoke', category: 'Verbs' },
    { german: 'fragen', english: 'to ask', category: 'Verbs' },
    { german: 'tragen', english: 'to wear', category: 'Verbs' },
    { german: 'passieren', english: 'to happen', category: 'Verbs' },
    { german: 'singen', english: 'to sing', category: 'Verbs' },
    { german: 'einschlagen', english: 'to fall sleep', category: 'Verbs' },
    { german: 'vorstellen', english: 'to present', category: 'Verbs' },
    { german: 'benutzen', english: 'to use', category: 'Verbs' },
    { german: 'öffnen', english: 'to open', category: 'Verbs' },
    { german: 'schließen', english: 'to close', category: 'Verbs' },
    { german: 'buchstabieren', english: 'to spell', category: 'Verbs' },
    { german: 'tanzen', english: 'to dance', category: 'Verbs' },
    { german: 'zurück/schreiben', english: 'to write back', category: 'Verbs' },

    // Restuarant
    { german: 'Kellner', english: 'waiter', category: 'Restuarant' },
    { german: 'Kellnerin', english: 'waitress', category: 'Restuarant' },
    { german: 'Gast', english: 'guest', category: 'Restuarant' },
    { german: 'das Messer', english: 'knife', category: 'Restuarant' },
    { german: 'die Gabel', english: 'fork', category: 'Restuarant' },
    { german: 'der Löffel', english: 'spoon', category: 'Restuarant' },
    { german: 'der Teller', english: 'plate', category: 'Restuarant' },
    { german: 'das Glas', english: 'glass', category: 'Restuarant' },
    { german: 'die Tasse', english: 'cup', category: 'Restuarant' },
    { german: 'die Serviette', english: 'napkin', category: 'Restuarant' },
    { german: 'die Flasche', english: 'bottle', category: 'Restuarant' },
    { german: 'Gemüsesuppe', english: 'vegetable soup', category: 'Restuarant' },
    { german: 'die Speisekarte', english: 'menu', category: 'Restuarant' },
    { german: 'die Rechnung', english: 'bill / check', category: 'Restuarant' },
    { german: 'das Salz', english: 'salt', category: 'Restuarant' },
    { german: 'Schokoladenkuchen', english: 'chocolate cake', category: 'Restuarant' },
    { german: 'der Pfeffer', english: 'pepper', category: 'Restuarant' },
    { german: 'der Zucker', english: 'sugar', category: 'Restuarant' },
    { german: 'bestellen', english: 'to order', category: 'Restuarant' },
    { german: 'bezahlen', english: 'to pay', category: 'Restuarant' },
    { german: 'frühstücken', english: 'to eat breakfast', category: 'Restuarant' },
    { german: 'Kann ich bitte die Speisekarte haben?', english: 'Can I have the menu?', category: 'Restuarant' },
    { german: 'Vorspeise', english: 'appetizer', category: 'Restuarant' },
    { german: 'Hauptgericht', english: 'main course', category: 'Restuarant' },
    { german: 'Nachtisch', english: 'dessert', category: 'Restuarant' },
    { german: 'Getraenk', english: 'drink', category: 'Restuarant' },
    { german: 'Ich möchte eine Suppe', english: 'I would like soup', category: 'Restuarant' },
    { german: 'Möchten Sie noch etwas?', english: 'Would you like anything else?', category: 'Restuarant' },
    { german: 'Was möchtest du trinken?', english: 'What would you like to drink?', category: 'Restuarant' },
    { german: 'Das schmeckt gut', english: 'That tastes good', category: 'Restuarant' },
    { german: 'Prost', english: 'cheers', category: 'Restuarant' },
    { german: 'Guten Appetit', english: 'good appetite', category: 'Restuarant' },

    // W Frage
    { german: 'Wo', english: 'Where', category: 'W Frage' },
    { german: 'Woher', english: 'Where from', category: 'W Frage' },
    { german: 'Wohin', english: 'Where to', category: 'W Frage' },
    { german: 'Wann', english: 'When', category: 'W Frage' },
    { german: 'Warum', english: 'Why', category: 'W Frage' },
    { german: 'Wie', english: 'How', category: 'W Frage' },
    { german: 'Wie oft', english: 'How often', category: 'W Frage' },
    { german: 'Wie viel', english: 'How much', category: 'W Frage' },
    { german: 'Wie viele', english: 'How many', category: 'W Frage' },
    { german: 'Was', english: 'What', category: 'W Frage' },
    { german: 'Wer', english: 'Who', category: 'W Frage' },
    { german: 'Welche/r/s', english: 'Which', category: 'W Frage' },

    // Animals
    { german: 'der Hund', english: 'dog', category: 'Animals' },
    { german: 'die Katze', english: 'cat', category: 'Animals' },
    { german: 'das Pferd', english: 'horse', category: 'Animals' },
    { german: 'das Schwein', english: 'pig', category: 'Animals' },
    { german: 'die Kuh', english: 'cow', category: 'Animals' },
    { german: 'der Vogel', english: 'bird', category: 'Animals' },
    { german: 'der Fisch', english: 'fish', category: 'Animals' },
    { german: 'die Maus', english: 'mouse', category: 'Animals' },
    { german: 'das Kaninchen', english: 'rabbit', category: 'Animals' },
    { german: 'der Elefant', english: 'elephant', category: 'Animals' },
    { german: 'der Löwe', english: 'lion', category: 'Animals' },
    { german: 'die Schlange', english: 'snake', category: 'Animals' },
    { german: 'die Spinne', english: 'spider', category: 'Animals' },
    { german: 'die Biene', english: 'bee', category: 'Animals' },
    { german: 'die Ente', english: 'duck', category: 'Animals' },

    // Stationery
    { german: 'das Buch', english: 'book', category: 'Stationery' },
    { german: 'der Brief', english: 'letter', category: 'Stationery' },
    { german: 'die Postkarte', english: 'postcard', category: 'Stationery' },
    { german: 'der Stift', english: 'pen', category: 'Stationery' },
    { german: 'das Papier', english: 'paper', category: 'Stationery' },

    // Accessory
    { german: 'ArmbandUhr', english: 'wristwatch', category: 'Accessory' },
    { german: 'die Kamera', english: 'camera', category: 'Accessory' },
    { german: 'der Computer', english: 'computer', category: 'Accessory' },
    { german: 'das Handy', english: 'phone', category: 'Accessory' },
    { german: 'die Tasche', english: 'bag', category: 'Accessory' },
    { german: 'der Rucksack', english: 'backpack', category: 'Accessory' },
    { german: 'das Gepäck', english: 'suitcase', category: 'Accessory' },

    // Materials
    { german: 'der Stoff', english: 'fabric', category: 'Materials' },
    { german: 'das Holz', english: 'wood', category: 'Materials' },
    { german: 'das Metal', english: 'metal', category: 'Materials' },
    { german: 'das Leder', english: 'leather', category: 'Materials' },
    { german: 'das Glas', english: 'glass', category: 'Materials' },
    { german: 'der Kunststoff', english: 'plastic', category: 'Materials' },


    // Verb Akkusative
    { german: 'haben', english: 'to have', category: 'Accusative Verbs' },
    { german: 'brauchen', english: 'to need', category: 'Accusative Verbs' },
    { german: 'parken', english: 'to park', category: 'Accusative Verbs' },
    { german: 'essen', english: 'to eat', category: 'Accusative Verbs' },
    { german: 'trinken', english: 'to drink', category: 'Accusative Verbs' },
    { german: 'sehen', english: 'to see', category: 'Accusative Verbs' },
    { german: 'hören', english: 'to hear', category: 'Accusative Verbs' },
    { german: 'kaufen', english: 'to buy', category: 'Accusative Verbs' },
    { german: 'bestellen', english: 'to order', category: 'Accusative Verbs' },
    { german: 'suchen', english: 'to look for', category: 'Accusative Verbs' },
    { german: 'finden', english: 'to find', category: 'Accusative Verbs' },
    { german: 'kochen', english: 'to cook', category: 'Accusative Verbs' },
    { german: 'verstehen', english: 'to understand', category: 'Accusative Verbs' },
    { german: 'besuchen', english: 'to visit', category: 'Accusative Verbs' },
    { german: 'anrufen', english: 'to call (on phone)', category: 'Accusative Verbs' },
    { german: 'schreiben', english: 'to write', category: 'Accusative Verbs' },
    { german: 'kennen', english: 'to know', category: 'Accusative Verbs' },


    // Dative
    { german: 'helfen', english: 'to help', category: 'Dative Verbs' },
    { german: 'danken', english: 'to thank', category: 'Dative Verbs' },
    { german: 'gefallen', english: 'to please / to like', category: 'Dative Verbs' },
    { german: 'gehören', english: 'to belong to', category: 'Dative Verbs' },
    { german: 'gratulieren', english: 'to congratulate', category: 'Dative Verbs' },
    { german: 'passen', english: 'to fit', category: 'Dative Verbs' },
    { german: 'antworten', english: 'to answer', category: 'Dative Verbs' },
    { german: 'zuhören', english: 'to listen to', category: 'Dative Verbs' },
    { german: 'schmecken', english: 'to taste (good) to', category: 'Dative Verbs' },
    { german: 'glauben', english: 'to believe', category: 'Dative Verbs' },
    { german: 'vertrauen', english: 'to trust', category: 'Dative Verbs' },
    { german: 'verzeihen', english: 'to forgive', category: 'Dative Verbs' },
    { german: 'wehtun', english: 'to hurt', category: 'Dative Verbs' },
    { german: 'folgen', english: 'to follow', category: 'Dative Verbs' },
    { german: 'passieren', english: 'to happen to', category: 'Dative Verbs' },

    // separatable Verbs
    { german: 'mitkommen', english: 'to come with', category: 'Separatable Verbs' },
    { german: 'aufkommen', english: 'to open', category: 'Separatable Verbs' },
    { german: 'aufmachen', english: 'to make', category: 'Separatable Verbs' },
    { german: 'mitspielen', english: 'to play with', category: 'Separatable Verbs' },

    // Weather
    { german: 'das Wetter', english: 'weather', category: 'Weather' },
    { german: 'die Sonne', english: 'sun', category: 'Weather' },
    { german: 'der Regen', english: 'rain', category: 'Weather' },
    { german: 'der Schnee', english: 'snow', category: 'Weather' },
    { german: 'der Wind', english: 'wind', category: 'Weather' },
    { german: 'warm', english: 'warm', category: 'Weather' },
    { german: 'kalt', english: 'cold', category: 'Weather' },
    { german: 'heiß', english: 'hot', category: 'Weather' },
    { german: 'kühl', english: 'cool', category: 'Weather' },
    { german: 'bewölkt', english: 'cloudy', category: 'Weather' },
    { german: 'neblig', english: 'foggy', category: 'Weather' },

    // Vacation
    { german: 'der Urlaub', english: 'vacation', category: 'Vacation' },

    // Prepositions
    { german: 'auf', english: 'on', category: 'Prepositions' },
    { german: 'an', english: 'at', category: 'Prepositions' },
    { german: 'ab', english: 'from - Dativ', category: 'Prepositions' },
    { german: 'bei', english: 'at - Dativ', category: 'Prepositions' },
    { german: 'durch', english: 'through - Akku', category: 'Prepositions' },
    { german: 'im', english: 'in', category: 'Prepositions' },
    { german: 'in', english: 'in', category: 'Prepositions' },
    { german: 'mit', english: 'with - Dativ', category: 'Prepositions' },
    { german: 'nach', english: 'after - Dativ', category: 'Prepositions' },
    { german: 'unter', english: 'under', category: 'Prepositions' },
    { german: 'zu', english: 'to - Dativ', category: 'Prepositions' },
    { german: 'hinter', english: 'behind', category: 'Prepositions' },
    { german: 'vor', english: 'before', category: 'Prepositions' },
    { german: 'ohne', english: 'without - Akku', category: 'Prepositions' },
    { german: 'mit', english: 'with', category: 'Prepositions' },
    { german: 'außer', english: 'except - Dativ', category: 'Prepositions' },
    { german: 'um', english: 'around - Akku', category: 'Prepositions' },
    { german: 'gegen', english: 'against - Akku', category: 'Prepositions' },
    { german: 'gegenüber', english: 'in front of - Dativ', category: 'Prepositions' },
    { german: 'Nach', english: 'after', category: 'Prepositions' },
    { german: 'aus', english: 'from - Dativ', category: 'Prepositions' },
    { german: 'von', english: 'from - Dativ', category: 'Prepositions' },
    { german: 'seit', english: 'since (for) - Dativ', category: 'Prepositions' },
    { german: 'nebe', english: 'beside', category: 'Prepositions' },
    { german: 'zwischen', english: 'between', category: 'Prepositions' },
    { german: 'für', english: 'for - Akku', category: 'Prepositions' },
    { german: 'bis', english: 'until - Akku', category: 'Prepositions' },

    // Health
    { german: 'der Arzt / die Ärztin', english: 'doctor', category: 'Health' },
    { german: 'der Zahnarzt / die Zahnärztin', english: 'dentist', category: 'Health' },
    { german: 'das Krankenhaus', english: 'hospital', category: 'Health' },
    { german: 'die Apotheke', english: 'pharmacy', category: 'Health' },
    { german: 'das Rezept', english: 'prescription', category: 'Health' },
    { german: 'die Tablette', english: 'tablet', category: 'Health' },
    { german: 'der Schmerz', english: 'pain', category: 'Health' },
    { german: 'das Fieber', english: 'fever', category: 'Health' },
    { german: 'die Erkältung', english: 'cold', category: 'Health' },
    { german: 'der Husten', english: 'cough', category: 'Health' },

    // Body Parts
    { german: 'der Kopf', english: 'head', category: 'Body' },
    { german: 'die Hand', english: 'hand', category: 'Body' },
    { german: 'der Arm', english: 'arm', category: 'Body' },
    { german: 'das Bein', english: 'leg', category: 'Body' },
    { german: 'der Rücken', english: 'back', category: 'Body' },
    { german: 'die Nase', english: 'nose', category: 'Body' },
    { german: 'der Mund', english: 'mouth', category: 'Body' },
    { german: 'das Auge', english: 'eye', category: 'Body' },
    { german: 'der Fuß', english: 'foot', category: 'Body' },
    { german: 'das Herz', english: 'heart', category: 'Body' },
    { german: 'das Gesicht', english: 'face', category: 'Body' },

    // Adjectives
    { german: 'groß', english: 'big / tall', category: 'Adjectives' },
    { german: 'klein', english: 'small / short', category: 'Adjectives' },
    { german: 'schön', english: 'beautiful', category: 'Adjectives' },
    { german: 'hässlich', english: 'ugly', category: 'Adjectives' },
    { german: 'alt', english: 'old', category: 'Adjectives' },
    { german: 'jung', english: 'young', category: 'Adjectives' },
    { german: 'neu', english: 'new', category: 'Adjectives' },
    { german: 'gut', english: 'good', category: 'Adjectives' },
    { german: 'schlecht', english: 'bad', category: 'Adjectives' },
    { german: 'freundlich', english: 'friendly', category: 'Adjectives' },
    { german: 'teuer', english: 'expensive', category: 'Adjectives' },
    { german: 'billig, güenstig', english: 'cheap', category: 'Adjectives' },
    { german: 'einfach', english: 'easy', category: 'Adjectives' },
    { german: 'schwer', english: 'difficult', category: 'Adjectives' },
    { german: 'ruhig', english: 'quiet', category: 'Adjectives' },
    { german: 'laut', english: 'loud', category: 'Adjectives' },
    { german: 'sauber', english: 'clean', category: 'Adjectives' },
    { german: 'schmutzig', english: 'dirty', category: 'Adjectives' },
    { german: 'nett', english: 'nice', category: 'Adjectives' },
    { german: 'langweilig', english: 'boring', category: 'Adjectives' },
    { german: 'interessant', english: 'interesting', category: 'Adjectives' },
    { german: 'lecker', english: 'tasty', category: 'Adjectives' },
    { german: 'müde', english: 'tired', category: 'Adjectives' },
    { german: 'gesund', english: 'healthy', category: 'Adjectives' },
    { german: 'krank', english: 'sick', category: 'Adjectives' },
    { german: 'lustig', english: 'funny', category: 'Adjectives' },
    { german: 'müde', english: 'tired', category: 'Adjectives' },
    { german: 'praktisch', english: 'usefull and practical', category: 'Adjectives' },
    { german: 'modern', english: 'modern', category: 'Adjectives' },
    { german: 'schnell', english: 'fast', category: 'Adjectives' },
    { german: 'langsam', english: 'slow', category: 'Adjectives' },

    // Hobbies
    { german: 'Zeitung lesen', english: 'reading the newspaper', category: 'Hobbies' },
    { german: 'das Buch', english: 'book', category: 'Hobbies' },
    { german: 'der Film', english: 'movie', category: 'Hobbies' },
    { german: 'das Spiel', english: 'game', category: 'Hobbies' },
    { german: 'der Sport', english: 'sport', category: 'Hobbies' },
    { german: 'die Musik', english: 'music', category: 'Hobbies' },
    { german: 'die Fotografie', english: 'photography', category: 'Hobbies' },
    { german: 'das Fitnessstudio', english: 'gym', category: 'Hobbies' },
    { german: 'Fußball spielen', english: 'playing football', category: 'Hobbies' },
    { german: 'Gittare spielen', english: 'playing Guitar', category: 'Hobbies' },
    { german: 'das Klavier', english: 'piano', category: 'Hobbies' },
    { german: 'Schwimmbad gehen', english: 'swimming', category: 'Hobbies' },

];

export default VOCABULARY