const VOCABULARY = [
    { id: 1, german: 'Hallo', english: 'hello', category: 'Greetings' },
    { id: 2, german: 'Guten Morgen', english: 'good morning', category: 'Greetings' },
    { id: 3, german: 'Guten Tag', english: 'good day', category: 'Greetings' },
    { id: 4, german: 'Guten Abend', english: 'good evening', category: 'Greetings' },
    { id: 5, german: 'Gute Nacht', english: 'good night', category: 'Greetings' },
    { id: 6, german: 'willkommen', english: 'welcome', category: 'Greetings' },
    { id: 7, german: 'Wie geht\'s?', english: 'how are you?', category: 'Greetings' },
    { id: 8, german: 'Danke', english: 'thank you', category: 'Greetings' },
    { id: 9, german: 'gern geschehen', english: 'You\'re welcome', category: 'Greetings' },
    { id: 10, german: 'Bitte', english: 'please / you\'re welcome', category: 'Greetings' },
    { id: 11, german: 'leider', english: 'unfortunately', category: 'Greetings' },
    { id: 12, german: 'Auf wiedersehen', english: 'goodbye', category: 'Greetings' },
    { id: 13, german: 'nicht schlecht', english: 'not bad', category: 'Greetings' },
    { id: 14, german: 'so lala', english: 'so so', category: 'Greetings' },
    { id: 15, german: 'freut mich', english: 'nice to meet you', category: 'Greetings' },
    { id: 16, german: 'Was machen sie beruflich?', english: 'What do you do professionally?', category: 'Greetings' },
    { id: 17, german: 'Ich arbeite als IT-Ingenieur', english: 'I work as an IT engineer', category: 'Greetings' },
    { id: 18, german: 'noch einmal', english: 'one more time', category: 'Greetings' },
    { id: 19, german: 'der Kollege', english: 'colleague', category: 'Work' },
    { id: 20, german: 'der Mitarbeiter', english: 'employee', category: 'Work' },
    { id: 21, german: 'der Arbeiter', english: 'worker', category: 'Work' },
    { id: 22, german: 'der Chef', english: 'boss', category: 'Work' },
    { id: 23, german: 'Ich heiße...', english: 'my name is...', category: 'Personal Info' },
    { id: 24, german: 'Woher kommst du?', english: 'where are you from?', category: 'Personal Info' },
    { id: 25, german: 'Ich komme aus...', english: 'I come from...', category: 'Personal Info' },
    { id: 26, german: 'Ich bin ... Jahre alt', english: 'I am ... years old', category: 'Personal Info' },
    { id: 27, german: 'Ich wohne in...', english: 'I live in...', category: 'Personal Info' },
    { id: 28, german: 'Wie heißt du?', english: 'What is your name?', category: 'Personal Info' },
    { id: 29, german: 'Wer bist du?', english: 'Who are you?', category: 'Personal Info' },
    { id: 30, german: 'Wie geht es dir?', english: 'How are you?', category: 'Personal Info' },
    { id: 31, german: 'Freut mich', english: 'Pleased to meet you', category: 'Personal Info' },
    { id: 32, german: 'ledig', english: 'single', category: 'Personal Info' },
    { id: 33, german: 'verheiratet', english: 'married', category: 'Personal Info' },
    { id: 34, german: 'Ich bin Student(in)', english: 'I am a student', category: 'Personal Info' },
    { id: 35, german: 'Beruf', english: 'profession / job', category: 'Personal Info' },
    { id: 36, german: 'Hobbys', english: 'hobbies', category: 'Personal Info' },
    { id: 37, german: 'die Telefonnummer', english: 'phone number', category: 'Personal Info' },
    { id: 38, german: 'die Adresse', english: 'address', category: 'Personal Info' },
    { id: 39, german: 'die Staatsangehörigkeit', english: 'nationality', category: 'Personal Info' },
    { id: 40, german: 'Sprechen Sie Deutsch?', english: 'Do you speak German? (formal)', category: 'Personal Info' },
    { id: 41, german: 'Ich spreche ein bisschen...', english: 'I speak a little...', category: 'Personal Info' },
    { id: 42, german: 'meine Muttersprache', english: 'my native language', category: 'Personal Info' },
    { id: 43, german: 'der Geburstag', english: 'birthday', category: 'Personal Info' },
    { id: 44, german: 'der Arzt', english: 'doctor', category: 'Jobs' },
    { id: 45, german: 'der Lehrer', english: 'teacher', category: 'Jobs' },
    { id: 46, german: 'der Kellner', english: 'waiter', category: 'Jobs' },
    { id: 47, german: 'der Polizist', english: 'police officer', category: 'Jobs' },
    { id: 48, german: 'der Mechaniker', english: 'mechanic', category: 'Jobs' },
    { id: 49, german: 'der Engenieur', english: 'Engineer', category: 'Jobs' },
    { id: 50, german: 'der Student', english: 'student', category: 'Jobs' },
    { id: 51, german: 'der Koch', english: 'cook', category: 'Jobs' },
    { id: 52, german: 'die Mutter', english: 'mother', category: 'Family' },
    { id: 53, german: 'der Vater', english: 'father', category: 'Family' },
    { id: 54, german: 'die Eltern', english: 'parents', category: 'Family' },
    { id: 55, german: 'der Bruder', english: 'brother', category: 'Family' },
    { id: 56, german: 'die Schwester', english: 'sister', category: 'Family' },
    { id: 57, german: 'das Geschwister', english: 'siblings', category: 'Family' },
    { id: 58, german: 'die Frau', english: 'woman / wife', category: 'Family' },
    { id: 59, german: 'der Mann', english: 'man / husband', category: 'Family' },
    { id: 60, german: 'das Kind', english: 'child', category: 'Family' },
    { id: 61, german: 'die Kinder', english: 'children', category: 'Family' },
    { id: 62, german: 'die Familie', english: 'family', category: 'Family' },
    { id: 63, german: 'der Freund / die Freundin', english: 'friend / boyfriend / girlfriend', category: 'Family' },
    { id: 64, german: 'das Essen', english: 'food', category: 'Food & Drink' },
    { id: 65, german: 'das Getränk', english: 'drink', category: 'Food & Drink' },
    { id: 66, german: 'das Brot', english: 'bread', category: 'Food & Drink' },
    { id: 67, german: 'das Brötchen', english: 'bread roll', category: 'Food & Drink' },
    { id: 68, german: 'der Apfel', english: 'apple', category: 'Food & Drink' },
    { id: 69, german: 'die Banane', english: 'banana', category: 'Food & Drink' },
    { id: 70, german: 'das Wasser', english: 'water', category: 'Food & Drink' },
    { id: 71, german: 'der Kaffee', english: 'coffee', category: 'Food & Drink' },
    { id: 72, german: 'der Tee', english: 'tea', category: 'Food & Drink' },
    { id: 73, german: 'das Bier', english: 'beer', category: 'Food & Drink' },
    { id: 74, german: 'der Wein', english: 'wine', category: 'Food & Drink' },
    { id: 75, german: 'die Milch', english: 'milk', category: 'Food & Drink' },
    { id: 76, german: 'der Saft', english: 'juice', category: 'Food & Drink' },
    { id: 77, german: 'das Frühstück', english: 'breakfast', category: 'Food & Drink' },
    { id: 78, german: 'das Mittagessen', english: 'lunch', category: 'Food & Drink' },
    { id: 79, german: 'das Abendessen', english: 'dinner', category: 'Food & Drink' },
    { id: 80, german: 'die Suppe', english: 'soup', category: 'Food & Drink' },
    { id: 81, german: 'der Salat', english: 'salad', category: 'Food & Drink' },
    { id: 82, german: 'der Zucker', english: 'sugar', category: 'Food & Drink' },
    { id: 83, german: 'das Salz', english: 'salt', category: 'Food & Drink' },
    { id: 84, german: 'das Hähnchen', english: 'chicken', category: 'Food & Drink' },
    { id: 85, german: 'der Fisch', english: 'fish', category: 'Food & Drink' },
    { id: 86, german: 'das Ei', english: 'egg', category: 'Food & Drink' },
    { id: 87, german: 'der Kuchen', english: 'cake', category: 'Food & Drink' },
    { id: 88, german: 'der honig', english: 'honey', category: 'Food & Drink' },
    { id: 89, german: 'die Marmelade', english: 'jam', category: 'Food & Drink' },
    { id: 90, german: 'lecker', english: 'delicious', category: 'Food & Drink' },
    { id: 91, german: 'der Käse', english: 'cheese', category: 'Food & Drink' },
    { id: 92, german: 'Große', english: 'big', category: 'Measurement' },
    { id: 93, german: 'kleine', english: 'small', category: 'Measurement' },
    { id: 94, german: 'kurz', english: 'short', category: 'Measurement' },
    { id: 95, german: 'lang', english: 'long', category: 'Measurement' },
    { id: 96, german: 'das Obst', english: 'fruit', category: 'Fruits' },
    { id: 97, german: 'der Apfel', english: 'apple', category: 'Fruits' },
    { id: 98, german: 'die Banane', english: 'banana', category: 'Fruits' },
    { id: 99, german: 'die Erdbeere', english: 'strawberry', category: 'Fruits' },
    { id: 100, german: 'die Orangen', english: 'orange', category: 'Fruits' },
    { id: 101, german: 'der Kasse', english: 'cashier', category: 'Supermarket' },
    { id: 102, german: 'bar', english: 'cash', category: 'Supermarket' },
    { id: 103, german: 'mit Karte', english: 'with card', category: 'Supermarket' },
    { id: 104, german: 'der Kassenbon', english: 'receipt', category: 'Supermarket' },
    { id: 105, german: 'zahlen', english: 'to pay', category: 'Supermarket' },
    { id: 106, german: 'die Farbe', english: 'color', category: 'Colors' },
    { id: 107, german: 'Blau', english: 'blue', category: 'Colors' },
    { id: 108, german: 'Rot', english: 'red', category: 'Colors' },
    { id: 109, german: 'Gelb', english: 'yellow', category: 'Colors' },
    { id: 110, german: 'Grün', english: 'green', category: 'Colors' },
    { id: 111, german: 'Weiß', english: 'white', category: 'Colors' },
    { id: 112, german: 'Schwarz', english: 'black', category: 'Colors' },
    { id: 113, german: 'Gelb', english: 'yellow', category: 'Colors' },
    { id: 114, german: 'heute', english: 'today', category: 'Time' },
    { id: 115, german: 'morgen', english: 'tomorrow', category: 'Time' },
    { id: 116, german: 'gestern', english: 'yesterday', category: 'Time' },
    { id: 117, german: 'jetzt', english: 'now', category: 'Time' },
    { id: 118, german: 'bald', english: 'soon', category: 'Time' },
    { id: 119, german: 'Uhr', english: 'o\'clock', category: 'Time' },
    { id: 120, german: 'Stunde', english: 'hour', category: 'Time' },
    { id: 121, german: 'Minute', english: 'minute', category: 'Time' },
    { id: 122, german: 'Zeit', english: 'time', category: 'Time' },
    { id: 123, german: 'immer', english: 'always', category: 'Time' },
    { id: 124, german: 'oft', english: 'often', category: 'Time' },
    { id: 125, german: 'manchmal', english: 'sometimes', category: 'Time' },
    { id: 126, german: 'selten', english: 'rarely', category: 'Time' },
    { id: 127, german: 'nie', english: 'never', category: 'Time' },
    { id: 128, german: 'Viertel vor fünf', english: 'quarter to five', category: 'Time' },
    { id: 129, german: 'Viertel nach fünf', english: 'quarter past five', category: 'Time' },
    { id: 130, german: 'es ist halb acht', english: 'half past seven', category: 'Time' },
    { id: 131, german: 'der Tag', english: 'day', category: 'Time' },
    { id: 132, german: 'die Woche', english: 'week', category: 'Time' },
    { id: 133, german: 'der Monat', english: 'month', category: 'Time' },
    { id: 134, german: 'das Jahr', english: 'year', category: 'Time' },
    { id: 135, german: 'das wochenende', english: 'weekend', category: 'Time' },
    { id: 136, german: 'später', english: 'later', category: 'Time' },
    { id: 137, german: 'in der nacht', english: 'at night', category: 'Time' },
    { id: 138, german: 'am Deinstagnachmittag', english: 'on Wednesday afternoon', category: 'Time' },
    { id: 139, german: 'am Mittwochabend', english: 'on Wednesday evening', category: 'Time' },
    { id: 140, german: 'am Montag', english: 'on Monday', category: 'Time' },
    { id: 141, german: 'heute Abend', english: 'tonight', category: 'Time' },
    { id: 142, german: 'heute Morgen', english: 'this morning', category: 'Time' },
    { id: 143, german: 'um 12:00 Uhr', english: 'at 12:00 o\'clock', category: 'Time' },
    { id: 144, german: 'von 12:00 bis 13:15 Uhr', english: 'from 12:00 to 13:15', category: 'Time' },
    { id: 145, german: 'nach dem Abendessen', english: 'after dinner', category: 'Time' },
    { id: 146, german: 'nächste Woche', english: 'next week', category: 'Time' },
    { id: 147, german: 'am kommenden sonntag', english: 'next Sunday', category: 'Time' },
    { id: 148, german: 'Wie spät ist es?', english: 'What time is it?', category: 'Time' },
    { id: 149, german: 'am letzten wochenende', english: 'last weekend', category: 'Time' },
    { id: 150, german: 'Es ist zwei Uhr', english: 'It is two o\'clock', category: 'Time' },
    { id: 151, german: 'Es ist zwei Uhr fuüfzhen', english: 'It is 02:15', category: 'Time' },
    { id: 152, german: 'Wann gehst du zur Arbeit?', english: 'When do you go to work?', category: 'Time' },
    { id: 153, german: 'Um wie viel Uhr?', english: 'At what time?', category: 'Time' },
    { id: 154, german: 'Hast du um Samstag zeit?', english: 'Are you free on Saturday?', category: 'Time' },
    { id: 155, german: 'Ja, ich bin frei', english: 'Yes, I am free', category: 'Time' },
    { id: 156, german: 'Perfekt, bis dann!', english: 'Perfect, see you then!', category: 'Time' },
    { id: 157, german: 'Montag', english: 'Monday', category: 'Days' },
    { id: 158, german: 'Dienstag', english: 'Tuesday', category: 'Days' },
    { id: 159, german: 'Mittwoch', english: 'Wednesday', category: 'Days' },
    { id: 160, german: 'Donnerstag', english: 'Thursday', category: 'Days' },
    { id: 161, german: 'Freitag', english: 'Friday', category: 'Days' },
    { id: 162, german: 'Samstag', english: 'Saturday', category: 'Days' },
    { id: 163, german: 'Sonntag', english: 'Sunday', category: 'Days' },
    { id: 164, german: 'Januar', english: 'January', category: 'Months' },
    { id: 165, german: 'Februar', english: 'February', category: 'Months' },
    { id: 166, german: 'März', english: 'March', category: 'Months' },
    { id: 167, german: 'April', english: 'April', category: 'Months' },
    { id: 168, german: 'Mai', english: 'May', category: 'Months' },
    { id: 169, german: 'Juni', english: 'June', category: 'Months' },
    { id: 170, german: 'Juli', english: 'July', category: 'Months' },
    { id: 171, german: 'August', english: 'August', category: 'Months' },
    { id: 172, german: 'September', english: 'September', category: 'Months' },
    { id: 173, german: 'Oktober', english: 'October', category: 'Months' },
    { id: 174, german: 'November', english: 'November', category: 'Months' },
    { id: 175, german: 'Dezember', english: 'December', category: 'Months' },


    { id: 176, german: 'eins', english: 'one', category: 'Numbers' },
    { id: 177, german: 'zwei', english: 'two', category: 'Numbers' },
    { id: 178, german: 'drei', english: 'three', category: 'Numbers' },
    { id: 179, german: 'vier', english: 'four', category: 'Numbers' },
    { id: 180, german: 'fünf', english: 'five', category: 'Numbers' },
    { id: 181, german: 'sechs', english: 'six', category: 'Numbers' },
    { id: 182, german: 'sieben', english: 'seven', category: 'Numbers' },
    { id: 183, german: 'acht', english: 'eight', category: 'Numbers' },
    { id: 184, german: 'neun', english: 'nine', category: 'Numbers' },
    { id: 185, german: 'zehn', english: 'ten', category: 'Numbers' },
    { id: 186, german: 'elf', english: 'eleven', category: 'Numbers' },
    { id: 187, german: 'zwölf', english: 'twelve', category: 'Numbers' },
    { id: 188, german: 'zwanzig', english: 'twenty', category: 'Numbers' },
    { id: 189, german: 'dreißig', english: 'thirty', category: 'Numbers' },
    { id: 190, german: 'vierzig', english: 'forty', category: 'Numbers' },
    { id: 191, german: 'fünfzig', english: 'fifty', category: 'Numbers' },
    { id: 192, german: 'hundert', english: 'one hundred', category: 'Numbers' },
    { id: 193, german: 'erste', english: 'first', category: 'Ordinals' },
    { id: 194, german: 'zweite', english: 'second', category: 'Ordinals' },
    { id: 195, german: 'dritte', english: 'third', category: 'Ordinals' },
    { id: 196, german: 'vierte', english: 'fourth', category: 'Ordinals' },
    { id: 197, german: 'fünfte', english: 'fifth', category: 'Ordinals' },
    { id: 198, german: 'der Bahnhof', english: 'train station', category: 'Transportation' },
    { id: 199, german: 'der Flughafen', english: 'airport', category: 'Transportation' },
    { id: 200, german: 'der Bus', english: 'bus', category: 'Transportation' },
    { id: 201, german: 'die U-Bahn', english: 'underground', category: 'Transportation' },
    { id: 202, german: 'das Auto', english: 'car', category: 'Transportation' },
    { id: 203, german: 'das Fahrrad', english: 'bicycle', category: 'Transportation' },
    { id: 204, german: 'der Zug', english: 'train', category: 'Transportation' },
    { id: 205, german: 'die Straßenbahn', english: 'tram', category: 'Transportation' },
    { id: 206, german: 'das Flugzeug', english: 'airplane', category: 'Transportation' },
    { id: 207, german: 'das Taxi', english: 'taxi', category: 'Transportation' },
    { id: 208, german: 'das Schiff', english: 'ship / boat', category: 'Transportation' },
    { id: 209, german: 'zu Fuß gehen', english: 'to go on foot / to walk', category: 'Transportation' },
    { id: 210, german: 'die Fahrkarte', english: 'ticket', category: 'Transportation' },
    { id: 211, german: 'die Haltestelle', english: 'stop / station (bus or tram)', category: 'Transportation' },
    { id: 212, german: 'der Bahnsteig', english: 'platform', category: 'Transportation' },
    { id: 213, german: 'die Fahrgäste', english: 'passengers', category: 'Transportation' },
    { id: 214, german: 'Schalter', english: 'check-in counter', category: 'Transportation' },
    { id: 215, german: 'Auto mieten', english: 'car rental', category: 'Transportation' },
    { id: 216, german: 'einsteigen', english: 'to get on / board', category: 'Transportation' },
    { id: 217, german: 'aussteigen', english: 'to get off / exit', category: 'Transportation' },
    { id: 218, german: 'umsteigen', english: 'to change trains', category: 'Transportation' },
    { id: 219, german: 'fahren', english: 'to drive / to ride', category: 'Transportation' },
    { id: 220, german: 'abfahren', english: 'to leave / depart', category: 'Transportation' },
    { id: 221, german: 'fliegen', english: 'to fly', category: 'Transportation' },
    { id: 222, german: 'Wir nehmen den Bus.', english: 'We take the bus.', category: 'Transportation' },
    { id: 223, german: 'rechts', english: 'right', category: 'Directions' },
    { id: 224, german: 'links', english: 'left', category: 'Directions' },
    { id: 225, german: 'geradeaus', english: 'straight ahead', category: 'Directions' },
    { id: 226, german: 'da drüben', english: 'over there', category: 'Directions' },
    { id: 227, german: 'hier', english: 'here', category: 'Directions' },
    { id: 228, german: 'da / dort', english: 'there', category: 'Directions' },
    { id: 229, german: 'oben', english: 'up / upstairs', category: 'Directions' },
    { id: 230, german: 'unten', english: 'down / downstairs', category: 'Directions' },
    { id: 231, german: 'vorne', english: 'at the front', category: 'Directions' },
    { id: 232, german: 'hinten', english: 'at the back', category: 'Directions' },
    { id: 233, german: 'um die Ecke', english: 'around the corner', category: 'Directions' },
    { id: 234, german: 'an der Ampel', english: 'at the traffic light', category: 'Directions' },
    { id: 235, german: 'die erste Straße', english: 'the first street', category: 'Directions' },
    { id: 236, german: 'abbiegen', english: 'to turn', category: 'Directions' },
    { id: 237, german: 'nach Hause', english: 'towards home', category: 'Directions' },
    { id: 238, german: 'zurück', english: 'back / return', category: 'Directions' },
    { id: 239, german: 'weit', english: 'far', category: 'Directions' },
    { id: 240, german: 'nah', english: 'near', category: 'Directions' },
    { id: 241, german: 'draußen', english: 'outside', category: 'Directions' },
    { id: 242, german: 'innen', english: 'inside', category: 'Directions' },
    { id: 243, german: 'auf dem Weg', english: 'on the way', category: 'Directions' },
    { id: 244, german: 'auf der Straße', english: 'on the street', category: 'Directions' },
    { id: 245, german: 'die Straße', english: 'street', category: 'Places' },
    { id: 246, german: 'das Hotel', english: 'hotel', category: 'Places' },
    { id: 247, german: 'die Stadt', english: 'city', category: 'Places' },
    { id: 248, german: 'das Dorf', english: 'village', category: 'Places' },
    { id: 249, german: 'die Haltestelle', english: 'stop', category: 'Places' },
    { id: 250, german: 'die Schule', english: 'school', category: 'Education' },
    { id: 251, german: 'die Universität', english: 'university', category: 'Education' },
    { id: 252, german: 'das Büro', english: 'office', category: 'Work' },
    { id: 253, german: 'das Museum', english: 'museum', category: 'Places' },
    { id: 254, german: 'der Park', english: 'park', category: 'Places' },
    { id: 255, german: 'die Bank', english: 'bank', category: 'Places' },
    { id: 256, german: 'die Post', english: 'post office', category: 'Places' },
    { id: 257, german: 'das Kino', english: 'cinema', category: 'Places' },
    { id: 258, german: 'das Café', english: 'café', category: 'Places' },
    { id: 259, german: 'das Restaurant', english: 'restaurant', category: 'Places' },
    { id: 260, german: 'die Bibliothek', english: 'library', category: 'Places' },
    { id: 261, german: 'der Supermarkt', english: 'supermarket', category: 'Places' },
    { id: 262, german: 'das Geschäft', english: 'shop', category: 'Places' },
    { id: 263, german: 'dort', english: 'there', category: 'Places' },
    { id: 264, german: 'weit', english: 'far', category: 'Places' },
    { id: 265, german: 'nah', english: 'near', category: 'Places' },
    { id: 266, german: 'hier', english: 'here', category: 'Places' },
    { id: 267, german: 'das Theater', english: 'theater', category: 'Places' },
    { id: 268, german: 'die Apotheke', english: 'pharmacy', category: 'Places' },
    { id: 269, german: 'der Garten', english: 'garden', category: 'Places' },
    { id: 270, german: 'ins Restaurant', english: 'to the restaurant', category: 'Going Inside' },
    { id: 271, german: 'ins Hotel', english: 'to the hotel', category: 'Going Inside' },
    { id: 272, german: 'ins Dorf', english: 'to the village', category: 'Going Inside' },
    { id: 273, german: 'ins Büro', english: 'to the office', category: 'Going Inside' },
    { id: 274, german: 'ins Konzert', english: 'to the concert', category: 'Going Inside' },
    { id: 275, german: 'ins Museum', english: 'to the museum', category: 'Going Inside' },
    { id: 276, german: 'ins Geschäft', english: 'to the shop', category: 'Going Inside' },
    { id: 277, german: 'in die Straße', english: 'to the street', category: 'Going Inside' },
    { id: 278, german: 'in die Universität', english: 'to the university', category: 'Going Inside' },
    { id: 279, german: 'in die Bibliothek', english: 'to the library', category: 'Going Inside' },
    { id: 280, german: 'in den Park', english: 'to the park', category: 'Going Inside' },
    { id: 281, german: 'in den Wald', english: 'to the forest', category: 'Going Inside' },
    { id: 282, german: 'zum Supermarkt', english: 'to the supermarket', category: 'Going Inside' },
    { id: 283, german: 'zur Haltestelle', english: 'to the stop', category: 'Going Inside' },
    { id: 284, german: 'zur Bank', english: 'to the bank', category: 'Going Inside' },
    { id: 285, german: 'zur Post', english: 'to the post office', category: 'Going Inside' },
    { id: 286, german: 'zur Arbeit', english: 'to work', category: 'Going Inside' },
    { id: 287, german: 'zum Kino', english: 'to the cinema', category: 'Going Inside' },
    { id: 288, german: 'zum Theater', english: 'to the theater', category: 'Going Inside' },
    { id: 289, german: 'zum Cafe', english: 'to the café', category: 'Going Inside' },
    { id: 290, german: 'nach Berlin', english: 'to Berlin', category: 'Going Inside' },
    { id: 291, german: 'nach Hause', english: 'to home', category: 'Going Inside' },
    { id: 292, german: 'in die USA', english: 'to the USA', category: 'Going Inside' },
    { id: 293, german: 'nach Deutschland', english: 'to Germany', category: 'Going Inside' },
    { id: 294, german: 'in den Iran', english: 'to Iran', category: 'Going Inside' },
    { id: 295, german: 'das Haus', english: 'house', category: 'Home' },
    { id: 296, german: 'die Wohnung', english: 'flat', category: 'Home' },
    { id: 297, german: 'das Zimmer', english: 'room', category: 'Home' },
    { id: 298, german: 'das Wohnzimmer', english: 'living room', category: 'Home' },
    { id: 299, german: 'die Küche', english: 'kitchen', category: 'Home' },
    { id: 300, german: 'das Badezimmer', english: 'bathroom', category: 'Home' },
    { id: 301, german: 'das Bett', english: 'bed', category: 'Home' },
    { id: 302, german: 'der Tisch', english: 'table', category: 'Home' },
    { id: 303, german: 'der Stuhl', english: 'chair', category: 'Home' },
    { id: 304, german: 'die Lampe', english: 'lamp', category: 'Home' },
    { id: 305, german: 'der Fernseher', english: 'television', category: 'Home' },
    { id: 306, german: 'das Fenster', english: 'window', category: 'Home' },
    { id: 307, german: 'die Tür', english: 'door', category: 'Home' },
    { id: 308, german: 'der Schrank', english: 'wardrobe', category: 'Home' },
    { id: 309, german: 'die Wand', english: 'wall', category: 'Home' },
    { id: 310, german: 'das Sofa', english: 'sofa', category: 'Home' },
    { id: 311, german: 'der Vorhang', english: 'curtain', category: 'Home' },
    { id: 312, german: 'der Kühlschrank', english: 'fridge', category: 'Home' },
    { id: 313, german: 'die Waschmachine', english: 'washing machine', category: 'Home' },
    { id: 314, german: 'die Hose', english: 'pants', category: 'Clothing' },
    { id: 315, german: 'die Jacke', english: 'jacket', category: 'Clothing' },
    { id: 316, german: 'die Kleidung', english: 'clothing', category: 'Clothing' },
    { id: 317, german: 'die Schuhe', english: 'shoes', category: 'Clothing' },
    { id: 318, german: 'das Hemd', english: 'shirt', category: 'Clothing' },
    { id: 319, german: 'der Hut', english: 'hat', category: 'Clothing' },
    { id: 320, german: 'die Hochzeit', english: 'wedding', category: 'Events' },
    { id: 321, german: 'Fest', english: 'party', category: 'Events' },
    { id: 322, german: 'aufstehen', english: 'to get up', category: 'Verbs' },
    { id: 323, german: 'hoffen', english: 'to hope', category: 'Verbs' },
    { id: 324, german: 'geben', english: 'to give', category: 'Verbs' },
    { id: 325, german: 'frühstücken', english: 'to eat breakfast', category: 'Verbs' },
    { id: 326, german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { id: 327, german: 'lernen', english: 'to study / learn', category: 'Verbs' },
    { id: 328, german: 'essen', english: 'to eat', category: 'Verbs' },
    { id: 329, german: 'trinken', english: 'to drink', category: 'Verbs' },
    { id: 330, german: 'fernsehen', english: 'to watch TV', category: 'Verbs' },
    { id: 331, german: 'schlafen', english: 'to sleep', category: 'Verbs' },
    { id: 332, german: 'treffen', english: 'to meet', category: 'Verbs' },
    { id: 333, german: 'lesen', english: 'to read', category: 'Verbs' },
    { id: 334, german: 'schreiben', english: 'to write', category: 'Verbs' },
    { id: 335, german: 'sprechen', english: 'to speak', category: 'Verbs' },
    { id: 336, german: 'gehen', english: 'to go', category: 'Verbs' },
    { id: 337, german: 'kommen', english: 'to come', category: 'Verbs' },
    { id: 338, german: 'fahren', english: 'to drive / travel', category: 'Verbs' },
    { id: 339, german: 'rennen / laufen', english: 'to run', category: 'Verbs' },
    { id: 340, german: 'spielen', english: 'to play', category: 'Verbs' },
    { id: 341, german: 'kochen', english: 'to cook', category: 'Verbs' },
    { id: 342, german: 'bleiben', english: 'to stay', category: 'Verbs' },
    { id: 343, german: 'arbeiten', english: 'to work', category: 'Verbs' },
    { id: 344, german: 'leben', english: 'to live', category: 'Verbs' },
    { id: 345, german: 'tun', english: 'to do', category: 'Verbs' },
    { id: 346, german: 'rauchen', english: 'to smoke', category: 'Verbs' },
    { id: 347, german: 'fragen', english: 'to ask', category: 'Verbs' },
    { id: 348, german: 'tragen', english: 'to wear', category: 'Verbs' },
    { id: 349, german: 'passieren', english: 'to happen', category: 'Verbs' },
    { id: 350, german: 'singen', english: 'to sing', category: 'Verbs' },
    { id: 351, german: 'einschlafen', english: 'to fall sleep', category: 'Verbs' },
    { id: 352, german: 'vorstellen', english: 'to present', category: 'Verbs' },
    { id: 353, german: 'benutzen', english: 'to use', category: 'Verbs' },
    { id: 354, german: 'öffnen', english: 'to open', category: 'Verbs' },
    { id: 355, german: 'schließen', english: 'to close', category: 'Verbs' },
    { id: 356, german: 'buchstabieren', english: 'to spell', category: 'Verbs' },
    { id: 357, german: 'tanzen', english: 'to dance', category: 'Verbs' },
    { id: 358, german: 'zurück/schreiben', english: 'to write back', category: 'Verbs' },
    { id: 359, german: 'Kellner', english: 'waiter', category: 'Restuarant' },
    { id: 360, german: 'Kellnerin', english: 'waitress', category: 'Restuarant' },
    { id: 361, german: 'Gast', english: 'guest', category: 'Restuarant' },
    { id: 362, german: 'das Messer', english: 'knife', category: 'Restuarant' },
    { id: 363, german: 'die Gabel', english: 'fork', category: 'Restuarant' },
    { id: 364, german: 'der Löffel', english: 'spoon', category: 'Restuarant' },
    { id: 365, german: 'der Teller', english: 'plate', category: 'Restuarant' },
    { id: 366, german: 'das Glas', english: 'glass', category: 'Restuarant' },
    { id: 367, german: 'die Tasse', english: 'cup', category: 'Restuarant' },
    { id: 368, german: 'die Serviette', english: 'napkin', category: 'Restuarant' },
    { id: 369, german: 'die Flasche', english: 'bottle', category: 'Restuarant' },
    { id: 370, german: 'Gemüsesuppe', english: 'vegetable soup', category: 'Restuarant' },
    { id: 371, german: 'die Speisekarte', english: 'menu', category: 'Restuarant' },
    { id: 372, german: 'die Rechnung', english: 'bill / check', category: 'Restuarant' },
    { id: 373, german: 'das Salz', english: 'salt', category: 'Restuarant' },
    { id: 374, german: 'Schokoladenkuchen', english: 'chocolate cake', category: 'Restuarant' },
    { id: 375, german: 'der Pfeffer', english: 'pepper', category: 'Restuarant' },
    { id: 376, german: 'der Zucker', english: 'sugar', category: 'Restuarant' },
    { id: 377, german: 'bestellen', english: 'to order', category: 'Restuarant' },
    { id: 378, german: 'bezahlen', english: 'to pay', category: 'Restuarant' },
    { id: 379, german: 'frühstücken', english: 'to eat breakfast', category: 'Restuarant' },
    { id: 380, german: 'Kann ich bitte die Speisekarte haben?', english: 'Can I have the menu?', category: 'Restuarant' },
    { id: 381, german: 'Vorspeise', english: 'appetizer', category: 'Restuarant' },
    { id: 382, german: 'Hauptgericht', english: 'main course', category: 'Restuarant' },
    { id: 383, german: 'Nachtisch', english: 'dessert', category: 'Restuarant' },
    { id: 384, german: 'Getraenk', english: 'drink', category: 'Restuarant' },
    { id: 385, german: 'Ich möchte eine Suppe', english: 'I would like soup', category: 'Restuarant' },
    { id: 386, german: 'Möchten Sie noch etwas?', english: 'Would you like anything else?', category: 'Restuarant' },
    { id: 387, german: 'Was möchtest du trinken?', english: 'What would you like to drink?', category: 'Restuarant' },
    { id: 388, german: 'Das schmeckt gut', english: 'That tastes good', category: 'Restuarant' },
    { id: 389, german: 'Prost', english: 'cheers', category: 'Restuarant' },
    { id: 390, german: 'Guten Appetit', english: 'good appetite', category: 'Restuarant' },
    { id: 391, german: 'Wo', english: 'Where', category: 'W Frage' },
    { id: 392, german: 'Woher', english: 'Where from', category: 'W Frage' },
    { id: 393, german: 'Wohin', english: 'Where to', category: 'W Frage' },
    { id: 394, german: 'Wann', english: 'When', category: 'W Frage' },
    { id: 395, german: 'Warum', english: 'Why', category: 'W Frage' },
    { id: 396, german: 'Wie', english: 'How', category: 'W Frage' },
    { id: 397, german: 'Wie oft', english: 'How often', category: 'W Frage' },
    { id: 398, german: 'Wie viel', english: 'How much', category: 'W Frage' },
    { id: 399, german: 'Wie viele', english: 'How many', category: 'W Frage' },
    { id: 400, german: 'Was', english: 'What', category: 'W Frage' },
    { id: 401, german: 'Wer', english: 'Who', category: 'W Frage' },
    { id: 402, german: 'Welche/r/s', english: 'Which', category: 'W Frage' },
    { id: 403, german: 'der Hund', english: 'dog', category: 'Animals' },
    { id: 404, german: 'die Katze', english: 'cat', category: 'Animals' },
    { id: 405, german: 'das Pferd', english: 'horse', category: 'Animals' },
    { id: 406, german: 'das Schwein', english: 'pig', category: 'Animals' },
    { id: 407, german: 'die Kuh', english: 'cow', category: 'Animals' },
    { id: 408, german: 'der Vogel', english: 'bird', category: 'Animals' },
    { id: 409, german: 'der Fisch', english: 'fish', category: 'Animals' },
    { id: 410, german: 'die Maus', english: 'mouse', category: 'Animals' },
    { id: 411, german: 'das Kaninchen', english: 'rabbit', category: 'Animals' },
    { id: 412, german: 'der Elefant', english: 'elephant', category: 'Animals' },
    { id: 413, german: 'der Löwe', english: 'lion', category: 'Animals' },
    { id: 414, german: 'die Schlange', english: 'snake', category: 'Animals' },
    { id: 415, german: 'die Spinne', english: 'spider', category: 'Animals' },
    { id: 416, german: 'die Biene', english: 'bee', category: 'Animals' },
    { id: 417, german: 'die Ente', english: 'duck', category: 'Animals' },
    { id: 418, german: 'das Buch', english: 'book', category: 'Stationery' },
    { id: 419, german: 'der Brief', english: 'letter', category: 'Stationery' },
    { id: 420, german: 'die Postkarte', english: 'postcard', category: 'Stationery' },
    { id: 421, german: 'der Stift', english: 'pen', category: 'Stationery' },
    { id: 422, german: 'das Papier', english: 'paper', category: 'Stationery' },
    { id: 423, german: 'ArmbandUhr', english: 'wristwatch', category: 'Accessory' },
    { id: 424, german: 'die Kamera', english: 'camera', category: 'Accessory' },
    { id: 425, german: 'der Computer', english: 'computer', category: 'Accessory' },
    { id: 426, german: 'das Handy', english: 'phone', category: 'Accessory' },
    { id: 427, german: 'die Tasche', english: 'bag', category: 'Accessory' },
    { id: 428, german: 'der Rucksack', english: 'backpack', category: 'Accessory' },
    { id: 429, german: 'das Gepäck', english: 'suitcase', category: 'Accessory' },
    { id: 430, german: 'der Stoff', english: 'fabric', category: 'Materials' },
    { id: 431, german: 'das Holz', english: 'wood', category: 'Materials' },
    { id: 432, german: 'das Metal', english: 'metal', category: 'Materials' },
    { id: 433, german: 'das Leder', english: 'leather', category: 'Materials' },
    { id: 434, german: 'das Glas', english: 'glass', category: 'Materials' },
    { id: 435, german: 'der Kunststoff', english: 'plastic', category: 'Materials' },
    { id: 436, german: 'haben', english: 'to have', category: 'Accusative Verbs' },
    { id: 437, german: 'brauchen', english: 'to need', category: 'Accusative Verbs' },
    { id: 438, german: 'parken', english: 'to park', category: 'Accusative Verbs' },
    { id: 439, german: 'essen', english: 'to eat', category: 'Accusative Verbs' },
    { id: 440, german: 'trinken', english: 'to drink', category: 'Accusative Verbs' },
    { id: 441, german: 'sehen', english: 'to see', category: 'Accusative Verbs' },
    { id: 442, german: 'hören', english: 'to hear', category: 'Accusative Verbs' },
    { id: 443, german: 'kaufen', english: 'to buy', category: 'Accusative Verbs' },
    { id: 444, german: 'bestellen', english: 'to order', category: 'Accusative Verbs' },
    { id: 445, german: 'suchen', english: 'to look for', category: 'Accusative Verbs' },
    { id: 446, german: 'finden', english: 'to find', category: 'Accusative Verbs' },
    { id: 447, german: 'kochen', english: 'to cook', category: 'Accusative Verbs' },
    { id: 448, german: 'verstehen', english: 'to understand', category: 'Accusative Verbs' },
    { id: 449, german: 'besuchen', english: 'to visit', category: 'Accusative Verbs' },
    { id: 450, german: 'anrufen', english: 'to call (on phone)', category: 'Accusative Verbs' },
    { id: 451, german: 'schreiben', english: 'to write', category: 'Accusative Verbs' },
    { id: 452, german: 'kennen', english: 'to know', category: 'Accusative Verbs' },
    { id: 453, german: 'helfen', english: 'to help', category: 'Dative Verbs' },
    { id: 454, german: 'danken', english: 'to thank', category: 'Dative Verbs' },
    { id: 455, german: 'gefallen', english: 'to please / to like', category: 'Dative Verbs' },
    { id: 456, german: 'gehören', english: 'to belong to', category: 'Dative Verbs' },
    { id: 457, german: 'gratulieren', english: 'to congratulate', category: 'Dative Verbs' },
    { id: 458, german: 'passen', english: 'to fit', category: 'Dative Verbs' },
    { id: 459, german: 'antworten', english: 'to answer', category: 'Dative Verbs' },
    { id: 460, german: 'zuhören', english: 'to listen to', category: 'Dative Verbs' },
    { id: 461, german: 'schmecken', english: 'to taste (good) to', category: 'Dative Verbs' },
    { id: 462, german: 'glauben', english: 'to believe', category: 'Dative Verbs' },
    { id: 463, german: 'vertrauen', english: 'to trust', category: 'Dative Verbs' },
    { id: 464, german: 'verzeihen', english: 'to forgive', category: 'Dative Verbs' },
    { id: 465, german: 'wehtun', english: 'to hurt', category: 'Dative Verbs' },
    { id: 466, german: 'folgen', english: 'to follow', category: 'Dative Verbs' },
    { id: 467, german: 'passieren', english: 'to happen to', category: 'Dative Verbs' },
    { id: 468, german: 'mitkommen', english: 'to come with', category: 'Separable Verbs' },
    { id: 469, german: 'einsteigen', english: 'to get in / board', category: 'Separable Verbs' },
    { id: 470, german: 'aufmachen', english: 'to open', category: 'Separable Verbs' },
    { id: 471, german: 'mitspielen', english: 'to play with', category: 'Separable Verbs' },
    { id: 472, german: 'das Wetter', english: 'weather', category: 'Weather' },
    { id: 473, german: 'die Sonne', english: 'sun', category: 'Weather' },
    { id: 474, german: 'der Regen', english: 'rain', category: 'Weather' },
    { id: 475, german: 'der Schnee', english: 'snow', category: 'Weather' },
    { id: 476, german: 'der Wind', english: 'wind', category: 'Weather' },
    { id: 477, german: 'warm', english: 'warm', category: 'Weather' },
    { id: 478, german: 'kalt', english: 'cold', category: 'Weather' },
    { id: 479, german: 'heiß', english: 'hot', category: 'Weather' },
    { id: 480, german: 'kühl', english: 'cool', category: 'Weather' },
    { id: 481, german: 'bewölkt', english: 'cloudy', category: 'Weather' },
    { id: 482, german: 'neblig', english: 'foggy', category: 'Weather' },
    { id: 483, german: 'der Urlaub', english: 'vacation', category: 'Vacation' },
    { id: 484, german: 'auf', english: 'on', category: 'Prepositions' },
    { id: 485, german: 'an', english: 'at', category: 'Prepositions' },
    { id: 486, german: 'ab', english: 'from - Dativ', category: 'Prepositions' },
    { id: 487, german: 'bei', english: 'at - Dativ', category: 'Prepositions' },
    { id: 488, german: 'durch', english: 'through - Akku', category: 'Prepositions' },
    { id: 489, german: 'im', english: 'in', category: 'Prepositions' },
    { id: 490, german: 'in', english: 'in', category: 'Prepositions' },
    { id: 491, german: 'mit', english: 'with - Dativ', category: 'Prepositions' },
    { id: 492, german: 'nach', english: 'after - Dativ', category: 'Prepositions' },
    { id: 493, german: 'unter', english: 'under', category: 'Prepositions' },
    { id: 494, german: 'zu', english: 'to - Dativ', category: 'Prepositions' },
    { id: 495, german: 'hinter', english: 'behind', category: 'Prepositions' },
    { id: 496, german: 'vor', english: 'before', category: 'Prepositions' },
    { id: 497, german: 'ohne', english: 'without - Akku', category: 'Prepositions' },
    { id: 498, german: 'mit', english: 'with', category: 'Prepositions' },
    { id: 499, german: 'außer', english: 'except - Dativ', category: 'Prepositions' },
    { id: 500, german: 'um', english: 'around - Akku', category: 'Prepositions' },
    { id: 501, german: 'gegen', english: 'against - Akku', category: 'Prepositions' },
    { id: 502, german: 'gegenüber', english: 'in front of - Dativ', category: 'Prepositions' },
    { id: 503, german: 'Nach', english: 'after', category: 'Prepositions' },
    { id: 504, german: 'aus', english: 'from - Dativ', category: 'Prepositions' },
    { id: 505, german: 'von', english: 'from - Dativ', category: 'Prepositions' },
    { id: 506, german: 'seit', english: 'since (for) - Dativ', category: 'Prepositions' },
    { id: 507, german: 'nebe', english: 'beside', category: 'Prepositions' },
    { id: 508, german: 'zwischen', english: 'between', category: 'Prepositions' },
    { id: 509, german: 'für', english: 'for - Akku', category: 'Prepositions' },
    { id: 510, german: 'bis', english: 'until - Akku', category: 'Prepositions' },
    { id: 511, german: 'der Arzt / die Ärztin', english: 'doctor', category: 'Health' },
    { id: 512, german: 'der Zahnarzt / die Zahnärztin', english: 'dentist', category: 'Health' },
    { id: 513, german: 'das Krankenhaus', english: 'hospital', category: 'Health' },
    { id: 514, german: 'die Apotheke', english: 'pharmacy', category: 'Health' },
    { id: 515, german: 'das Rezept', english: 'prescription', category: 'Health' },
    { id: 516, german: 'die Tablette', english: 'tablet', category: 'Health' },
    { id: 517, german: 'der Schmerz', english: 'pain', category: 'Health' },
    { id: 518, german: 'das Fieber', english: 'fever', category: 'Health' },
    { id: 519, german: 'die Erkältung', english: 'cold', category: 'Health' },
    { id: 520, german: 'der Husten', english: 'cough', category: 'Health' },
    { id: 521, german: 'der Kopf', english: 'head', category: 'Body' },
    { id: 522, german: 'die Hand', english: 'hand', category: 'Body' },
    { id: 523, german: 'der Arm', english: 'arm', category: 'Body' },
    { id: 524, german: 'das Bein', english: 'leg', category: 'Body' },
    { id: 525, german: 'der Rücken', english: 'back', category: 'Body' },
    { id: 526, german: 'die Nase', english: 'nose', category: 'Body' },
    { id: 527, german: 'der Mund', english: 'mouth', category: 'Body' },
    { id: 528, german: 'das Auge', english: 'eye', category: 'Body' },
    { id: 529, german: 'der Fuß', english: 'foot', category: 'Body' },
    { id: 530, german: 'das Herz', english: 'heart', category: 'Body' },
    { id: 531, german: 'das Gesicht', english: 'face', category: 'Body' },
    { id: 532, german: 'groß', english: 'big / tall', category: 'Adjectives' },
    { id: 533, german: 'klein', english: 'small / short', category: 'Adjectives' },
    { id: 534, german: 'schön', english: 'beautiful', category: 'Adjectives' },
    { id: 535, german: 'hässlich', english: 'ugly', category: 'Adjectives' },
    { id: 536, german: 'alt', english: 'old', category: 'Adjectives' },
    { id: 537, german: 'jung', english: 'young', category: 'Adjectives' },
    { id: 538, german: 'neu', english: 'new', category: 'Adjectives' },
    { id: 539, german: 'gut', english: 'good', category: 'Adjectives' },
    { id: 540, german: 'schlecht', english: 'bad', category: 'Adjectives' },
    { id: 541, german: 'freundlich', english: 'friendly', category: 'Adjectives' },
    { id: 542, german: 'teuer', english: 'expensive', category: 'Adjectives' },
    { id: 543, german: 'billig, güenstig', english: 'cheap', category: 'Adjectives' },
    { id: 544, german: 'einfach', english: 'easy', category: 'Adjectives' },
    { id: 545, german: 'schwer', english: 'difficult', category: 'Adjectives' },
    { id: 546, german: 'ruhig', english: 'quiet', category: 'Adjectives' },
    { id: 547, german: 'laut', english: 'loud', category: 'Adjectives' },
    { id: 548, german: 'sauber', english: 'clean', category: 'Adjectives' },
    { id: 549, german: 'schmutzig', english: 'dirty', category: 'Adjectives' },
    { id: 550, german: 'nett', english: 'nice', category: 'Adjectives' },
    { id: 551, german: 'langweilig', english: 'boring', category: 'Adjectives' },
    { id: 552, german: 'interessant', english: 'interesting', category: 'Adjectives' },
    { id: 553, german: 'lecker', english: 'tasty', category: 'Adjectives' },
    { id: 554, german: 'müde', english: 'tired', category: 'Adjectives' },
    { id: 555, german: 'gesund', english: 'healthy', category: 'Adjectives' },
    { id: 556, german: 'krank', english: 'sick', category: 'Adjectives' },
    { id: 557, german: 'lustig', english: 'funny', category: 'Adjectives' },
    { id: 558, german: 'müde', english: 'tired', category: 'Adjectives' },
    { id: 559, german: 'praktisch', english: 'usefull and practical', category: 'Adjectives' },
    { id: 560, german: 'modern', english: 'modern', category: 'Adjectives' },
    { id: 561, german: 'schnell', english: 'fast', category: 'Adjectives' },
    { id: 562, german: 'langsam', english: 'slow', category: 'Adjectives' },
    { id: 563, german: 'Zeitung lesen', english: 'reading the newspaper', category: 'Hobbies' },
    { id: 564, german: 'das Buch', english: 'book', category: 'Hobbies' },
    { id: 565, german: 'der Film', english: 'movie', category: 'Hobbies' },
    { id: 566, german: 'das Spiel', english: 'game', category: 'Hobbies' },
    { id: 567, german: 'der Sport', english: 'sport', category: 'Hobbies' },
    { id: 568, german: 'die Musik', english: 'music', category: 'Hobbies' },
    { id: 569, german: 'die Fotografie', english: 'photography', category: 'Hobbies' },
    { id: 570, german: 'das Fitnessstudio', english: 'gym', category: 'Hobbies' },
    { id: 571, german: 'Fußball spielen', english: 'playing football', category: 'Hobbies' },
    { id: 572, german: 'Gittare spielen', english: 'playing Guitar', category: 'Hobbies' },
    { id: 573, german: 'das Klavier', english: 'piano', category: 'Hobbies' },
    { id: 574, german: 'Schwimmbad gehen', english: 'swimming', category: 'Hobbies' },

    { id: 575, german: 'im Herbst', english: 'in autumn', category: 'Seasons' },
    { id: 576, german: 'im Sommer', english: 'in summer', category: 'Seasons' },
    { id: 577, german: 'im Winter', english: 'in winter', category: 'Seasons' },
    { id: 578, german: 'im Frühling', english: 'in spring', category: 'Seasons' },
    { id: 579, german: 'im Januar', english: 'in January', category: 'Time' },
    { id: 580, german: 'vor 5 Jahren', english: '5 years ago', category: 'Time' },
    { id: 581, german: 'ans Meer', english: 'to the sea', category: 'Going Inside' },
    { id: 582, german: 'der Urlaub', english: 'vacation / leave', category: 'Work' },
    { id: 583, german: 'der See', english: 'lake', category: 'Going Inside' },
    { id: 584, german: 'das Wetter', english: 'weather', category: 'Weather' },
    { id: 585, german: 'der Regen', english: 'rain', category: 'Weather' },
    { id: 586, german: 'der Schnee', english: 'snow', category: 'Weather' },
    { id: 587, german: 'der Wind', english: 'wind', category: 'Weather' },
    { id: 588, german: 'Es ist windig', english: 'it is windy', category: 'Weather' },
    { id: 589, german: 'Es ist kalt', english: 'it is cold', category: 'Weather' },
    { id: 590, german: 'Es ist heiß', english: 'it is hot', category: 'Weather' },
    { id: 591, german: 'Es ist sonnig', english: 'it is sunny', category: 'Weather' },
    { id: 592, german: 'Es ist bewölkt', english: 'it is cloudy', category: 'Weather' },
    { id: 593, german: 'Es ist neblig', english: 'it is foggy', category: 'Weather' },
    { id: 594, german: 'Es regnet', english: 'it is raining', category: 'Weather' },
    { id: 595, german: 'früh', english: 'early', category: 'Time' },
    { id: 596, german: 'stehen', english: 'to stand', category: 'Verbs' },
    { id: 597, german: 'Ich fahre mit dem Bus.', english: 'I go with the bus.', category: 'Transportation' },
    { id: 598, german: 'ich gehe zu fuß.', english: 'I go on foot.', category: 'Transportation' },
    { id: 599, german: 'das ist weit von hier', english: 'That is far from here', category: 'Directions' },
    { id: 600, german: 'das Geld', english: 'money', category: 'Supermarket' },
    { id: 601, german: 'tut mir leid', english: 'I am sorry', category: 'Greetings' },
    { id: 602, german: 'der Herd', english: 'stove', category: 'Home' },
    { id: 603, german: 'der Mülleimer', english: 'trash can / bin', category: 'Home' },
    { id: 604, german: 'vermissen', english: 'to miss', category: 'Verbs' },
    { id: 605, german: 'die Nachbarn', english: 'neighbours', category: 'Home' },
    { id: 606, german: 'zweimal pro woche', english: 'twice a week', category: 'Time' },
    { id: 607, german: 'das Stadtzentrum', english: 'city center', category: 'Places' },
    { id: 608, german: 'der Schlüssel', english: 'key', category: 'Accessory' },
    { id: 609, german: 'verlieren', english: 'lose', category: 'Verbs' },
    { id: 610, german: 'die Treppe', english: 'stairs', category: 'Home' },
    { id: 611, german: 'die Aufzug', english: 'elevator', category: 'Home' },
    { id: 612, german: 'Wie hoch ist die Miete?', english: 'How much is the rent?', category: 'Home' },
    { id: 613, german: 'Wie viel kostet die Wohnung?', english: 'How much is the apartment?', category: 'Home' },
    { id: 614, german: 'Wie groß ist die Wohnung?', english: 'How big is the apartment?', category: 'Home' },
    { id: 615, german: 'Wie viele Zimmer hat die Wohnung?', english: 'How many rooms does the apartment have?', category: 'Home' },
    { id: 616, german: 'Gibt es eine Küche?', english: 'Is there a kitchen?', category: 'Home' },
    { id: 617, german: 'Ab wann ist die Wohnung frei?', english: 'When is the apartment free?', category: 'Home' },
    { id: 618, german: 'die möblierte Wohnung', english: 'furnished apartment', category: 'Home' },
    { id: 619, german: 'die Kaltmiete', english: 'The basic rent', category: 'Home' },
    { id: 620, german: 'die Warmmiete', english: 'the rent including utilities', category: 'Home' },
    { id: 621, german: 'Die Nebenkosten', english: 'the additional costs', category: 'Home' },
    { id: 622, german: 'die Haustiere', english: 'pets', category: 'Home' },
    { id: 623, german: 'die Kaution', english: 'deposit', category: 'Home' },
    { id: 624, german: 'die Wohnung zur miete', english: 'apartment for rent', category: 'Home' },
    { id: 625, german: 'Nähe vom Zentrum', english: 'near the center', category: 'Home' },
    { id: 626, german: 'die Wohnung ist im zweiten Stock.', english: 'the apartment is on the second floor.', category: 'Home' },
    { id: 627, german: 'umziehen', english: 'to move', category: 'Verbs' },
    { id: 628, german: 'ruhigen Stadtteil', english: 'quiet neighborhood', category: 'Home' },
    { id: 629, german: 'der Koffer', english: 'suitcase', category: 'Vacation' },
    { id: 630, german: 'verlassen', english: 'to leave', category: 'Verbs' },
    { id: 631, german: 'jemanden', english: 'someone', category: 'People' },
    { id: 632, german: 'Vielen Dank für Ihre Hilfe', english: 'Thank you for your help', category: 'Greetings' },
    { id: 633, german: 'pünktlich', english: 'on time', category: 'Time' },
    { id: 634, german: 'absagen', english: 'to cancel', category: 'Verbs' },
    { id: 635, german: 'verschieben', english: 'to move / postpone', category: 'Verbs' },
    { id: 636, german: 'ausgehen', english: 'to go', category: 'Verbs' },
    { id: 637, german: 'zurückkehren', english: 'to return', category: 'Verbs' },
    { id: 638, german: 'unbedingt', english: 'for sure, without a doubt', category: 'Adverbs' },
    { id: 639, german: 'vielleicht', english: 'maybe', category: 'Adverbs' },
    { id: 640, german: 'auf keinen fall', english: 'absolutely not', category: 'Adverbs' },
    { id: 641, german: 'Pause', english: 'pause', category: 'Work' },
    { id: 642, german: 'Geschenk', english: 'gift', category: 'Events' },
    { id: 643, german: 'der Geburtstag', english: 'birthday', category: 'Events' },
    { id: 644, german: 'die Firma', english: 'company, firm', category: 'Work' },
    { id: 645, german: 'zukunft', english: 'future', category: 'Time' },
    { id: 646, german: 'die Welt', english: 'world', category: 'Places' },
    { id: 647, german: 'allein', english: 'alone', category: 'Adverbs' },
    { id: 648, german: 'Reise', english: 'trip', category: 'Vacation' },
    { id: 649, german: 'mehr', english: 'more', category: 'Adverbs' },
    { id: 650, german: 'bauen', english: 'to build', category: 'Verbs' },
    { id: 651, german: 'die Nachrichten', english: 'news', category: 'Society' },
    { id: 652, german: 'dauern', english: 'to last, to take time', category: 'Verbs' },
    { id: 653, german: 'Anfänger', english: 'beginner', category: 'Adjectives' },
    { id: 654, german: 'Profi', english: 'professional', category: 'Adjectives' },
    { id: 655, german: 'leise', english: 'quiet', category: 'Adjectives' },
    { id: 656, german: 'Nehmen Sie Platz!', english: 'Please take a seat!', category: 'Greetings' },
    { id: 657, german: 'der Zahn', english: 'tooth', category: 'Body' },
    { id: 658, german: 'Kopfschmerzen', english: 'headache', category: 'Health' },
    { id: 659, german: 'Zahnschmerzen', english: 'toothache', category: 'Health' },
    { id: 660, german: 'Mein Rücken tut weh', english: 'my back hurts', category: 'Health' },
    { id: 661, german: 'die Tablette', english: 'tablet', category: 'Health' },
    { id: 662, german: 'der Schmerz', english: 'pain', category: 'Health' },
    { id: 663, german: 'der Husten', english: 'cough', category: 'Health' },
    { id: 664, german: 'die Kapsel', english: 'capsule', category: 'Health' },
    { id: 665, german: 'der Sirup', english: 'syrup', category: 'Health' },
    { id: 666, german: 'Wie oft soll ich die Tabletten nehmen?', english: 'How often should I take the tablets?', category: 'Health' },
    { id: 667, german: 'Fieber', english: 'fever', category: 'Health' },
    { id: 668, german: 'das Medikament', english: 'medicine', category: 'Health' },
    { id: 669, german: 'die Menschen', english: 'people', category: 'People' },
    { id: 670, german: 'ernst', english: 'serious', category: 'Adjectives' },
    { id: 671, german: 'jeder', english: 'everyone', category: 'People' },
    { id: 672, german: 'Angebot', english: 'offer', category: 'Work' },
    { id: 673, german: 'abflug', english: 'departure', category: 'Transportation' },
    { id: 674, german: 'ab sofort', english: 'from now on', category: 'Time' },
    { id: 675, german: 'erzählen', english: 'to tell', category: 'Verbs' },
    { id: 676, german: 'entscheiden', english: 'to decide', category: 'Verbs' },
    { id: 677, german: 'verkaufen', english: 'to sell', category: 'Verbs' },
    { id: 678, german: 'lachen', english: 'to laugh', category: 'Verbs' },
    { id: 679, german: 'holen', english: 'pick up', category: 'Verbs' },
    { id: 680, german: 'waschen', english: 'to wash', category: 'Verbs' },
    { id: 681, german: 'mischen', english: 'to mix', category: 'Verbs' },
    { id: 682, german: 'wissen', english: 'to know', category: 'Verbs' },
    { id: 683, german: 'mussen', english: 'should', category: 'Verbs' },
    { id: 684, german: 'mogen', english: 'like', category: 'Verbs' },
    { id: 685, german: 'werden', english: 'become', category: 'Verbs' },
    { id: 686, german: 'aussehen', english: 'look like', category: 'Separable Verbs' },
    { id: 687, german: 'früher', english: 'earlier', category: 'Time' },
    { id: 688, german: 'dick', english: 'fat', category: 'Adjectives' },
    { id: 689, german: 'schlank', english: 'slim', category: 'Adjectives' },
    { id: 690, german: 'schick', english: 'handsome or attractive', category: 'Adjectives' },
    { id: 691, german: 'schlampig', english: 'untidy, sloopy', category: 'Adjectives' },
    { id: 692, german: 'hübsch', english: 'pretty', category: 'Adjectives' },
    { id: 693, german: 'Marjan sieht hübsch aus', english: 'Marjan looks pretty', category: 'Adjectives' },
    { id: 694, german: 'glücklich', english: 'happy', category: 'Adjectives' },
    { id: 695, german: 'unglücklich', english: 'sad, unhappy', category: 'Adjectives' },
    { id: 696, german: 'unfreundlich', english: 'unfriendly', category: 'Adjectives' },
    { id: 697, german: 'unwichtig', english: 'less important', category: 'Adjectives' },
    { id: 698, german: 'wichtig', english: 'important', category: 'Adjectives' },
    { id: 699, german: 'uninteressant', english: 'not interesting', category: 'Adjectives' },
    { id: 700, german: 'Unglaublich', english: 'unbelievable', category: 'Adjectives' },
    { id: 701, german: 'hilfsbereit', english: 'helpful', category: 'Adjectives' },
    { id: 702, german: 'sympathisch', english: 'sympathetic, friendly', category: 'Adjectives' },
    { id: 703, german: 'besonderes', english: 'special', category: 'Adjectives' },
    { id: 704, german: 'die Pflanze', english: 'plan', category: 'Home' },
    { id: 705, german: 'schon', english: 'already', category: 'Adverbs' },
    { id: 706, german: 'aussteigen', english: 'to get out / off', category: 'Separable Verbs' },
    { id: 707, german: 'umsteigen', english: 'change train / bus', category: 'Separable Verbs' },
    { id: 708, german: 'nervig', english: 'nervous', category: 'Adjectives' },
    { id: 709, german: 'heißen', english: 'to call', category: 'Verbs' },
    { id: 710, german: 'fertig', english: 'ready', category: 'Adjectives' },
    { id: 711, german: 'malen', english: 'to paint', category: 'Verbs' },
    { id: 712, german: 'dürfen', english: 'can', category: 'Verbs' },
    { id: 713, german: 'fehlen', english: 'miss', category: 'Verbs' },
    { id: 714, german: 'laden', english: 'to invite', category: 'Verbs' },
    { id: 715, german: 'aufräumen', english: 'to clean', category: 'Verbs' },
    { id: 716, german: 'sagen', english: 'to say', category: 'Verbs' },
    { id: 717, german: 'vergessen', english: 'to forget', category: 'Verbs' },
    { id: 718, german: 'studieren', english: 'to study', category: 'Verbs' },
    { id: 719, german: 'reparieren', english: 'to repair', category: 'Verbs' },
    { id: 720, german: 'abholen', english: 'to pick up', category: 'Verbs' },
    { id: 721, german: 'warten', english: 'to wait', category: 'Verbs' },
    { id: 722, german: 'liegen', english: 'be located, lie', category: 'Verbs' },
    { id: 723, german: 'einkaufen', english: 'to shop, perchase', category: 'Verbs' },
    { id: 724, german: 'außerdem', english: 'also', category: 'Prepositions' },
    { id: 725, german: 'normalerweise', english: 'usually', category: 'Adverbs' },
    { id: 726, german: 'ferien', english: 'holidays', category: 'Work' },
    { id: 727, german: 'das Wörterbuch', english: 'dictionary', category: 'Tool' },
    { id: 728, german: 'erlaubt', english: 'allowed', category: 'Public Places' },
    { id: 729, german: 'verboten', english: 'prohibited, forbidden', category: 'Public Places' },
    { id: 730, german: 'dürfen', english: 'to allow', category: 'Public Places' },
    { id: 731, german: 'spazieren', english: 'walk', category: 'Verbs' },
    { id: 732, german: 'Natur', english: 'nature', category: 'Public Places' },
    { id: 733, german: 'Grillen und Feuer machen ist verboten', english: 'grilling and fire making is prohibited', category: 'Public Places' },
    { id: 734, german: 'halten', english: 'keep, hold', category: 'Verbs' },
    { id: 735, german: 'vorsichtig', english: 'careful', category: 'Adjectives' },
    { id: 736, german: 'am ältesten', english: 'the oldest', category: 'Adjectives' },
    { id: 737, german: 'am modernsten', english: 'the most modern', category: 'Adjectives' },
    { id: 738, german: 'am teuersten', english: 'the most expensive', category: 'Adjectives' },
    { id: 739, german: 'am billigsten', english: 'the cheapest', category: 'Adjectives' },
    { id: 740, german: 'Ben ist so schick wie Marjan', english: 'Ben is so handsome as Marjan', category: 'Adjectives' },
    { id: 741, german: 'kleiner', english: 'smaller', category: 'Adjectives' },
    { id: 742, german: 'schöner', english: 'prettier', category: 'Adjectives' },
    { id: 743, german: 'teurer', english: 'more expensive', category: 'Adjectives' },
    { id: 744, german: 'dunkler', english: 'darker', category: 'Adjectives' },
    { id: 745, german: 'leckerer', english: 'more tasty', category: 'Adjectives' },
    { id: 746, german: 'länger', english: 'longer', category: 'Adjectives' },
    { id: 747, german: 'größer', english: 'bigger', category: 'Adjectives' },
    { id: 748, german: 'schneller', english: 'faster', category: 'Adjectives' },
    { id: 749, german: 'heller', english: 'brighter', category: 'Adjectives' },
    { id: 750, german: 'Ich bin größer als er.', english: 'I am bigger than him.', category: 'Adjectives' },
    { id: 751, german: 'Iran ist das schönste Land.', english: 'Iran is the most beautiful country.', category: 'Adjectives' },
    { id: 752, german: 'am liebsten', english: 'the most lovely', category: 'Adjectives' },
    { id: 753, german: 'Der Kaffee ist besser als Tee', english: 'coffee is better than tea', category: 'Adjectives' },
    { id: 754, german: 'Er hatte mehr Zeit als ich.', english: 'He had more time than I.', category: 'Adjectives' },
    { id: 755, german: 'näher', english: 'closer', category: 'Adjectives' },
    { id: 756, german: 'denn', english: 'because', category: 'Conjunctions' },
    { id: 757, german: 'und', english: 'and', category: 'Conjunctions' },
    { id: 758, german: 'oder', english: 'or', category: 'Conjunctions' },
    { id: 759, german: 'aber', english: 'but', category: 'Conjunctions' },
    { id: 760, german: 'durst', english: 'thirst', category: 'Adjectives' },
    { id: 761, german: 'hunger', english: 'hunger', category: 'Adjectives' },
    { id: 762, german: 'wertlos', english: 'worthless', category: 'Adjectives' },
    { id: 763, german: 'arbeitslos', english: 'unemployed', category: 'Adjectives' },
    { id: 764, german: 'schlaflos', english: 'sleepless', category: 'Adjectives' },
    { id: 765, german: 'ohne', english: 'without', category: 'Conjunctions' },
    { id: 766, german: 'mit', english: 'with', category: 'Conjunctions' },
    { id: 767, german: 'Wie ist das Wetter?', english: 'How is the weather?', category: 'Weather' },
    { id: 768, german: 'Es ist bewölkt.', english: 'It is cloudy.', category: 'Weather' },
    { id: 769, german: 'Es regnet', english: 'It is raining', category: 'Weather' },
    { id: 770, german: 'schon', english: 'already', category: 'Conjunctions' },
    { id: 771, german: 'dann', english: 'then', category: 'Conjunctions' },
    { id: 772, german: 'anders', english: 'different', category: 'Adjectives' },
    { id: 773, german: 'noch', english: 'still', category: 'Conjunctions' },
    { id: 774, german: 'mitnehmen', english: 'take along', category: 'Separable Verbs' },
    { id: 775, german: 'manche', english: 'some', category: 'Conjunctions' },
    { id: 776, german: 'überall', english: 'everywhere', category: 'Conjunctions' },
    { id: 777, german: 'das Ostern', english: 'Easter', category: 'Events' },
    { id: 778, german: 'das Weihnachten', english: 'Christmas', category: 'Events' },
    { id: 779, german: 'das Silvester', english: 'New Year', category: 'Events' },
    { id: 780, german: 'das Oktoberfest', english: 'beer festival', category: 'Events' },
    { id: 781, german: 'das Feuerwerk', english: 'fireworks', category: 'Events' },
    { id: 782, german: 'feiern', english: 'celebrate', category: 'Verbs' },
    { id: 783, german: 'freuen', english: 'be happy', category: 'Verbs' },
    { id: 784, german: 'einladung', english: 'invitation', category: 'Events' },
    { id: 785, german: 'Anfong Mai', english: 'beginning of May', category: 'Time' },
    { id: 786, german: 'lage', english: 'location', category: 'Home' },
    { id: 787, german: 'die Wanderung', english: 'hike', category: 'Hobbies' },
    { id: 788, german: 'empfehlen', english: 'recommend', category: 'Verbs' },
    { id: 789, german: 'Erwachsene', english: 'adult', category: 'People' },
    { id: 790, german: 'weil', english: 'because', category: 'Conjunctions' },
    { id: 791, german: 'übermorgen', english: 'the day after tomorrow', category: 'Time' },
    { id: 792, german: 'sollten', english: 'should', category: 'Verbs' },
    { id: 793, german: 'shoppen', english: 'shop', category: 'Verbs' },
    { id: 794, german: 'buchen', english: 'reserve, book', category: 'Verbs' },
    { id: 795, german: 'das ganze Wochenende', english: 'the whole weekend', category: 'Time' },
    { id: 796, german: 'zeigen', english: 'to show', category: 'Verbs' },
    { id: 797, german: 'herzlichen Glückwunsch zu..', english: 'Congratulations on ..', category: 'Greetings' },
    { id: 798, german: 'ausleihen', english: 'to borrow', category: 'Verbs' },
    { id: 799, german: 'teilnehmen', english: 'Participate, attend', category: 'Verbs' },
    { id: 800, german: 'im voraus', english: 'in advance', category: 'Conjunctions' },
    { id: 801, german: 'das Gehalt', english: 'salary', category: 'Work' },
    { id: 802, german: 'der Grund', english: 'the reason', category: 'General' },
    { id: 803, german: 'diesen', english: 'this', category: 'Conjunctions' },
    { id: 804, german: '', english: '', category: '' },
    { id: 805, german: '', english: '', category: '' },
    { id: 806, german: '', english: '', category: '' },
];


export default VOCABULARY

// 1 =
// 2 =
// 3 =
// 4 =
// 5 =
// 6 =
// 7 =
// 8 =
// 9 =
// 10 =
// 11 =
// 12 =
// 13 =
// 14 =
// 15 = 